set xth(point_types) {
	air-draught
	altitude
	anastomosis
	anchor
	aragonite
	archeo-material
	bedrock
	blocks
	breakdown-choke
	bridge
	camp
	cave-pearl
	clay
	continuation
	crystal
	curtain
	date
	debris
	dimensions
	disk
	entrance
	fixed-ladder
	flowstone
	flowstone-choke
	flute
	gradient
	guano
	gypsum
	gypsum-flower
	height
	helictite
	ice
	karren
	label
	low-end
	moonmilk
	narrow-end
	no-equipment
	paleo-material
	passage-height
	pebbles
	pillar
	popcorn
	raft
	raft-cone
	remark
	rimstone-dam
	rimstone-pool
	root
	rope
	rope-ladder
	sand
	scallop
	section
	sink
	snow
	soda-straw
	spring
	stalactite
	stalagmite
	station
	station-name
	steps
	traverse
	vegetable-debris
	wall-calcite
	water
	water-flow
}

set xth(line_types) {
	arrow
	border
	ceiling-meander
	ceiling-step
	chimney
	contour
	floor-meander
	floor-step
	flowstone
	gradient
	label
	overhang
	pit
	rock-border
	rock-edge
	section
	slope
	survey
	wall
	water-flow
}

set xth(area_types) {
	blocks
	clay
	debris
	ice
	pebbles
	sand
	snow
	sump
	water
}

::msgcat::mcset cz "point air-draught" [encoding convertfrom utf-8 "pr\305\257van"]
::msgcat::mcset en "point air-draught" [encoding convertfrom utf-8 "air draught"]
::msgcat::mcset en_UK "point air-draught" [encoding convertfrom utf-8 "air draught"]
::msgcat::mcset en_US "point air-draught" [encoding convertfrom utf-8 "air draught"]
::msgcat::mcset es "point air-draught" [encoding convertfrom utf-8 "corriente aire"]
::msgcat::mcset fr "point air-draught" [encoding convertfrom utf-8 "courant d\342\200\231air"]
::msgcat::mcset sk "point air-draught" [encoding convertfrom utf-8 "prievan"]
::msgcat::mcset cz "point altitude" [encoding convertfrom utf-8 "nadmo\305\231sk\303\241 v\303\275\305\241ka bodu v chodb\304\233"]
::msgcat::mcset en "point altitude" [encoding convertfrom utf-8 "altitude"]
::msgcat::mcset en_UK "point altitude" [encoding convertfrom utf-8 "altitude"]
::msgcat::mcset en_US "point altitude" [encoding convertfrom utf-8 "altitude"]
::msgcat::mcset es "point altitude" [encoding convertfrom utf-8 "altura"]
::msgcat::mcset fr "point altitude" [encoding convertfrom utf-8 "altitude"]
::msgcat::mcset sk "point altitude" [encoding convertfrom utf-8 "nadmorsk\303\241 v\303\275\305\241ka bodu v chodbe"]
::msgcat::mcset cz "point anastomosis" [encoding convertfrom utf-8 "anastom\303\263za"]
::msgcat::mcset en "point anastomosis" [encoding convertfrom utf-8 "anastomosis"]
::msgcat::mcset en_UK "point anastomosis" [encoding convertfrom utf-8 "anastomosis"]
::msgcat::mcset en_US "point anastomosis" [encoding convertfrom utf-8 "anastomosis"]
::msgcat::mcset es "point anastomosis" [encoding convertfrom utf-8 "anastomosis"]
::msgcat::mcset fr "point anastomosis" [encoding convertfrom utf-8 "anastomose"]
::msgcat::mcset sk "point anastomosis" [encoding convertfrom utf-8 "anastom\303\263za"]
::msgcat::mcset cz "point anchor" [encoding convertfrom utf-8 "kotven\303\255"]
::msgcat::mcset en "point anchor" [encoding convertfrom utf-8 "anchor"]
::msgcat::mcset en_UK "point anchor" [encoding convertfrom utf-8 "anchor"]
::msgcat::mcset en_US "point anchor" [encoding convertfrom utf-8 "anchor"]
::msgcat::mcset es "point anchor" [encoding convertfrom utf-8 "anclaje"]
::msgcat::mcset fr "point anchor" [encoding convertfrom utf-8 "ancrage"]
::msgcat::mcset sk "point anchor" [encoding convertfrom utf-8 "kotvenie"]
::msgcat::mcset cz "point aragonite" [encoding convertfrom utf-8 "aragonit"]
::msgcat::mcset en "point aragonite" [encoding convertfrom utf-8 "aragonite"]
::msgcat::mcset en_UK "point aragonite" [encoding convertfrom utf-8 "aragonite"]
::msgcat::mcset en_US "point aragonite" [encoding convertfrom utf-8 "aragonite"]
::msgcat::mcset es "point aragonite" [encoding convertfrom utf-8 "aragonito"]
::msgcat::mcset fr "point aragonite" [encoding convertfrom utf-8 "aragonite"]
::msgcat::mcset sk "point aragonite" [encoding convertfrom utf-8 "aragonit"]
::msgcat::mcset cz "point archeo-material" [encoding convertfrom utf-8 "archeologick\303\251 n\303\241lezy"]
::msgcat::mcset en "point archeo-material" [encoding convertfrom utf-8 "archeo material"]
::msgcat::mcset en_UK "point archeo-material" [encoding convertfrom utf-8 "archeo material"]
::msgcat::mcset en_US "point archeo-material" [encoding convertfrom utf-8 "archeo material"]
::msgcat::mcset es "point archeo-material" [encoding convertfrom utf-8 "yacimiento (arq)"]
::msgcat::mcset fr "point archeo-material" [encoding convertfrom utf-8 "mat\303\251riel arch\303\251o"]
::msgcat::mcset sk "point archeo-material" [encoding convertfrom utf-8 "archeologick\303\251 n\303\241lezy"]
::msgcat::mcset cz "point bedrock" [encoding convertfrom utf-8 "pevn\303\241 sk\303\241la"]
::msgcat::mcset en "point bedrock" [encoding convertfrom utf-8 "bedrock"]
::msgcat::mcset en_UK "point bedrock" [encoding convertfrom utf-8 "bedrock"]
::msgcat::mcset en_US "point bedrock" [encoding convertfrom utf-8 "bedrock"]
::msgcat::mcset es "point bedrock" [encoding convertfrom utf-8 "roca madre"]
::msgcat::mcset fr "point bedrock" [encoding convertfrom utf-8 "roche"]
::msgcat::mcset sk "point bedrock" [encoding convertfrom utf-8 "pevn\303\241 skala"]
::msgcat::mcset cz "point blocks" [encoding convertfrom utf-8 "kamenn\303\251 bloky"]
::msgcat::mcset en "point blocks" [encoding convertfrom utf-8 "blocks, breakdown"]
::msgcat::mcset en_UK "point blocks" [encoding convertfrom utf-8 "blocks, breakdown"]
::msgcat::mcset en_US "point blocks" [encoding convertfrom utf-8 "blocks, breakdown"]
::msgcat::mcset es "point blocks" [encoding convertfrom utf-8 "bloques"]
::msgcat::mcset fr "point blocks" [encoding convertfrom utf-8 "blocs"]
::msgcat::mcset sk "point blocks" [encoding convertfrom utf-8 "kamenn\303\251 bloky"]
::msgcat::mcset cz "point breakdown-choke" [encoding convertfrom utf-8 "zavalen\303\275 konec"]
::msgcat::mcset en "point breakdown-choke" [encoding convertfrom utf-8 "breakdown choke"]
::msgcat::mcset en_UK "point breakdown-choke" [encoding convertfrom utf-8 "breakdown choke"]
::msgcat::mcset en_US "point breakdown-choke" [encoding convertfrom utf-8 "breakdown choke"]
::msgcat::mcset es "point breakdown-choke" [encoding convertfrom utf-8 "colmatado por derrumbe"]
::msgcat::mcset fr "point breakdown-choke" [encoding convertfrom utf-8 "tr\303\251mie"]
::msgcat::mcset sk "point breakdown-choke" [encoding convertfrom utf-8 "zavalen\303\275 koniec"]
::msgcat::mcset cz "point bridge" [encoding convertfrom utf-8 "most"]
::msgcat::mcset en "point bridge" [encoding convertfrom utf-8 "bridge"]
::msgcat::mcset en_UK "point bridge" [encoding convertfrom utf-8 "bridge"]
::msgcat::mcset en_US "point bridge" [encoding convertfrom utf-8 "bridge"]
::msgcat::mcset es "point bridge" [encoding convertfrom utf-8 "puente roca"]
::msgcat::mcset fr "point bridge" [encoding convertfrom utf-8 "pont"]
::msgcat::mcset sk "point bridge" [encoding convertfrom utf-8 "most"]
::msgcat::mcset cz "point camp" [encoding convertfrom utf-8 "bivak"]
::msgcat::mcset en "point camp" [encoding convertfrom utf-8 "camp"]
::msgcat::mcset en_UK "point camp" [encoding convertfrom utf-8 "camp"]
::msgcat::mcset en_US "point camp" [encoding convertfrom utf-8 "camp"]
::msgcat::mcset es "point camp" [encoding convertfrom utf-8 "campamento"]
::msgcat::mcset fr "point camp" [encoding convertfrom utf-8 "camp"]
::msgcat::mcset sk "point camp" [encoding convertfrom utf-8 "bivak"]
::msgcat::mcset cz "point cave-pearl" [encoding convertfrom utf-8 "jeskynn\303\255 perly"]
::msgcat::mcset en "point cave-pearl" [encoding convertfrom utf-8 "cave pearl"]
::msgcat::mcset en_UK "point cave-pearl" [encoding convertfrom utf-8 "cave pearl"]
::msgcat::mcset en_US "point cave-pearl" [encoding convertfrom utf-8 "cave pearl"]
::msgcat::mcset es "point cave-pearl" [encoding convertfrom utf-8 "perla de caverna"]
::msgcat::mcset fr "point cave-pearl" [encoding convertfrom utf-8 "perle des cavernes"]
::msgcat::mcset sk "point cave-pearl" [encoding convertfrom utf-8 "jaskynn\303\251 perly"]
::msgcat::mcset cz "point clay" [encoding convertfrom utf-8 "bahno"]
::msgcat::mcset en "point clay" [encoding convertfrom utf-8 "clay"]
::msgcat::mcset en_UK "point clay" [encoding convertfrom utf-8 "clay"]
::msgcat::mcset en_US "point clay" [encoding convertfrom utf-8 "clay"]
::msgcat::mcset es "point clay" [encoding convertfrom utf-8 "arcilla"]
::msgcat::mcset fr "point clay" [encoding convertfrom utf-8 "argile"]
::msgcat::mcset sk "point clay" [encoding convertfrom utf-8 "blato"]
::msgcat::mcset cz "point continuation" [encoding convertfrom utf-8 "mo\305\276n\303\251 pokra\304\215ov\303\241n\303\255"]
::msgcat::mcset en "point continuation" [encoding convertfrom utf-8 "possible continuation"]
::msgcat::mcset en_UK "point continuation" [encoding convertfrom utf-8 "possible continuation"]
::msgcat::mcset en_US "point continuation" [encoding convertfrom utf-8 "possible continuation"]
::msgcat::mcset es "point continuation" [encoding convertfrom utf-8 "continuaci\303\263n"]
::msgcat::mcset fr "point continuation" [encoding convertfrom utf-8 "suite possible"]
::msgcat::mcset sk "point continuation" [encoding convertfrom utf-8 "mo\305\276n\303\251 pokra\304\215ovanie"]
::msgcat::mcset cz "point crystal" [encoding convertfrom utf-8 "krystal"]
::msgcat::mcset en "point crystal" [encoding convertfrom utf-8 "crystal"]
::msgcat::mcset en_UK "point crystal" [encoding convertfrom utf-8 "crystal"]
::msgcat::mcset en_US "point crystal" [encoding convertfrom utf-8 "crystal"]
::msgcat::mcset es "point crystal" [encoding convertfrom utf-8 "cristal"]
::msgcat::mcset fr "point crystal" [encoding convertfrom utf-8 "cristaux"]
::msgcat::mcset sk "point crystal" [encoding convertfrom utf-8 "kry\305\241t\303\241l"]
::msgcat::mcset cz "point curtain" [encoding convertfrom utf-8 "sintrov\303\251 z\303\241clony"]
::msgcat::mcset en "point curtain" [encoding convertfrom utf-8 "curtain"]
::msgcat::mcset en_UK "point curtain" [encoding convertfrom utf-8 "curtain"]
::msgcat::mcset en_US "point curtain" [encoding convertfrom utf-8 "curtain"]
::msgcat::mcset es "point curtain" [encoding convertfrom utf-8 "cortina"]
::msgcat::mcset fr "point curtain" [encoding convertfrom utf-8 "rideau"]
::msgcat::mcset sk "point curtain" [encoding convertfrom utf-8 "sintrov\303\251 z\303\241clony"]
::msgcat::mcset cz "point date" [encoding convertfrom utf-8 "datum pozorov\303\241n\303\255"]
::msgcat::mcset en "point date" [encoding convertfrom utf-8 "date of observation"]
::msgcat::mcset en_UK "point date" [encoding convertfrom utf-8 "date of observation"]
::msgcat::mcset en_US "point date" [encoding convertfrom utf-8 "date of observation"]
::msgcat::mcset es "point date" [encoding convertfrom utf-8 "fecha"]
::msgcat::mcset fr "point date" [encoding convertfrom utf-8 "date"]
::msgcat::mcset sk "point date" [encoding convertfrom utf-8 "d\303\241tum pozorovania"]
::msgcat::mcset cz "point debris" [encoding convertfrom utf-8 "\305\241t\304\233rk"]
::msgcat::mcset en "point debris" [encoding convertfrom utf-8 "debris"]
::msgcat::mcset en_UK "point debris" [encoding convertfrom utf-8 "debris"]
::msgcat::mcset en_US "point debris" [encoding convertfrom utf-8 "debris"]
::msgcat::mcset es "point debris" [encoding convertfrom utf-8 "derrubios"]
::msgcat::mcset fr "point debris" [encoding convertfrom utf-8 "d\303\251bris"]
::msgcat::mcset sk "point debris" [encoding convertfrom utf-8 "\305\241trk"]
::msgcat::mcset sk "point dimensions" [encoding convertfrom utf-8 "rozmery"]
::msgcat::mcset cz "point disk" [encoding convertfrom utf-8 "disk"]
::msgcat::mcset en "point disk" [encoding convertfrom utf-8 "disk"]
::msgcat::mcset en_UK "point disk" [encoding convertfrom utf-8 "disk"]
::msgcat::mcset en_US "point disk" [encoding convertfrom utf-8 "disk"]
::msgcat::mcset es "point disk" [encoding convertfrom utf-8 "disco"]
::msgcat::mcset fr "point disk" [encoding convertfrom utf-8 "disque"]
::msgcat::mcset sk "point disk" [encoding convertfrom utf-8 "disk"]
::msgcat::mcset cz "point entrance" [encoding convertfrom utf-8 "vchod"]
::msgcat::mcset en "point entrance" [encoding convertfrom utf-8 "entrance"]
::msgcat::mcset en_UK "point entrance" [encoding convertfrom utf-8 "entrance"]
::msgcat::mcset en_US "point entrance" [encoding convertfrom utf-8 "entrance"]
::msgcat::mcset es "point entrance" [encoding convertfrom utf-8 "boca"]
::msgcat::mcset fr "point entrance" [encoding convertfrom utf-8 "entr\303\251e"]
::msgcat::mcset sk "point entrance" [encoding convertfrom utf-8 "vchod"]
::msgcat::mcset cz "point fixed-ladder" [encoding convertfrom utf-8 "pevn\303\275 \305\276eb\305\231\303\255k"]
::msgcat::mcset en "point fixed-ladder" [encoding convertfrom utf-8 "fixed ladder"]
::msgcat::mcset en_UK "point fixed-ladder" [encoding convertfrom utf-8 "fixed ladder"]
::msgcat::mcset en_US "point fixed-ladder" [encoding convertfrom utf-8 "fixed ladder"]
::msgcat::mcset es "point fixed-ladder" [encoding convertfrom utf-8 "escala fija"]
::msgcat::mcset fr "point fixed-ladder" [encoding convertfrom utf-8 "\303\251chelle fixe"]
::msgcat::mcset sk "point fixed-ladder" [encoding convertfrom utf-8 "fixn\303\275 rebr\303\255k"]
::msgcat::mcset cz "point flowstone" [encoding convertfrom utf-8 "sintr"]
::msgcat::mcset en "point flowstone" [encoding convertfrom utf-8 "flowstone"]
::msgcat::mcset en_UK "point flowstone" [encoding convertfrom utf-8 "flowstone"]
::msgcat::mcset en_US "point flowstone" [encoding convertfrom utf-8 "flowstone"]
::msgcat::mcset es "point flowstone" [encoding convertfrom utf-8 "concreci\303\263n"]
::msgcat::mcset fr "point flowstone" [encoding convertfrom utf-8 "concr\303\251tions"]
::msgcat::mcset sk "point flowstone" [encoding convertfrom utf-8 "sinter"]
::msgcat::mcset cz "point flowstone-choke" [encoding convertfrom utf-8 "zasintrovan\303\275 konec"]
::msgcat::mcset en "point flowstone-choke" [encoding convertfrom utf-8 "flowstone choke"]
::msgcat::mcset en_UK "point flowstone-choke" [encoding convertfrom utf-8 "flowstone choke"]
::msgcat::mcset en_US "point flowstone-choke" [encoding convertfrom utf-8 "flowstone choke"]
::msgcat::mcset es "point flowstone-choke" [encoding convertfrom utf-8 "colmatado por concreci\303\263n"]
::msgcat::mcset fr "point flowstone-choke" [encoding convertfrom utf-8 "tr\303\251mie calcifi\303\251e"]
::msgcat::mcset sk "point flowstone-choke" [encoding convertfrom utf-8 "zasintren\303\275 koniec"]
::msgcat::mcset cz "point flute" [encoding convertfrom utf-8 "p\303\255\305\241\305\245aly"]
::msgcat::mcset en "point flute" [encoding convertfrom utf-8 "flute"]
::msgcat::mcset en_UK "point flute" [encoding convertfrom utf-8 "flute"]
::msgcat::mcset en_US "point flute" [encoding convertfrom utf-8 "flute"]
::msgcat::mcset es "point flute" [encoding convertfrom utf-8 "canaleta"]
::msgcat::mcset fr "point flute" [encoding convertfrom utf-8 "flute (?)"]
::msgcat::mcset sk "point flute" [encoding convertfrom utf-8 "p\303\255\305\241\305\245aly"]
::msgcat::mcset cz "point gradient" [encoding convertfrom utf-8 "sklon chodby"]
::msgcat::mcset en "point gradient" [encoding convertfrom utf-8 "passage gradient"]
::msgcat::mcset en_UK "point gradient" [encoding convertfrom utf-8 "passage gradient"]
::msgcat::mcset en_US "point gradient" [encoding convertfrom utf-8 "passage gradient"]
::msgcat::mcset es "point gradient" [encoding convertfrom utf-8 "gradiente"]
::msgcat::mcset fr "point gradient" [encoding convertfrom utf-8 "pente"]
::msgcat::mcset sk "point gradient" [encoding convertfrom utf-8 "sklon chodby"]
::msgcat::mcset cz "point guano" [encoding convertfrom utf-8 "guano"]
::msgcat::mcset en "point guano" [encoding convertfrom utf-8 "guano"]
::msgcat::mcset en_UK "point guano" [encoding convertfrom utf-8 "guano"]
::msgcat::mcset en_US "point guano" [encoding convertfrom utf-8 "guano"]
::msgcat::mcset es "point guano" [encoding convertfrom utf-8 "guano"]
::msgcat::mcset fr "point guano" [encoding convertfrom utf-8 "guano"]
::msgcat::mcset sk "point guano" [encoding convertfrom utf-8 "gu\303\241no"]
::msgcat::mcset cz "point gypsum" [encoding convertfrom utf-8 "s\303\241drovec"]
::msgcat::mcset en "point gypsum" [encoding convertfrom utf-8 "gypsum"]
::msgcat::mcset en_UK "point gypsum" [encoding convertfrom utf-8 "gypsum"]
::msgcat::mcset en_US "point gypsum" [encoding convertfrom utf-8 "gypsum"]
::msgcat::mcset es "point gypsum" [encoding convertfrom utf-8 "yeso"]
::msgcat::mcset fr "point gypsum" [encoding convertfrom utf-8 "gypse"]
::msgcat::mcset sk "point gypsum" [encoding convertfrom utf-8 "s\303\241drovec"]
::msgcat::mcset cz "point gypsum-flower" [encoding convertfrom utf-8 "s\303\241drovcov\303\275 kv\304\233t"]
::msgcat::mcset en "point gypsum-flower" [encoding convertfrom utf-8 "gypsum flower"]
::msgcat::mcset en_UK "point gypsum-flower" [encoding convertfrom utf-8 "gypsum flower"]
::msgcat::mcset en_US "point gypsum-flower" [encoding convertfrom utf-8 "gypsum flower"]
::msgcat::mcset es "point gypsum-flower" [encoding convertfrom utf-8 "flor yeso"]
::msgcat::mcset fr "point gypsum-flower" [encoding convertfrom utf-8 "fleur de gypse"]
::msgcat::mcset sk "point gypsum-flower" [encoding convertfrom utf-8 "s\303\241drovcov\303\275 kvet"]
::msgcat::mcset cz "point height" [encoding convertfrom utf-8 "v\303\275\305\241ka stupn\304\233/kom\303\255nu/hloubka propasti"]
::msgcat::mcset en "point height" [encoding convertfrom utf-8 "the height of floor step/chimney/pit depth"]
::msgcat::mcset en_UK "point height" [encoding convertfrom utf-8 "the height of floor step/chimney/pit depth"]
::msgcat::mcset en_US "point height" [encoding convertfrom utf-8 "the height of floor step/chimney/pit depth"]
::msgcat::mcset es "point height" [encoding convertfrom utf-8 "altura resalte/chimenea/profundidad pozo"]
::msgcat::mcset fr "point height" [encoding convertfrom utf-8 "hauteur d\342\200\231une marche/d\342\200\231une chemin\303\251e/profondeur"]
::msgcat::mcset sk "point height" [encoding convertfrom utf-8 "v\303\275\305\241ka stup\305\210a/kom\303\255nu/h\304\272bka priepasti"]
::msgcat::mcset cz "point helictite" [encoding convertfrom utf-8 "heliktit"]
::msgcat::mcset en "point helictite" [encoding convertfrom utf-8 "helictite"]
::msgcat::mcset en_UK "point helictite" [encoding convertfrom utf-8 "helictite"]
::msgcat::mcset en_US "point helictite" [encoding convertfrom utf-8 "helictite"]
::msgcat::mcset es "point helictite" [encoding convertfrom utf-8 "exc\303\251ntrica"]
::msgcat::mcset fr "point helictite" [encoding convertfrom utf-8 "excentrique/h\303\251lictite"]
::msgcat::mcset sk "point helictite" [encoding convertfrom utf-8 "helektit"]
::msgcat::mcset cz "point ice" [encoding convertfrom utf-8 "led"]
::msgcat::mcset en "point ice" [encoding convertfrom utf-8 "ice"]
::msgcat::mcset en_UK "point ice" [encoding convertfrom utf-8 "ice"]
::msgcat::mcset en_US "point ice" [encoding convertfrom utf-8 "ice"]
::msgcat::mcset es "point ice" [encoding convertfrom utf-8 "hielo"]
::msgcat::mcset fr "point ice" [encoding convertfrom utf-8 "glace"]
::msgcat::mcset sk "point ice" [encoding convertfrom utf-8 "\304\276ad"]
::msgcat::mcset cz "point karren" [encoding convertfrom utf-8 "\305\241krapy"]
::msgcat::mcset en "point karren" [encoding convertfrom utf-8 "karren"]
::msgcat::mcset en_UK "point karren" [encoding convertfrom utf-8 "karren"]
::msgcat::mcset en_US "point karren" [encoding convertfrom utf-8 "karren"]
::msgcat::mcset es "point karren" [encoding convertfrom utf-8 "lapiaz"]
::msgcat::mcset fr "point karren" [encoding convertfrom utf-8 "lapiez"]
::msgcat::mcset sk "point karren" [encoding convertfrom utf-8 "\305\241krapy"]
::msgcat::mcset cz "point label" [encoding convertfrom utf-8 "pojmenov\303\241n\303\255"]
::msgcat::mcset sk "point label" [encoding convertfrom utf-8 "pomenovanie"]
::msgcat::mcset cz "point low-end" [encoding convertfrom utf-8 "nepr\305\257lezn\303\251 sn\303\255\305\276en\303\255"]
::msgcat::mcset en "point low-end" [encoding convertfrom utf-8 "passage low end"]
::msgcat::mcset en_UK "point low-end" [encoding convertfrom utf-8 "passage low end"]
::msgcat::mcset en_US "point low-end" [encoding convertfrom utf-8 "passage low end"]
::msgcat::mcset es "point low-end" [encoding convertfrom utf-8 "final bajo"]
::msgcat::mcset fr "point low-end" [encoding convertfrom utf-8 "passage bas"]
::msgcat::mcset sk "point low-end" [encoding convertfrom utf-8 "neprielezn\303\251 zn\303\255\305\276enie"]
::msgcat::mcset cz "point moonmilk" [encoding convertfrom utf-8 "nickam\303\255nek"]
::msgcat::mcset en "point moonmilk" [encoding convertfrom utf-8 "moonmilk"]
::msgcat::mcset en_UK "point moonmilk" [encoding convertfrom utf-8 "moonmilk"]
::msgcat::mcset en_US "point moonmilk" [encoding convertfrom utf-8 "moonmilk"]
::msgcat::mcset es "point moonmilk" [encoding convertfrom utf-8 "mondmilch"]
::msgcat::mcset fr "point moonmilk" [encoding convertfrom utf-8 "mondmilch"]
::msgcat::mcset sk "point moonmilk" [encoding convertfrom utf-8 "m\303\244kk\303\275 sinter"]
::msgcat::mcset cz "point narrow-end" [encoding convertfrom utf-8 "nepr\305\257lezn\303\251 z\303\272\305\276en\303\255"]
::msgcat::mcset en "point narrow-end" [encoding convertfrom utf-8 "passage narrow end"]
::msgcat::mcset en_UK "point narrow-end" [encoding convertfrom utf-8 "passage narrow end"]
::msgcat::mcset en_US "point narrow-end" [encoding convertfrom utf-8 "passage narrow end"]
::msgcat::mcset es "point narrow-end" [encoding convertfrom utf-8 "final estrecho"]
::msgcat::mcset fr "point narrow-end" [encoding convertfrom utf-8 "passage imp\303\251n\303\251trable"]
::msgcat::mcset sk "point narrow-end" [encoding convertfrom utf-8 "neprielezn\303\251 z\303\272\305\276enie"]
::msgcat::mcset cz "point no-equipment" [encoding convertfrom utf-8 "nevystrojen\303\251 m\303\255sto"]
::msgcat::mcset en "point no-equipment" [encoding convertfrom utf-8 "place without equipement"]
::msgcat::mcset en_UK "point no-equipment" [encoding convertfrom utf-8 "place without equipement"]
::msgcat::mcset en_US "point no-equipment" [encoding convertfrom utf-8 "place without equipement"]
::msgcat::mcset es "point no-equipment" [encoding convertfrom utf-8 "sin equipar"]
::msgcat::mcset fr "point no-equipment" [encoding convertfrom utf-8 "pas d\342\200\231\303\251quipement"]
::msgcat::mcset sk "point no-equipment" [encoding convertfrom utf-8 "nevystrojen\303\251 miesto"]
::msgcat::mcset cz "point paleo-material" [encoding convertfrom utf-8 "paleontologick\303\251 n\303\241lezy"]
::msgcat::mcset en "point paleo-material" [encoding convertfrom utf-8 "paleo material"]
::msgcat::mcset en_UK "point paleo-material" [encoding convertfrom utf-8 "paleo material"]
::msgcat::mcset en_US "point paleo-material" [encoding convertfrom utf-8 "paleo material"]
::msgcat::mcset es "point paleo-material" [encoding convertfrom utf-8 "yacimiento (pal)"]
::msgcat::mcset fr "point paleo-material" [encoding convertfrom utf-8 "mat\303\251riel pal\303\251o"]
::msgcat::mcset sk "point paleo-material" [encoding convertfrom utf-8 "paleontologick\303\251 n\303\241lezy"]
::msgcat::mcset cz "point passage-height" [encoding convertfrom utf-8 "v\303\275\305\241ka chodby"]
::msgcat::mcset en "point passage-height" [encoding convertfrom utf-8 "passage height"]
::msgcat::mcset en_UK "point passage-height" [encoding convertfrom utf-8 "passage height"]
::msgcat::mcset en_US "point passage-height" [encoding convertfrom utf-8 "passage height"]
::msgcat::mcset es "point passage-height" [encoding convertfrom utf-8 "altura"]
::msgcat::mcset fr "point passage-height" [encoding convertfrom utf-8 "hauteur du passage"]
::msgcat::mcset sk "point passage-height" [encoding convertfrom utf-8 "v\303\275\305\241ka chodby"]
::msgcat::mcset cz "point pebbles" [encoding convertfrom utf-8 "valouny"]
::msgcat::mcset en "point pebbles" [encoding convertfrom utf-8 "pebbles"]
::msgcat::mcset en_UK "point pebbles" [encoding convertfrom utf-8 "pebbles"]
::msgcat::mcset en_US "point pebbles" [encoding convertfrom utf-8 "pebbles"]
::msgcat::mcset es "point pebbles" [encoding convertfrom utf-8 "cantos rodados"]
::msgcat::mcset fr "point pebbles" [encoding convertfrom utf-8 "galets"]
::msgcat::mcset sk "point pebbles" [encoding convertfrom utf-8 "okruhliaky"]
::msgcat::mcset cz "point pillar" [encoding convertfrom utf-8 "stalagn\303\241t"]
::msgcat::mcset en "point pillar" [encoding convertfrom utf-8 "pillar"]
::msgcat::mcset en_UK "point pillar" [encoding convertfrom utf-8 "pillar"]
::msgcat::mcset en_US "point pillar" [encoding convertfrom utf-8 "pillar"]
::msgcat::mcset es "point pillar" [encoding convertfrom utf-8 "pilar"]
::msgcat::mcset fr "point pillar" [encoding convertfrom utf-8 "pillier"]
::msgcat::mcset sk "point pillar" [encoding convertfrom utf-8 "stalagn\303\241t"]
::msgcat::mcset cz "point popcorn" [encoding convertfrom utf-8 "pizolity"]
::msgcat::mcset en "point popcorn" [encoding convertfrom utf-8 "popcorn"]
::msgcat::mcset en_UK "point popcorn" [encoding convertfrom utf-8 "popcorn"]
::msgcat::mcset en_US "point popcorn" [encoding convertfrom utf-8 "popcorn"]
::msgcat::mcset es "point popcorn" [encoding convertfrom utf-8 "coliflor"]
::msgcat::mcset fr "point popcorn" [encoding convertfrom utf-8 "choux-fleur"]
::msgcat::mcset sk "point popcorn" [encoding convertfrom utf-8 "pizolity"]
::msgcat::mcset cz "point raft" [encoding convertfrom utf-8 "n\303\241plav"]
::msgcat::mcset en "point raft" [encoding convertfrom utf-8 "raft"]
::msgcat::mcset en_UK "point raft" [encoding convertfrom utf-8 "raft"]
::msgcat::mcset en_US "point raft" [encoding convertfrom utf-8 "raft"]
::msgcat::mcset es "point raft" [encoding convertfrom utf-8 "calcita flotante"]
::msgcat::mcset fr "point raft" [encoding convertfrom utf-8 "calcite flottante"]
::msgcat::mcset sk "point raft" [encoding convertfrom utf-8 "n\303\241plav"]
::msgcat::mcset cz "point raft-cone" [encoding convertfrom utf-8 "n\303\241plavov\303\275 ku\305\276el"]
::msgcat::mcset en "point raft-cone" [encoding convertfrom utf-8 "raft cone"]
::msgcat::mcset en_UK "point raft-cone" [encoding convertfrom utf-8 "raft cone"]
::msgcat::mcset en_US "point raft-cone" [encoding convertfrom utf-8 "raft cone"]
::msgcat::mcset es "point raft-cone" [encoding convertfrom utf-8 "conos"]
::msgcat::mcset fr "point raft-cone" [encoding convertfrom utf-8 "cone"]
::msgcat::mcset sk "point raft-cone" [encoding convertfrom utf-8 "n\303\241plavov\303\275 ku\305\276e\304\276"]
::msgcat::mcset cz "point remark" [encoding convertfrom utf-8 "pozn\303\241mka"]
::msgcat::mcset sk "point remark" [encoding convertfrom utf-8 "pozn\303\241mka"]
::msgcat::mcset cz "point rimstone-dam" [encoding convertfrom utf-8 "sintrov\303\241 hr\303\241zka"]
::msgcat::mcset en "point rimstone-dam" [encoding convertfrom utf-8 "rimstone dam"]
::msgcat::mcset en_UK "point rimstone-dam" [encoding convertfrom utf-8 "rimstone dam"]
::msgcat::mcset en_US "point rimstone-dam" [encoding convertfrom utf-8 "rimstone dam"]
::msgcat::mcset es "point rimstone-dam" [encoding convertfrom utf-8 "gour-presa"]
::msgcat::mcset fr "point rimstone-dam" [encoding convertfrom utf-8 "gours"]
::msgcat::mcset sk "point rimstone-dam" [encoding convertfrom utf-8 "sintrov\303\241 hr\303\241dza"]
::msgcat::mcset cz "point rimstone-pool" [encoding convertfrom utf-8 "sintrov\303\251 jez\303\255rko"]
::msgcat::mcset en "point rimstone-pool" [encoding convertfrom utf-8 "rimstone pool"]
::msgcat::mcset en_UK "point rimstone-pool" [encoding convertfrom utf-8 "rimstone pool"]
::msgcat::mcset en_US "point rimstone-pool" [encoding convertfrom utf-8 "rimstone pool"]
::msgcat::mcset es "point rimstone-pool" [encoding convertfrom utf-8 "gour-poza"]
::msgcat::mcset fr "point rimstone-pool" [encoding convertfrom utf-8 "gour"]
::msgcat::mcset sk "point rimstone-pool" [encoding convertfrom utf-8 "sintrov\303\251 jazierko"]
::msgcat::mcset cz "point root" [encoding convertfrom utf-8 "ko\305\231eny"]
::msgcat::mcset en "point root" [encoding convertfrom utf-8 "root"]
::msgcat::mcset en_UK "point root" [encoding convertfrom utf-8 "root"]
::msgcat::mcset en_US "point root" [encoding convertfrom utf-8 "root"]
::msgcat::mcset es "point root" [encoding convertfrom utf-8 "ra\303\255z"]
::msgcat::mcset fr "point root" [encoding convertfrom utf-8 "racine"]
::msgcat::mcset sk "point root" [encoding convertfrom utf-8 "korene"]
::msgcat::mcset cz "point rope" [encoding convertfrom utf-8 "lano"]
::msgcat::mcset en "point rope" [encoding convertfrom utf-8 "rope"]
::msgcat::mcset en_UK "point rope" [encoding convertfrom utf-8 "rope"]
::msgcat::mcset en_US "point rope" [encoding convertfrom utf-8 "rope"]
::msgcat::mcset es "point rope" [encoding convertfrom utf-8 "cuerda"]
::msgcat::mcset fr "point rope" [encoding convertfrom utf-8 "corde"]
::msgcat::mcset sk "point rope" [encoding convertfrom utf-8 "lano"]
::msgcat::mcset cz "point rope-ladder" [encoding convertfrom utf-8 "lanov\303\275 \305\276eb\305\231\303\255k"]
::msgcat::mcset en "point rope-ladder" [encoding convertfrom utf-8 "rope ladder"]
::msgcat::mcset en_UK "point rope-ladder" [encoding convertfrom utf-8 "rope ladder"]
::msgcat::mcset en_US "point rope-ladder" [encoding convertfrom utf-8 "rope ladder"]
::msgcat::mcset es "point rope-ladder" [encoding convertfrom utf-8 "escala"]
::msgcat::mcset fr "point rope-ladder" [encoding convertfrom utf-8 "\303\251chelle de corde"]
::msgcat::mcset sk "point rope-ladder" [encoding convertfrom utf-8 "lanov\303\275 rebr\303\255k"]
::msgcat::mcset cz "point sand" [encoding convertfrom utf-8 "p\303\255sek"]
::msgcat::mcset en "point sand" [encoding convertfrom utf-8 "sand"]
::msgcat::mcset en_UK "point sand" [encoding convertfrom utf-8 "sand"]
::msgcat::mcset en_US "point sand" [encoding convertfrom utf-8 "sand"]
::msgcat::mcset es "point sand" [encoding convertfrom utf-8 "arena"]
::msgcat::mcset fr "point sand" [encoding convertfrom utf-8 "sable"]
::msgcat::mcset sk "point sand" [encoding convertfrom utf-8 "piesok"]
::msgcat::mcset cz "point scallop" [encoding convertfrom utf-8 "erozn\303\255 \303\272tvary"]
::msgcat::mcset en "point scallop" [encoding convertfrom utf-8 "scallop"]
::msgcat::mcset en_UK "point scallop" [encoding convertfrom utf-8 "scallop"]
::msgcat::mcset en_US "point scallop" [encoding convertfrom utf-8 "scallop"]
::msgcat::mcset es "point scallop" [encoding convertfrom utf-8 "cavitaciones"]
::msgcat::mcset fr "point scallop" [encoding convertfrom utf-8 "vagues d\342\200\231\303\251rosion (coups de gouge)"]
::msgcat::mcset sk "point scallop" [encoding convertfrom utf-8 "er\303\263zne \303\272tvary"]
::msgcat::mcset cz "point section" [encoding convertfrom utf-8 "p\305\231\303\255\304\215n\303\275 \305\231ez"]
::msgcat::mcset sk "point section" [encoding convertfrom utf-8 "prie\304\215ny rez"]
::msgcat::mcset cz "point sink" [encoding convertfrom utf-8 "ponor"]
::msgcat::mcset en "point sink" [encoding convertfrom utf-8 "sink"]
::msgcat::mcset en_UK "point sink" [encoding convertfrom utf-8 "sink"]
::msgcat::mcset en_US "point sink" [encoding convertfrom utf-8 "sink"]
::msgcat::mcset es "point sink" [encoding convertfrom utf-8 "sumidero"]
::msgcat::mcset fr "point sink" [encoding convertfrom utf-8 "perte"]
::msgcat::mcset sk "point sink" [encoding convertfrom utf-8 "ponor"]
::msgcat::mcset cz "point snow" [encoding convertfrom utf-8 "sn\303\255h"]
::msgcat::mcset en "point snow" [encoding convertfrom utf-8 "snow"]
::msgcat::mcset en_UK "point snow" [encoding convertfrom utf-8 "snow"]
::msgcat::mcset en_US "point snow" [encoding convertfrom utf-8 "snow"]
::msgcat::mcset es "point snow" [encoding convertfrom utf-8 "nieve"]
::msgcat::mcset sk "point snow" [encoding convertfrom utf-8 "sneh"]
::msgcat::mcset cz "point soda-straw" [encoding convertfrom utf-8 "br\304\215ka"]
::msgcat::mcset en "point soda-straw" [encoding convertfrom utf-8 "soda straw"]
::msgcat::mcset en_UK "point soda-straw" [encoding convertfrom utf-8 "soda straw"]
::msgcat::mcset en_US "point soda-straw" [encoding convertfrom utf-8 "soda straw"]
::msgcat::mcset es "point soda-straw" [encoding convertfrom utf-8 "fistulosa"]
::msgcat::mcset fr "point soda-straw" [encoding convertfrom utf-8 "fistuleuse"]
::msgcat::mcset sk "point soda-straw" [encoding convertfrom utf-8 "br\304\215k\303\241"]
::msgcat::mcset cz "point spring" [encoding convertfrom utf-8 "v\303\275v\304\233r"]
::msgcat::mcset en "point spring" [encoding convertfrom utf-8 "spring"]
::msgcat::mcset en_UK "point spring" [encoding convertfrom utf-8 "spring"]
::msgcat::mcset en_US "point spring" [encoding convertfrom utf-8 "spring"]
::msgcat::mcset es "point spring" [encoding convertfrom utf-8 "surgencia"]
::msgcat::mcset fr "point spring" [encoding convertfrom utf-8 "source"]
::msgcat::mcset sk "point spring" [encoding convertfrom utf-8 "v\303\275ver"]
::msgcat::mcset cz "point stalactite" [encoding convertfrom utf-8 "stalaktit"]
::msgcat::mcset en "point stalactite" [encoding convertfrom utf-8 "stalactite"]
::msgcat::mcset en_UK "point stalactite" [encoding convertfrom utf-8 "stalactite"]
::msgcat::mcset en_US "point stalactite" [encoding convertfrom utf-8 "stalactite"]
::msgcat::mcset es "point stalactite" [encoding convertfrom utf-8 "estalactita"]
::msgcat::mcset fr "point stalactite" [encoding convertfrom utf-8 "stalactite"]
::msgcat::mcset sk "point stalactite" [encoding convertfrom utf-8 "stalaktit"]
::msgcat::mcset cz "point stalagmite" [encoding convertfrom utf-8 "stalagmit"]
::msgcat::mcset en "point stalagmite" [encoding convertfrom utf-8 "stalagmite"]
::msgcat::mcset en_UK "point stalagmite" [encoding convertfrom utf-8 "stalagmite"]
::msgcat::mcset en_US "point stalagmite" [encoding convertfrom utf-8 "stalagmite"]
::msgcat::mcset es "point stalagmite" [encoding convertfrom utf-8 "estalagmita"]
::msgcat::mcset fr "point stalagmite" [encoding convertfrom utf-8 "stalagmite"]
::msgcat::mcset sk "point stalagmite" [encoding convertfrom utf-8 "stalagmit"]
::msgcat::mcset cz "point station" [encoding convertfrom utf-8 "m\304\233\305\231i\304\215sk\303\275 bod"]
::msgcat::mcset en "point station" [encoding convertfrom utf-8 "survey station"]
::msgcat::mcset en_UK "point station" [encoding convertfrom utf-8 "survey station"]
::msgcat::mcset en_US "point station" [encoding convertfrom utf-8 "survey station"]
::msgcat::mcset es "point station" [encoding convertfrom utf-8 "estaci\303\263n"]
::msgcat::mcset fr "point station" [encoding convertfrom utf-8 "station topo"]
::msgcat::mcset sk "point station" [encoding convertfrom utf-8 "mera\304\215sk\303\275 bod"]
::msgcat::mcset cz "point station-name" [encoding convertfrom utf-8 "\304\215\303\255slo m\304\233\305\231i\304\215sk\303\251ho bodu"]
::msgcat::mcset en "point station-name" [encoding convertfrom utf-8 "survey station name"]
::msgcat::mcset en_UK "point station-name" [encoding convertfrom utf-8 "survey station name"]
::msgcat::mcset en_US "point station-name" [encoding convertfrom utf-8 "survey station name"]
::msgcat::mcset es "point station-name" [encoding convertfrom utf-8 "nombre estacion"]
::msgcat::mcset fr "point station-name" [encoding convertfrom utf-8 "station topo, nom"]
::msgcat::mcset sk "point station-name" [encoding convertfrom utf-8 "\304\215\303\255slo mera\304\215sk\303\251ho bodu"]
::msgcat::mcset cz "point steps" [encoding convertfrom utf-8 "schody"]
::msgcat::mcset en "point steps" [encoding convertfrom utf-8 "steps"]
::msgcat::mcset en_UK "point steps" [encoding convertfrom utf-8 "steps"]
::msgcat::mcset en_US "point steps" [encoding convertfrom utf-8 "steps"]
::msgcat::mcset es "point steps" [encoding convertfrom utf-8 "escalones"]
::msgcat::mcset fr "point steps" [encoding convertfrom utf-8 "marches"]
::msgcat::mcset sk "point steps" [encoding convertfrom utf-8 "schody"]
::msgcat::mcset cz "point traverse" [encoding convertfrom utf-8 "traverz"]
::msgcat::mcset en "point traverse" [encoding convertfrom utf-8 "traverse"]
::msgcat::mcset en_UK "point traverse" [encoding convertfrom utf-8 "traverse"]
::msgcat::mcset en_US "point traverse" [encoding convertfrom utf-8 "traverse"]
::msgcat::mcset es "point traverse" [encoding convertfrom utf-8 "pasamanos"]
::msgcat::mcset fr "point traverse" [encoding convertfrom utf-8 "travers\303\251e"]
::msgcat::mcset sk "point traverse" [encoding convertfrom utf-8 "traverz"]
::msgcat::mcset cz "point vegetable-debris" [encoding convertfrom utf-8 "zbytky rostlin"]
::msgcat::mcset en "point vegetable-debris" [encoding convertfrom utf-8 "vegetable debris"]
::msgcat::mcset en_UK "point vegetable-debris" [encoding convertfrom utf-8 "vegetable debris"]
::msgcat::mcset en_US "point vegetable-debris" [encoding convertfrom utf-8 "vegetable debris"]
::msgcat::mcset es "point vegetable-debris" [encoding convertfrom utf-8 "detritus vegetales"]
::msgcat::mcset fr "point vegetable-debris" [encoding convertfrom utf-8 "d\303\251bris v\303\251g\303\251taux"]
::msgcat::mcset sk "point vegetable-debris" [encoding convertfrom utf-8 "zvy\305\241ky rastl\303\255n"]
::msgcat::mcset cz "point wall-calcite" [encoding convertfrom utf-8 "v\303\241pencov\303\275 povlak"]
::msgcat::mcset en "point wall-calcite" [encoding convertfrom utf-8 "wall calcite"]
::msgcat::mcset en_UK "point wall-calcite" [encoding convertfrom utf-8 "wall calcite"]
::msgcat::mcset en_US "point wall-calcite" [encoding convertfrom utf-8 "wall calcite"]
::msgcat::mcset es "point wall-calcite" [encoding convertfrom utf-8 "calcita"]
::msgcat::mcset fr "point wall-calcite" [encoding convertfrom utf-8 "mur, calcite"]
::msgcat::mcset sk "point wall-calcite" [encoding convertfrom utf-8 "v\303\241pencov\303\275 povlak"]
::msgcat::mcset cz "point water" [encoding convertfrom utf-8 "voda"]
::msgcat::mcset en "point water" [encoding convertfrom utf-8 "water"]
::msgcat::mcset en_UK "point water" [encoding convertfrom utf-8 "water"]
::msgcat::mcset en_US "point water" [encoding convertfrom utf-8 "water"]
::msgcat::mcset es "point water" [encoding convertfrom utf-8 "agua"]
::msgcat::mcset fr "point water" [encoding convertfrom utf-8 "eau"]
::msgcat::mcset sk "point water" [encoding convertfrom utf-8 "voda"]
::msgcat::mcset cz "point water-flow" [encoding convertfrom utf-8 "vodn\303\255 tok"]
::msgcat::mcset en "point water-flow" [encoding convertfrom utf-8 "water flow"]
::msgcat::mcset en_UK "point water-flow" [encoding convertfrom utf-8 "water flow"]
::msgcat::mcset en_US "point water-flow" [encoding convertfrom utf-8 "water flow"]
::msgcat::mcset es "point water-flow" [encoding convertfrom utf-8 "curso agua"]
::msgcat::mcset fr "point water-flow" [encoding convertfrom utf-8 "rivi\303\250re"]
::msgcat::mcset sk "point water-flow" [encoding convertfrom utf-8 "vodn\303\275 tok"]
::msgcat::mcset cz "line arrow" [encoding convertfrom utf-8 "pomocn\303\241 \305\241ipka"]
::msgcat::mcset en "line arrow" [encoding convertfrom utf-8 "arrow"]
::msgcat::mcset en_UK "line arrow" [encoding convertfrom utf-8 "arrow"]
::msgcat::mcset en_US "line arrow" [encoding convertfrom utf-8 "arrow"]
::msgcat::mcset es "line arrow" [encoding convertfrom utf-8 "flecha"]
::msgcat::mcset fr "line arrow" [encoding convertfrom utf-8 "fl\303\250che"]
::msgcat::mcset sk "line arrow" [encoding convertfrom utf-8 "pomocn\303\241 \305\241\303\255pka"]
::msgcat::mcset cz "line border" [encoding convertfrom utf-8 "ohrani\304\215en\303\255"]
::msgcat::mcset en "line border" [encoding convertfrom utf-8 "border"]
::msgcat::mcset en_UK "line border" [encoding convertfrom utf-8 "border"]
::msgcat::mcset en_US "line border" [encoding convertfrom utf-8 "border"]
::msgcat::mcset es "line border" [encoding convertfrom utf-8 "l\303\255mite"]
::msgcat::mcset fr "line border" [encoding convertfrom utf-8 "bord"]
::msgcat::mcset sk "line border" [encoding convertfrom utf-8 "ohrani\304\215enie"]
::msgcat::mcset cz "line ceiling-meander" [encoding convertfrom utf-8 "stropn\303\255 meandr"]
::msgcat::mcset en "line ceiling-meander" [encoding convertfrom utf-8 "ceiling meander"]
::msgcat::mcset en_UK "line ceiling-meander" [encoding convertfrom utf-8 "ceiling meander"]
::msgcat::mcset en_US "line ceiling-meander" [encoding convertfrom utf-8 "ceiling meander"]
::msgcat::mcset es "line ceiling-meander" [encoding convertfrom utf-8 "meandro inverso"]
::msgcat::mcset sk "line ceiling-meander" [encoding convertfrom utf-8 "stropn\303\275 meander"]
::msgcat::mcset cz "line ceiling-step" [encoding convertfrom utf-8 "zm\304\233na v\303\275\305\241ky stropu"]
::msgcat::mcset en "line ceiling-step" [encoding convertfrom utf-8 "step on the ceiling"]
::msgcat::mcset en_UK "line ceiling-step" [encoding convertfrom utf-8 "step on the ceiling"]
::msgcat::mcset en_US "line ceiling-step" [encoding convertfrom utf-8 "step on the ceiling"]
::msgcat::mcset es "line ceiling-step" [encoding convertfrom utf-8 "resalte inverso"]
::msgcat::mcset fr "line ceiling-step" [encoding convertfrom utf-8 "marche de plafond"]
::msgcat::mcset sk "line ceiling-step" [encoding convertfrom utf-8 "zmena v\303\275\305\241ky stropu"]
::msgcat::mcset cz "line chimney" [encoding convertfrom utf-8 "kom\303\255n"]
::msgcat::mcset en "line chimney" [encoding convertfrom utf-8 "chimney"]
::msgcat::mcset en_UK "line chimney" [encoding convertfrom utf-8 "chimney"]
::msgcat::mcset en_US "line chimney" [encoding convertfrom utf-8 "chimney"]
::msgcat::mcset es "line chimney" [encoding convertfrom utf-8 "chimenea"]
::msgcat::mcset fr "line chimney" [encoding convertfrom utf-8 "chemin\303\251e"]
::msgcat::mcset sk "line chimney" [encoding convertfrom utf-8 "kom\303\255n"]
::msgcat::mcset cz "line contour" [encoding convertfrom utf-8 "vrstevnice"]
::msgcat::mcset en "line contour" [encoding convertfrom utf-8 "contour"]
::msgcat::mcset en_UK "line contour" [encoding convertfrom utf-8 "contour"]
::msgcat::mcset en_US "line contour" [encoding convertfrom utf-8 "contour"]
::msgcat::mcset es "line contour" [encoding convertfrom utf-8 "contorno"]
::msgcat::mcset fr "line contour" [encoding convertfrom utf-8 "contour"]
::msgcat::mcset sk "line contour" [encoding convertfrom utf-8 "vrstevnica"]
::msgcat::mcset cz "line floor-meander" [encoding convertfrom utf-8 "meandr ve dn\304\233"]
::msgcat::mcset en "line floor-meander" [encoding convertfrom utf-8 "floor meander"]
::msgcat::mcset en_UK "line floor-meander" [encoding convertfrom utf-8 "floor meander"]
::msgcat::mcset en_US "line floor-meander" [encoding convertfrom utf-8 "floor meander"]
::msgcat::mcset es "line floor-meander" [encoding convertfrom utf-8 "meandro"]
::msgcat::mcset sk "line floor-meander" [encoding convertfrom utf-8 "meander v dne"]
::msgcat::mcset cz "line floor-step" [encoding convertfrom utf-8 "stupe\305\210"]
::msgcat::mcset en "line floor-step" [encoding convertfrom utf-8 "floor step"]
::msgcat::mcset en_UK "line floor-step" [encoding convertfrom utf-8 "floor step"]
::msgcat::mcset en_US "line floor-step" [encoding convertfrom utf-8 "floor step"]
::msgcat::mcset es "line floor-step" [encoding convertfrom utf-8 "resalte"]
::msgcat::mcset fr "line floor-step" [encoding convertfrom utf-8 "marche"]
::msgcat::mcset sk "line floor-step" [encoding convertfrom utf-8 "stupe\305\210"]
::msgcat::mcset cz "line flowstone" [encoding convertfrom utf-8 "sintrov\303\251 n\303\241teky"]
::msgcat::mcset en "line flowstone" [encoding convertfrom utf-8 "flowstone"]
::msgcat::mcset en_UK "line flowstone" [encoding convertfrom utf-8 "flowstone"]
::msgcat::mcset en_US "line flowstone" [encoding convertfrom utf-8 "flowstone"]
::msgcat::mcset es "line flowstone" [encoding convertfrom utf-8 "concreci\303\263n"]
::msgcat::mcset fr "line flowstone" [encoding convertfrom utf-8 "concr\303\251tion"]
::msgcat::mcset sk "line flowstone" [encoding convertfrom utf-8 "sintrov\303\251 n\303\241teky"]
::msgcat::mcset cz "line gradient" [encoding convertfrom utf-8 "sklon chodby"]
::msgcat::mcset en "line gradient" [encoding convertfrom utf-8 "passage gradient"]
::msgcat::mcset en_UK "line gradient" [encoding convertfrom utf-8 "passage gradient"]
::msgcat::mcset en_US "line gradient" [encoding convertfrom utf-8 "passage gradient"]
::msgcat::mcset es "line gradient" [encoding convertfrom utf-8 "gradiente"]
::msgcat::mcset fr "line gradient" [encoding convertfrom utf-8 "pente"]
::msgcat::mcset sk "line gradient" [encoding convertfrom utf-8 "sklon chodby"]
::msgcat::mcset cz "line label" [encoding convertfrom utf-8 "pojmenov\303\241n\303\255"]
::msgcat::mcset sk "line label" [encoding convertfrom utf-8 "pomenovanie"]
::msgcat::mcset cz "line overhang" [encoding convertfrom utf-8 "p\305\231evis"]
::msgcat::mcset en "line overhang" [encoding convertfrom utf-8 "overhang"]
::msgcat::mcset en_UK "line overhang" [encoding convertfrom utf-8 "overhang"]
::msgcat::mcset en_US "line overhang" [encoding convertfrom utf-8 "overhang"]
::msgcat::mcset es "line overhang" [encoding convertfrom utf-8 "extraplomo"]
::msgcat::mcset fr "line overhang" [encoding convertfrom utf-8 "surplomb"]
::msgcat::mcset sk "line overhang" [encoding convertfrom utf-8 "previs"]
::msgcat::mcset cz "line pit" [encoding convertfrom utf-8 "propast"]
::msgcat::mcset en "line pit" [encoding convertfrom utf-8 "pitch"]
::msgcat::mcset en_UK "line pit" [encoding convertfrom utf-8 "pitch"]
::msgcat::mcset en_US "line pit" [encoding convertfrom utf-8 "pit"]
::msgcat::mcset es "line pit" [encoding convertfrom utf-8 "pozo"]
::msgcat::mcset fr "line pit" [encoding convertfrom utf-8 "puits"]
::msgcat::mcset sk "line pit" [encoding convertfrom utf-8 "priepas\305\245"]
::msgcat::mcset cz "line rock-border" [encoding convertfrom utf-8 "kameny"]
::msgcat::mcset en "line rock-border" [encoding convertfrom utf-8 "rock border"]
::msgcat::mcset en_UK "line rock-border" [encoding convertfrom utf-8 "rock border"]
::msgcat::mcset en_US "line rock-border" [encoding convertfrom utf-8 "rock border"]
::msgcat::mcset es "line rock-border" [encoding convertfrom utf-8 "l\303\255mite roca"]
::msgcat::mcset fr "line rock-border" [encoding convertfrom utf-8 "bord d\342\200\231un rocher"]
::msgcat::mcset sk "line rock-border" [encoding convertfrom utf-8 "ohrani\304\215enie kame\305\210ov"]
::msgcat::mcset cz "line rock-edge" [encoding convertfrom utf-8 "hrany kamen\305\257"]
::msgcat::mcset en "line rock-edge" [encoding convertfrom utf-8 "rock edges"]
::msgcat::mcset en_UK "line rock-edge" [encoding convertfrom utf-8 "rock edges"]
::msgcat::mcset en_US "line rock-edge" [encoding convertfrom utf-8 "rock edges"]
::msgcat::mcset es "line rock-edge" [encoding convertfrom utf-8 "arista"]
::msgcat::mcset fr "line rock-edge" [encoding convertfrom utf-8 "ar\303\252te d\342\200\231un rocher"]
::msgcat::mcset sk "line rock-edge" [encoding convertfrom utf-8 "hrany kame\305\210ov"]
::msgcat::mcset cz "line section" [encoding convertfrom utf-8 "p\305\231\303\255\304\215n\303\275 \305\231ez"]
::msgcat::mcset en "line section" [encoding convertfrom utf-8 "cross-section"]
::msgcat::mcset en_UK "line section" [encoding convertfrom utf-8 "cross-section"]
::msgcat::mcset en_US "line section" [encoding convertfrom utf-8 "cross-section"]
::msgcat::mcset es "line section" [encoding convertfrom utf-8 "secci\303\263n"]
::msgcat::mcset fr "line section" [encoding convertfrom utf-8 "section"]
::msgcat::mcset sk "line section" [encoding convertfrom utf-8 "prie\304\215ny rez"]
::msgcat::mcset cz "line slope" [encoding convertfrom utf-8 "svah"]
::msgcat::mcset en "line slope" [encoding convertfrom utf-8 "slope"]
::msgcat::mcset en_UK "line slope" [encoding convertfrom utf-8 "slope"]
::msgcat::mcset en_US "line slope" [encoding convertfrom utf-8 "slope"]
::msgcat::mcset es "line slope" [encoding convertfrom utf-8 "pendiente"]
::msgcat::mcset fr "line slope" [encoding convertfrom utf-8 "pente"]
::msgcat::mcset sk "line slope" [encoding convertfrom utf-8 "\305\241ikm\303\241 plocha"]
::msgcat::mcset cz "line survey" [encoding convertfrom utf-8 "polygonov\303\275 tah"]
::msgcat::mcset en "line survey" [encoding convertfrom utf-8 "survey lines"]
::msgcat::mcset en_UK "line survey" [encoding convertfrom utf-8 "survey lines"]
::msgcat::mcset en_US "line survey" [encoding convertfrom utf-8 "survey lines"]
::msgcat::mcset es "line survey" [encoding convertfrom utf-8 "poligonal"]
::msgcat::mcset fr "line survey" [encoding convertfrom utf-8 "vis\303\251e topo"]
::msgcat::mcset sk "line survey" [encoding convertfrom utf-8 "polyg\303\263nov\303\275 \305\245ah"]
::msgcat::mcset cz "line wall" [encoding convertfrom utf-8 "st\304\233na"]
::msgcat::mcset en "line wall" [encoding convertfrom utf-8 "wall"]
::msgcat::mcset en_UK "line wall" [encoding convertfrom utf-8 "wall"]
::msgcat::mcset en_US "line wall" [encoding convertfrom utf-8 "wall"]
::msgcat::mcset es "line wall" [encoding convertfrom utf-8 "pared"]
::msgcat::mcset fr "line wall" [encoding convertfrom utf-8 "mur"]
::msgcat::mcset sk "line wall" [encoding convertfrom utf-8 "stena"]
::msgcat::mcset cz "line water-flow" [encoding convertfrom utf-8 "vodn\303\255 tok"]
::msgcat::mcset en "line water-flow" [encoding convertfrom utf-8 "water flow"]
::msgcat::mcset en_UK "line water-flow" [encoding convertfrom utf-8 "water flow"]
::msgcat::mcset en_US "line water-flow" [encoding convertfrom utf-8 "water flow"]
::msgcat::mcset es "line water-flow" [encoding convertfrom utf-8 "curso agua"]
::msgcat::mcset fr "line water-flow" [encoding convertfrom utf-8 "rivi\303\250re"]
::msgcat::mcset sk "line water-flow" [encoding convertfrom utf-8 "vodn\303\275 tok"]
::msgcat::mcset cz "area blocks" [encoding convertfrom utf-8 "skaln\303\255 bloky"]
::msgcat::mcset en "area blocks" [encoding convertfrom utf-8 "blocks"]
::msgcat::mcset en_UK "area blocks" [encoding convertfrom utf-8 "blocks"]
::msgcat::mcset en_US "area blocks" [encoding convertfrom utf-8 "blocks"]
::msgcat::mcset es "area blocks" [encoding convertfrom utf-8 "bloques"]
::msgcat::mcset sk "area blocks" [encoding convertfrom utf-8 "skaln\303\251 bloky"]
::msgcat::mcset cz "area clay" [encoding convertfrom utf-8 "bahno"]
::msgcat::mcset en "area clay" [encoding convertfrom utf-8 "clay"]
::msgcat::mcset en_UK "area clay" [encoding convertfrom utf-8 "clay"]
::msgcat::mcset en_US "area clay" [encoding convertfrom utf-8 "clay"]
::msgcat::mcset es "area clay" [encoding convertfrom utf-8 "arcilla"]
::msgcat::mcset sk "area clay" [encoding convertfrom utf-8 "blato"]
::msgcat::mcset cz "area debris" [encoding convertfrom utf-8 "\305\241t\304\233rk"]
::msgcat::mcset en "area debris" [encoding convertfrom utf-8 "debris"]
::msgcat::mcset en_UK "area debris" [encoding convertfrom utf-8 "debris"]
::msgcat::mcset en_US "area debris" [encoding convertfrom utf-8 "debris"]
::msgcat::mcset es "area debris" [encoding convertfrom utf-8 "derrubios"]
::msgcat::mcset fr "area debris" [encoding convertfrom utf-8 "d\303\251bris"]
::msgcat::mcset sk "area debris" [encoding convertfrom utf-8 "\305\241trk"]
::msgcat::mcset cz "area ice" [encoding convertfrom utf-8 "led"]
::msgcat::mcset en "area ice" [encoding convertfrom utf-8 "ice"]
::msgcat::mcset en_UK "area ice" [encoding convertfrom utf-8 "ice"]
::msgcat::mcset en_US "area ice" [encoding convertfrom utf-8 "ice"]
::msgcat::mcset es "area ice" [encoding convertfrom utf-8 "hielo"]
::msgcat::mcset sk "area ice" [encoding convertfrom utf-8 "\304\276ad"]
::msgcat::mcset cz "area pebbles" [encoding convertfrom utf-8 "valouny"]
::msgcat::mcset en "area pebbles" [encoding convertfrom utf-8 "pebbles"]
::msgcat::mcset en_UK "area pebbles" [encoding convertfrom utf-8 "pebbles"]
::msgcat::mcset en_US "area pebbles" [encoding convertfrom utf-8 "pebbles"]
::msgcat::mcset es "area pebbles" [encoding convertfrom utf-8 "cantos rodados"]
::msgcat::mcset sk "area pebbles" [encoding convertfrom utf-8 "okr\303\272hliaky"]
::msgcat::mcset cz "area sand" [encoding convertfrom utf-8 "p\303\255sek"]
::msgcat::mcset en "area sand" [encoding convertfrom utf-8 "sand"]
::msgcat::mcset en_UK "area sand" [encoding convertfrom utf-8 "sand"]
::msgcat::mcset en_US "area sand" [encoding convertfrom utf-8 "sand"]
::msgcat::mcset es "area sand" [encoding convertfrom utf-8 "arena"]
::msgcat::mcset fr "area sand" [encoding convertfrom utf-8 "sable"]
::msgcat::mcset sk "area sand" [encoding convertfrom utf-8 "piesok"]
::msgcat::mcset cz "area snow" [encoding convertfrom utf-8 "sn\303\255h"]
::msgcat::mcset en "area snow" [encoding convertfrom utf-8 "snow"]
::msgcat::mcset en_UK "area snow" [encoding convertfrom utf-8 "snow"]
::msgcat::mcset en_US "area snow" [encoding convertfrom utf-8 "snow"]
::msgcat::mcset es "area snow" [encoding convertfrom utf-8 "nieve"]
::msgcat::mcset sk "area snow" [encoding convertfrom utf-8 "sneh"]
::msgcat::mcset cz "area sump" [encoding convertfrom utf-8 "sifon"]
::msgcat::mcset en "area sump" [encoding convertfrom utf-8 "sump"]
::msgcat::mcset en_UK "area sump" [encoding convertfrom utf-8 "sump"]
::msgcat::mcset en_US "area sump" [encoding convertfrom utf-8 "sump"]
::msgcat::mcset es "area sump" [encoding convertfrom utf-8 "sif\303\263n"]
::msgcat::mcset fr "area sump" [encoding convertfrom utf-8 "siphon"]
::msgcat::mcset sk "area sump" [encoding convertfrom utf-8 "zatopen\303\241 plocha (sif\303\263n)"]
::msgcat::mcset cz "area water" [encoding convertfrom utf-8 "vodn\303\255 plocha"]
::msgcat::mcset en "area water" [encoding convertfrom utf-8 "water"]
::msgcat::mcset en_UK "area water" [encoding convertfrom utf-8 "water"]
::msgcat::mcset en_US "area water" [encoding convertfrom utf-8 "water"]
::msgcat::mcset es "area water" [encoding convertfrom utf-8 "agua"]
::msgcat::mcset fr "area water" [encoding convertfrom utf-8 "eau"]
::msgcat::mcset sk "area water" [encoding convertfrom utf-8 "vodn\303\241 plocha"]
