.TH "THERION" "1" "2003/07/15"
.SH "NAME" 
XTherion \(em Graphical drawing editor for Therion 
.SH "SYNOPSIS" 
.PP 
\fBxtherion\fP 
.SH "DESCRIPTION" 
.PP 
This manual page documents \fBXTherion\fP, which is part of the therion package. 
.PP 
\fBXTherion\fP is an application that serves as a graphical 
front end for Therion. Therion itself works entirely with text-based files, but  
much of the data needs to be generated graphically, so XTherion is one example of  
how it might be done.  It is written in Tcl/Tk. 
.PP 
\fBXTherion\fP lets you load a background GIF, PPM or PNM  
(a scan of the cave segment or to-scale notes), scale it, then draw Therion 'scraps' over  
the image, and relate it to survey stations and save the resulting data. 
.PP 
For full information see The Therion Book which describes the application and 
its use in detail. 
.SH "OPTIONS" 
.PP 
XTherion takes no options. 
.SH "SEE ALSO" 
.PP 
loch(1), therion(1)
.SH "AUTHOR" 
.PP 
Stacho Mudrak. This manual page was written by Wookey wookey@debian.org for 
the \fBDebian\fP system. Modified by MB.
