/**
 * @file thlangdata.cxx
 * Therion language translations module.
 *
 * THIS FILE IS GENERATED AUTOMATICALLY, DO NOT MODIFY IT !!!
 */

 
typedef const char * thlang_pchar;


static const thstok thtt_lang [] = {
  {"bg", THLANG_BG},
  {"cz", THLANG_CZ},
  {"de", THLANG_DE},
  {"el", THLANG_EL},
  {"en", THLANG_EN},
  {"en_UK", THLANG_EN_UK},
  {"en_US", THLANG_EN_US},
  {"es", THLANG_ES},
  {"fr", THLANG_FR},
  {"it", THLANG_IT},
  {"mi", THLANG_MI},
  {"pl", THLANG_PL},
  {"pt", THLANG_PT},
  {"pt_BR", THLANG_PT_BR},
  {"pt_PT", THLANG_PT_PT},
  {"ru", THLANG_RU},
  {"sk", THLANG_SK},
  {"sq", THLANG_SQ},
  {"zh", THLANG_ZH},
  {"zh_CN", THLANG_ZH_CN},
  {NULL, THLANG_UNKNOWN},
};



static const thlang_pchar thlang__cxxids []  = {
  "THLANG_BG",
  "THLANG_CZ",
  "THLANG_DE",
  "THLANG_EL",
  "THLANG_EN",
  "THLANG_EN_UK",
  "THLANG_EN_US",
  "THLANG_ES",
  "THLANG_FR",
  "THLANG_IT",
  "THLANG_MI",
  "THLANG_PL",
  "THLANG_PT",
  "THLANG_PT_BR",
  "THLANG_PT_PT",
  "THLANG_RU",
  "THLANG_SK",
  "THLANG_SQ",
  "THLANG_ZH",
  "THLANG_ZH_CN",
};



static const int thlang__alternatives [] = {
  THLANG_UNKNOWN,
  THLANG_UNKNOWN,
  THLANG_UNKNOWN,
  THLANG_UNKNOWN,
  THLANG_UNKNOWN,
  THLANG_EN,
  THLANG_EN,
  THLANG_UNKNOWN,
  THLANG_UNKNOWN,
  THLANG_UNKNOWN,
  THLANG_UNKNOWN,
  THLANG_UNKNOWN,
  THLANG_UNKNOWN,
  THLANG_PT,
  THLANG_PT,
  THLANG_UNKNOWN,
  THLANG_UNKNOWN,
  THLANG_UNKNOWN,
  THLANG_UNKNOWN,
  THLANG_ZH,
};



static const thstok thtt__texts [184] = {
  {"area bedrock",0},
  {"area blocks",1},
  {"area clay",2},
  {"area debris",3},
  {"area flowstone",4},
  {"area ice",5},
  {"area moonmilk",6},
  {"area pebbles",7},
  {"area sand",8},
  {"area snow",9},
  {"area sump",10},
  {"area water",11},
  {"line border",12},
  {"line border:presumed",13},
  {"line border:temporary",14},
  {"line border:visible",15},
  {"line ceiling-meander",16},
  {"line ceiling-step",17},
  {"line chimney",18},
  {"line contour",19},
  {"line fixed-ladder",20},
  {"line floor-meander",21},
  {"line floor-step",22},
  {"line flowstone",23},
  {"line gradient",24},
  {"line handrail",25},
  {"line label",26},
  {"line map-connection",27},
  {"line moonmilk",28},
  {"line overhang",29},
  {"line pit",30},
  {"line rock-border",31},
  {"line rock-edge",32},
  {"line rope",33},
  {"line rope-ladder",34},
  {"line section",35},
  {"line slope",36},
  {"line steps",37},
  {"line survey",38},
  {"line via-ferrata",39},
  {"line wall",40},
  {"line wall:bedrock",41},
  {"line wall:blocks",42},
  {"line wall:clay",43},
  {"line wall:debris",44},
  {"line wall:flowstone",45},
  {"line wall:ice",46},
  {"line wall:moonmilk",47},
  {"line wall:overlying",48},
  {"line wall:pebbles",49},
  {"line wall:pit",50},
  {"line wall:presumed",51},
  {"line wall:sand",52},
  {"line wall:underlying",53},
  {"line wall:unsurveyed",54},
  {"line water-flow",55},
  {"line water-flow:conjectural",56},
  {"line water-flow:intermittent",57},
  {"line water-flow:permanent",58},
  {"point air-draught",59},
  {"point air-draught:summer",60},
  {"point air-draught:winter",61},
  {"point altitude",62},
  {"point anastomosis",63},
  {"point anchor",64},
  {"point aragonite",65},
  {"point archeo-material",66},
  {"point bedrock",67},
  {"point blocks",68},
  {"point breakdown-choke",69},
  {"point bridge",70},
  {"point camp",71},
  {"point cave-pearl",72},
  {"point clay",73},
  {"point clay-choke",74},
  {"point clay-tree",75},
  {"point continuation",76},
  {"point crystal",77},
  {"point curtain",78},
  {"point date",79},
  {"point debris",80},
  {"point dig",81},
  {"point dimensions",82},
  {"point disk",83},
  {"point entrance",84},
  {"point fixed-ladder",85},
  {"point flag:air-draught",86},
  {"point flag:arch",87},
  {"point flag:continuation",88},
  {"point flag:dig",89},
  {"point flag:doline",90},
  {"point flag:entrance",91},
  {"point flag:overhang",92},
  {"point flag:sink",93},
  {"point flag:spring",94},
  {"point flowstone",95},
  {"point flowstone-choke",96},
  {"point flute",97},
  {"point gradient",98},
  {"point guano",99},
  {"point gypsum",100},
  {"point gypsum-flower",101},
  {"point handrail",102},
  {"point height",103},
  {"point height:negative",104},
  {"point height:positive",105},
  {"point height:unsigned",106},
  {"point helictite",107},
  {"point ice",108},
  {"point ice-pillar",109},
  {"point ice-stalactite",110},
  {"point ice-stalagmite",111},
  {"point karren",112},
  {"point label",113},
  {"point low-end",114},
  {"point moonmilk",115},
  {"point narrow-end",116},
  {"point no-equipment",117},
  {"point paleo-material",118},
  {"point passage-height",119},
  {"point passage-height:both",120},
  {"point passage-height:negative",121},
  {"point passage-height:positive",122},
  {"point passage-height:unsigned",123},
  {"point pebbles",124},
  {"point pillar",125},
  {"point pillars",126},
  {"point popcorn",127},
  {"point raft",128},
  {"point raft-cone",129},
  {"point remark",130},
  {"point rimstone-dam",131},
  {"point rimstone-pool",132},
  {"point root",133},
  {"point rope",134},
  {"point rope-ladder",135},
  {"point sand",136},
  {"point scallop",137},
  {"point section",138},
  {"point sink",139},
  {"point snow",140},
  {"point soda-straw",141},
  {"point spring",142},
  {"point stalactite",143},
  {"point stalactites",144},
  {"point stalagmite",145},
  {"point stalagmites",146},
  {"point station",147},
  {"point station-name",148},
  {"point station:fixed",149},
  {"point station:natural",150},
  {"point station:painted",151},
  {"point station:temporary",152},
  {"point steps",153},
  {"point traverse",154},
  {"point vegetable-debris",155},
  {"point via-ferrata",156},
  {"point wall-altitude",157},
  {"point wall-calcite",158},
  {"point water",159},
  {"point water-flow",160},
  {"point water-flow:intermittent",161},
  {"point water-flow:paleo",162},
  {"point water-flow:permanent",163},
  {"surface legs",164},
  {"title carto",165},
  {"title carto (plural)",166},
  {"title cave depth",167},
  {"title cave length",168},
  {"title color-legend-altitude",169},
  {"title color-legend-map",170},
  {"title explo",171},
  {"title explo (plural)",172},
  {"title legend",173},
  {"title map",174},
  {"title model",175},
  {"title preview above",176},
  {"title preview below",177},
  {"title surface bitmap",178},
  {"title topo",179},
  {"title topo (plural)",180},
  {"units ft",181},
  {"units m",182},
  {NULL, -1},
};



static thlang_pchar thlang__translations [180][20] = {
  {
    "основна скала",
    "pevná skála",
    "Deckgebirge",
    "πέτρωμα",
    "bedrock",
    NULL,
    NULL,
    "roca madre",
    "roche",
    "roccia",
    NULL,
    NULL,
    "rocha encaixante",
    NULL,
    NULL,
    "коренная порода",
    "pevná skala",
    "shtrat shkembi",
    "基岩区",
    "基岩区",
  },
  {
    "блокаж",
    "skalní bloky",
    "Fläche mit Blöcken",
    "ογκόλιθοι",
    "blocks, breakdown",
    NULL,
    NULL,
    "bloques",
    "blocs",
    "massi",
    "pakaru a kōhatunui",
    "bloki skalne",
    "blocos",
    NULL,
    NULL,
    "навал глыб",
    "skalné bloky",
    "blloqe",
    "块石堆积区",
    "块石堆积区",
  },
  {
    "глина",
    "bahno",
    "Lehmfläche",
    "άργιλος",
    "clay",
    NULL,
    NULL,
    "arcilla",
    "argile",
    "argilla",
    "oneuku",
    "glina",
    "lama",
    NULL,
    NULL,
    "глина",
    "íl",
    "argjil",
    "粘土区",
    "粘土区",
  },
  {
    "чакъл",
    "štěrk",
    "Schuttfläche",
    "χαλάσματα",
    "debris",
    NULL,
    NULL,
    "derrubios",
    "débris",
    "detriti",
    "otaota",
    "żwir",
    "escombros",
    NULL,
    NULL,
    "щебень",
    "štrk",
    "mbetje-gurresh",
    "碎屑沉积区",
    "碎屑沉积区",
  },
  {
    "каменен водопад",
    "sintrové náteky",
    "flächiger Sinter",
    "σταλαγμιτικό υλικό δαπέδου",
    "flowstone",
    NULL,
    NULL,
    "concreción",
    "concrétion",
    "concrezione",
    NULL,
    NULL,
    "escorrimento",
    NULL,
    NULL,
    "натечный каскад",
    "sintrové náteky",
    "gurre-rrjedhes",
    "流石区",
    "流石区",
  },
  {
    "лед",
    "led",
    "Eisfläche",
    "πάγος",
    "ice",
    NULL,
    NULL,
    "hielo",
    "glace",
    "ghiaccio",
    "kōpaka",
    "lód",
    "gelo",
    NULL,
    NULL,
    "лёд",
    "ľad",
    "akull",
    "冰区",
    "冰区",
  },
  {
    "пещерно мляко",
    "nickamínek",
    "Bergmilch",
    "γάλα σπηλαίου",
    "moonmilk",
    NULL,
    NULL,
    NULL,
    "mondmilch",
    "moonmilk",
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    "лунное молоко",
    "náteky mäkkého sintra",
    "qumesht-hena",
    "月奶石区",
    "月奶石区",
  },
  {
    "камъчета",
    "valouny",
    "Kiesfläche",
    "χαλίκια",
    "pebbles",
    NULL,
    NULL,
    "cantos rodados",
    "galets/pierres",
    "ciotoli",
    "nga kōhatu iti",
    "okręglaki",
    "seixos",
    NULL,
    NULL,
    "галька",
    "okrúhliaky",
    "gurralece",
    "卵石区",
    "卵石区",
  },
  {
    "пясък",
    "písek",
    "Sandfläche",
    "άμμος",
    "sand",
    NULL,
    NULL,
    "arena",
    "sable",
    "sabbia",
    "onepū",
    "piasek",
    "areia",
    NULL,
    NULL,
    "песок",
    "piesok",
    "rane",
    "砂区",
    "砂区",
  },
  {
    "сняг",
    "sníh",
    "Schneefläche",
    "χιόνι",
    "snow",
    NULL,
    NULL,
    "nieve",
    "neige",
    "neve",
    "huka",
    "śnieg",
    "neve",
    NULL,
    NULL,
    "снег",
    "sneh",
    "bore",
    "雪区",
    "雪区",
  },
  {
    "сифон",
    "sifon",
    "Siphonfläche",
    "σιφόνι",
    "sump",
    NULL,
    NULL,
    "sifón",
    "siphon",
    "sifone",
    "kari a wai",
    "syfon",
    "sifão",
    NULL,
    NULL,
    "сифон",
    "zatopená plocha (sifón)",
    "sifoni",
    "潜水塘区",
    "潜水塘区",
  },
  {
    "вода",
    "vodní plocha",
    "Wasserfläche",
    "νερό",
    "water",
    NULL,
    NULL,
    "agua",
    "eau",
    "acqua",
    "wai",
    "powierzchnia wody",
    "água",
    NULL,
    NULL,
    "вода",
    "vodná plocha",
    "uje",
    "水体区",
    "水体区",
  },
  {
    "граница",
    "ohraničení",
    "Begrenzung",
    "άκρη",
    "border",
    NULL,
    NULL,
    "límite",
    "bord",
    "bordo",
    "rohe",
    "granica",
    "borda",
    NULL,
    NULL,
    "граница",
    "ohraničenie",
    "kufiri",
    "边界线",
    "边界线",
  },
  {
    "предполагаема граница",
    "předpokládané ohraničení",
    "geschätzte Begrenzung",
    "υποθετική άκρη",
    "presumed border",
    NULL,
    NULL,
    "límite supuesto",
    "bord, supposé",
    "bordo presunto",
    "rohe whakaaringa whakaaro",
    "niewidoczna granica",
    "borda presumida",
    NULL,
    NULL,
    "предполагаемая граница",
    "predpokladané ohraničenie",
    "kufij I supozuar",
    "推测边界",
    "推测边界",
  },
  {
    "временна граница",
    "nestálé ohraničení",
    "vorübergehende Begrenzung",
    "προσωρινή άκρη",
    "temporary border",
    NULL,
    NULL,
    "límite temporal",
    "bord, temporaire",
    "bordo temporaneo",
    "rohe mo te wā",
    "tymczasowa granica",
    "borda temporária",
    NULL,
    NULL,
    "временная граница",
    "nestále ohraničenie",
    "kufij i perkohshem",
    "暂时边界",
    "暂时边界",
  },
  {
    "видима граница",
    "ohraničení",
    "sichtbare Begrenzung",
    "άκρη",
    "border",
    NULL,
    NULL,
    "límite",
    "bord",
    "bordo",
    "rohe",
    "granica",
    "borda",
    NULL,
    NULL,
    "видимая граница",
    "ohraničenie",
    "vije kufiri-e dukshme",
    "可见边界",
    "可见边界",
  },
  {
    "меандър, канал в тавана",
    "stropní meandr",
    "Deckenmäander",
    "μαίανδρος οροφής",
    "ceiling meander",
    NULL,
    NULL,
    "meandro inverso",
    "méandre de plafond",
    "canale di volta",
    "kopiko tuanui",
    "meander w stropie",
    "meandro no teto",
    "meandro no teto",
    "meandro no tecto",
    "меандр, канал в потолке",
    "stropný meander",
    "rrjedhe uji gjarperore ne tavan",
    "天沟",
    "天沟",
  },
  {
    "ниша в тавана",
    "změna výšky stropu",
    "Deckenstufe",
    "σκαλοπάτι οροφής",
    "ceiling step",
    NULL,
    NULL,
    "resalte inverso",
    "marche de plafond",
    "gradino a soffitto",
    "tapuae ki te tuanui",
    "zmiana wysokości stropu",
    "degrau no teto",
    "degrau no teto",
    "degrau no tecto",
    "уступ потолка",
    "zmena výšky stropu",
    "shkalle ne tavan",
    "梯坎状洞顶",
    "梯坎状洞顶",
  },
  {
    "комин",
    "komín",
    "Schlot",
    "καμινάδα",
    "chimney",
    NULL,
    NULL,
    "chimenea",
    "cheminée",
    "camino",
    "tumera",
    "komin",
    "chaminé",
    NULL,
    NULL,
    "труба",
    "komín",
    "oxhak",
    "烟囱式洞道",
    "烟囱式洞道",
  },
  {
    "контур",
    "vrstevnice",
    "Höhenlinie",
    "ισοϋψής",
    "contour",
    NULL,
    NULL,
    "contorno",
    "contour",
    "contorno",
    "koru",
    "poziomica",
    "contorno",
    NULL,
    NULL,
    "контур",
    "vrstevnica",
    "kontura",
    "等高线",
    "等高线",
  },
  {
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
  },
  {
    "меандър, канал в пода",
    "meandr ve dně",
    "Bodenmäander",
    "μαίανδρος δαπέδου",
    "floor meander",
    NULL,
    NULL,
    "meandro",
    "méandre au sol",
    "meandro",
    "kopiko",
    "meander w dnie",
    "meandro no piso",
    NULL,
    NULL,
    "меандр, канал в полу",
    "meander v dne",
    "rrjedhe uji gjarperore",
    "洞底蛇曲",
    "洞底蛇曲",
  },
  {
    "праг",
    "stupeň",
    "Bodenstufe",
    "σκαλοπάτι",
    "floor step",
    NULL,
    NULL,
    "resalte",
    "marche",
    "gradino",
    "tapuae",
    "próg",
    "degrau",
    NULL,
    NULL,
    "уступ пола",
    "stupeň",
    "shkalle ne dysheme",
    "梯坎状洞底",
    "梯坎状洞底",
  },
  {
    "каменен водопад",
    "sintrové náteky",
    "flächiger Sinter",
    "σταλαγμιτικό υλικό δαπέδου",
    "flowstone",
    NULL,
    NULL,
    "concreción",
    "concrétion",
    "concrezione",
    "pari kōhatu",
    "nacieki",
    "escorrimento",
    NULL,
    NULL,
    "натечный каскад",
    "sintrové náteky",
    "gurre-rrjedhes",
    "流石",
    "流石",
  },
  {
    "наклон на галерията",
    "sklon chodby",
    "Gefälle",
    "κλίση στοάς",
    "passage gradient",
    NULL,
    NULL,
    "gradiente",
    "pente",
    "scivolo",
    "heke",
    "nachylenie korytarza",
    "declividade da galeria",
    NULL,
    NULL,
    "уклон хода",
    "sklon chodby",
    "pjertesia e kalimit",
    "洞道坡度",
    "洞道坡度",
  },
  {
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
  },
  {
    "етикет",
    "pojmenování",
    "Beschriftung",
    "περιγραφή",
    "label",
    NULL,
    NULL,
    "etiqueta",
    "libellé",
    "etichetta",
    "ingoa",
    "nazwa",
    "indicação",
    NULL,
    NULL,
    "текстовая метка",
    "pomenovanie",
    "mbishkrim",
    "标记",
    "标记",
  },
  {
    "свързване на карти",
    "spojení map",
    "zusammenhängende Pläne",
    "ένωση χαρτών",
    "map connection",
    NULL,
    NULL,
    NULL,
    "jonction de carte",
    "riporto di mappa",
    "mahere whenua ki te hui",
    "połączenie map",
    NULL,
    NULL,
    NULL,
    "линия выноса",
    "prepojenie máp",
    "lidhjet ne harta",
    "图形连接",
    "图形连接",
  },
  {
    "пещерно мляко",
    "nickamínek",
    "Bergmilch",
    "γάλα σπηλαίου",
    "moonmilk",
    NULL,
    NULL,
    NULL,
    "mondmilch",
    "moonmilk",
    "mirika marama",
    "miękkie nacieki",
    NULL,
    NULL,
    NULL,
    "лунное молоко",
    "náteky mäkkého sintra",
    "qumesht-hena",
    "月奶石",
    "月奶石",
  },
  {
    "скална площадка",
    "převis",
    "Überhang",
    "προέκταση οροφής",
    "overhang",
    NULL,
    NULL,
    "extraplomo",
    "surplomb",
    "sporgenza",
    "tauwharenga",
    "przewieszka",
    "projeção",
    "projeção",
    "projecção",
    "нависание потолка",
    "previs",
    "varese",
    "倒倾斜",
    "倒倾斜",
  },
  {
    "кладенец",
    "propast",
    "Schacht",
    "πηγάδι",
    "pitch",
    "pitch",
    "pit",
    "pozo",
    "puits",
    "pozzo",
    "tupari",
    "studnia",
    "desnível",
    NULL,
    NULL,
    "колодец",
    "priepasť",
    "ngjitje",
    "竖井",
    "竖井",
  },
  {
    "външен ръб на камък",
    "kameny",
    "Umriss eines Felsens",
    "περίγραμμα βράχου",
    "rock border",
    NULL,
    NULL,
    "contorno bloque",
    "bord d’un rocher",
    "bordo masso",
    "rohe kōhatu",
    "obrys kamienia",
    "lateral da rocha",
    NULL,
    NULL,
    "внешний кромка глыбы",
    "obrys kameňa",
    "kufij shkembinjsh",
    "块石边界",
    "块石边界",
  },
  {
    "вътрешен ръб на камък",
    "hrany kamenů",
    "Struktur eines Felsens",
    "άκρη βράχου",
    "rock edges",
    NULL,
    NULL,
    "arista bloque",
    "arête d’un rocher",
    "spigolo masso",
    "mata kohatu",
    "krawędzie kamienia",
    "bordas da rocha",
    NULL,
    NULL,
    "внутренняя кромка глыбы",
    "hrany kameňa",
    "skaji I shkembit",
    "块石边缘",
    "块石边缘",
  },
  {
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
  },
  {
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
  },
  {
    "напречно сечение",
    "příčný řez",
    "Schnittlinie",
    "τομή",
    "cross-section",
    NULL,
    NULL,
    "sección",
    "section",
    "sezione trasversale",
    "taha papahanga",
    "przekrój",
    "corte",
    NULL,
    NULL,
    "выносная линия сечения",
    "priečny rez",
    "kryq-ndarje",
    "横断面",
    "横断面",
  },
  {
    "склон",
    "svah",
    "Hangform",
    "κλίση",
    "slope",
    NULL,
    NULL,
    "pendiente",
    "pente",
    "scivolo",
    "tupari",
    "pochyła powierzchnia",
    "declive",
    NULL,
    NULL,
    "склон",
    "šikmá plocha",
    "breg",
    "斜坡",
    "斜坡",
  },
  {
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
  },
  {
    "антена",
    "polygonový tah",
    "Messzug",
    "γραμμή χαρτογράφησης",
    "survey lines",
    NULL,
    NULL,
    "poligonal",
    "visée topo",
    "poligonale",
    "ruri rārangi",
    "ciąg pomiarowy",
    "linha de topografia",
    NULL,
    NULL,
    "нитка хода",
    "polygónový ťah",
    "vijat matese-vrojtuese",
    "测线",
    "测线",
  },
  {
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
  },
  {
    "стена",
    "stěna",
    "Wand",
    "τοίχος",
    "wall",
    NULL,
    NULL,
    "pared",
    "mur",
    "parete",
    "tarā",
    "ściana",
    "parede",
    NULL,
    NULL,
    "стена",
    "stena",
    "muri",
    "洞道边界",
    "洞道边界",
  },
  {
    "стена (основна скала)",
    "stěna",
    "Wand zum Deckgebirge",
    "τοίχος",
    "wall",
    NULL,
    NULL,
    "pared",
    "mur",
    "roccia",
    "tarā",
    "ściana",
    "parede",
    NULL,
    NULL,
    "стена",
    "stena",
    "shkembi-muri",
    "基岩边界",
    "基岩边界",
  },
  {
    "стена - блокаж",
    "zával",
    "Wand aus Versturz",
    "ογκόλιθοι",
    "blocks, breakdown",
    NULL,
    NULL,
    "bloques",
    "effrondrement",
    "massi",
    "pakaru",
    "ściana utworzona przez zawalisko",
    "desmoronamento",
    NULL,
    NULL,
    "глыбы",
    "stena tvorená závalom",
    "blloqe",
    "崩塌块石边界",
    "崩塌块石边界",
  },
  {
    "глина",
    "bahno",
    "Wand aus Lehm",
    "άργιλος",
    "clay",
    NULL,
    NULL,
    "arcilla",
    "argile",
    "argilla",
    "oneuku",
    "ściana z gliny",
    "lama",
    NULL,
    NULL,
    "глина",
    "stena tvorená ílom",
    "argjil",
    "粘土边界",
    "粘土边界",
  },
  {
    "чакъл",
    "štěrk",
    "Wand aus Schutt",
    "χαλάσματα",
    "debris",
    NULL,
    NULL,
    "derrubios",
    "débris de roche",
    "detriti",
    "otaota",
    "ściana utworzona przez żwir",
    "escombros",
    NULL,
    NULL,
    "щебень",
    "stena tvorená suťou",
    "depozitime/mbetje gurresh",
    "碎屑沉积边界",
    "碎屑沉积边界",
  },
  {
    NULL,
    NULL,
    "Wand aus Sinter",
    NULL,
    "flowstone wall",
    NULL,
    NULL,
    NULL,
    NULL,
    "colata",
    "tāra a pari kōhatu",
    "ściana z nacieków",
    NULL,
    NULL,
    NULL,
    NULL,
    "stena tvorená sintrom",
    NULL,
    "流石边界",
    "流石边界",
  },
  {
    "лед/фирн",
    "led",
    "Wand aus Eis",
    "πάγος",
    "ice",
    NULL,
    NULL,
    "hielo",
    "glace",
    "ghiaccio",
    "kōpaka",
    "ściana z lodu",
    "gelo",
    NULL,
    NULL,
    "лед, фирн",
    "stena tvorená ľadom",
    "akull",
    "冰边界",
    "冰边界",
  },
  {
    NULL,
    NULL,
    "Wand aus Bergmilch",
    NULL,
    "moonmilk wall",
    NULL,
    NULL,
    NULL,
    NULL,
    "moonmilk",
    "tāra a mirika marama",
    "ściana z miękkich nacieków",
    NULL,
    NULL,
    NULL,
    NULL,
    "stena tvorená mäkkým sintrom",
    NULL,
    "月奶石边界",
    "月奶石边界",
  },
  {
    NULL,
    NULL,
    "überlagerter Wandverlauf",
    NULL,
    "overlying wall",
    NULL,
    NULL,
    NULL,
    NULL,
    "parete:sovrastante",
    "tāra ki runga",
    "ściana położona wyżej",
    NULL,
    NULL,
    NULL,
    NULL,
    "stena vyššej úrovne",
    NULL,
    "洞顶边界",
    "洞顶边界",
  },
  {
    "камъчета",
    "valouny",
    "Wand aus Kies",
    "χαλίκια",
    "pebbles",
    NULL,
    NULL,
    "cantos rodados",
    "cailloux",
    "ciotoli",
    "nga kōhatu iti",
    "ściana utworzona przez okręglaki",
    "seixos",
    NULL,
    NULL,
    "галька",
    "stena tvorená okruhliakmi",
    "gurralece",
    "卵砾石边界",
    "卵砾石边界",
  },
  {
    NULL,
    NULL,
    "Eingangsschacht",
    NULL,
    "entrance pit",
    NULL,
    NULL,
    NULL,
    NULL,
    "parete:pozzo",
    "rua",
    "studnia wstępna",
    NULL,
    NULL,
    NULL,
    NULL,
    "vstupná priepasť",
    NULL,
    "竖井洞口",
    "竖井洞口",
  },
  {
    "предполагаема стена",
    "předpokládaná stěna",
    "Wand geschätzt",
    "τοίχος υποθετικός",
    "presumed wall",
    NULL,
    NULL,
    "pared supuesta",
    "mur supposé",
    "parete:presunta",
    "tāra whakaaro",
    "niewidoczna ściana",
    "parede presumida",
    NULL,
    NULL,
    "предпологаемая стена",
    "predpokladaná stena",
    "muri I supozuar",
    "推测洞道边界",
    "推测洞道边界",
  },
  {
    "пясък",
    "písek",
    "Wand aus Sand",
    "άμμος",
    "sand",
    NULL,
    NULL,
    "arena",
    "sable",
    "sabbia",
    "onepū",
    "ściana utworzona przez piasek",
    "areia",
    NULL,
    NULL,
    "песок",
    "stena tvorená pieskom",
    "rane",
    "砂边界",
    "砂边界",
  },
  {
    "по-ниско разположена стена",
    "stěna nižší úrovně",
    "Wand unterlagernder Gang",
    "υποκείμενος τοίχος",
    "underlying wall",
    NULL,
    NULL,
    "pared subyacente",
    "mur sousjacent",
    "parete:sottostante",
    "tāra ki raro",
    "ściana położona niżej",
    "parede subjacente",
    NULL,
    NULL,
    "нижерасположенная стена",
    "stena nižšej úrovne",
    "muri I shtrire",
    "洞底边界",
    "洞底边界",
  },
  {
    "окомерна скица на стените",
    "nezaměřená stěna",
    "Wand unvermessen",
    "τοίχος (μη χαρτογραφημένος)",
    "unsurveyed wall",
    NULL,
    NULL,
    "pared no topografiada",
    "mur non topographié",
    "parete:stimata",
    "ka rūri tāra",
    "ściana nie pomierzona",
    "parede não-topografada",
    NULL,
    NULL,
    "глазомерная съемка стен",
    "nezameraná stena",
    "muri I pamatur",
    "未测量洞道边界",
    "未测量洞道边界",
  },
  {
    "водно течение",
    "vodní tok",
    "Gerinne",
    "υδρορροή",
    "water flow",
    NULL,
    NULL,
    "curso agua",
    "rivière",
    "corso d'acqua",
    "wairere",
    "ciek wodny",
    "fluxo de água",
    NULL,
    NULL,
    "водоток",
    "vodný tok",
    "rrjedhe uji",
    "水流",
    "水流",
  },
  {
    "предполагаемо водно течение",
    "předpokládaný vodní tok",
    "vermutetes Gerinne",
    "υποτιθέμενη υδρορροή",
    "conjectural water flow",
    NULL,
    NULL,
    "curso agua supuesto",
    "rivière, conjoncturelle",
    "corso d'acqua presunto",
    "wairere a pātai",
    "przewidywany ciek wodny",
    "fluxo de água suposto",
    NULL,
    NULL,
    "предполагаемый водоток",
    "predpokladaný vodný tok",
    "rrjedhe uji e supozuar",
    "推测流水",
    "推测流水",
  },
  {
    "периодично водно течение",
    "občasný vodní tok",
    "zeitweises Gerinne",
    "διακοπτόμενη υδρορροή",
    "intermittent water flow",
    NULL,
    NULL,
    "curso agua intermitente",
    "rivière, intermittente",
    "corso d'acqua temporaneo",
    "wairere taumutumutu",
    "okresowy ciek wodny",
    "fluxo de água intermitente",
    NULL,
    NULL,
    "непостоянный водоток",
    "občasný vodný tok",
    "rrjedhe uji me force",
    "季节性流水",
    "季节性流水",
  },
  {
    "постоянно водно течение",
    "vodní tok",
    "ständiges Gerinne",
    "μόνιμη υδρορροή",
    "water flow",
    NULL,
    NULL,
    "curso agua",
    "rivière, permanente",
    "corso d'acqua permanente",
    "wairere",
    "ciek wodny",
    "fluxo de água permanente",
    NULL,
    NULL,
    "постоянный водоток",
    "vodný tok",
    "rrjedhe uji e perhershme",
    "常流水",
    "常流水",
  },
  {
    "въздушно течение",
    "průvan",
    "Luftzug",
    "ροή αέρα",
    "air draught",
    NULL,
    NULL,
    "corriente aire",
    "courant d’air",
    "corrente d'aria",
    "tawhiri",
    "przewiew",
    "presença de vento",
    NULL,
    NULL,
    "ток воздуха",
    "prievan",
    "rrymim i ajrit",
    "气流",
    "气流",
  },
  {
    "летен въздушно течение",
    "letní průvan",
    "Luftzug im Sommer",
    "θερινή ροή αέρα",
    "summer air draught",
    NULL,
    NULL,
    NULL,
    "courant d’air d’été",
    "circolazione estiva",
    "tawhiri a raumati",
    "przewiew w lecie",
    NULL,
    NULL,
    NULL,
    "ток воздуха летний",
    "letný prievan",
    "rrymim ajri-veror",
    "暖气流",
    "暖气流",
  },
  {
    "зимен въздушно течение",
    "zimní průvan",
    "Luftzug im Winter",
    "χειμερινή ροή αέρα",
    "winter air draught",
    NULL,
    NULL,
    NULL,
    "courant d’air d’hiver",
    "circolazione invernale",
    "tawhiri a takurua",
    "przewiew w zimie",
    NULL,
    NULL,
    NULL,
    "ток воздуха зимний",
    "zimný prievan",
    "rrymim ajri-dimeror",
    "冷气流",
    "冷气流",
  },
  {
    "н.м. височина",
    "nadmořská výška bodu v chodbě",
    "Höhe über Koordinatenursprung",
    "ύψος",
    "altitude",
    NULL,
    NULL,
    "altura",
    "altitude",
    "quota",
    "teitei, tiketike",
    "wysokość punktu pomiarowego npm",
    "altura",
    NULL,
    NULL,
    "высотная отметка",
    "nadmorská výška bodu v chodbe",
    "lartesia mbidetare",
    "海拔",
    "海拔",
  },
  {
    "анастомоза",
    "anastomóza",
    "Anastomose",
    "αναστόμωση",
    "anastomosis",
    NULL,
    NULL,
    "anastomosis",
    "anastomose",
    "anastomosi",
    "peka hono",
    "anastomoza",
    "anastomose",
    NULL,
    NULL,
    "анастомозис",
    "anastomóza",
    "anastomosa(kuartz)",
    "溶沟",
    "溶沟",
  },
  {
    "закрепване",
    "kotvení",
    "Seilbefestigung",
    "αγκύρωση",
    "anchor",
    NULL,
    NULL,
    "anclaje",
    "ancrage",
    "ancoraggio",
    "punga",
    "punkt asekuracyjny",
    "ancoragem",
    NULL,
    NULL,
    "ИТО",
    "kotvenie",
    "pike-sigurimi",
    "锚点",
    "锚点",
  },
  {
    "арагонит",
    "aragonit",
    "Aragonit",
    "αραγονίτης",
    "aragonite",
    NULL,
    NULL,
    "aragonito",
    "aragonite",
    "aragonite",
    "pākeho tuarua",
    "aragonit",
    "aragonita",
    "aragonita",
    "aragonite",
    "арагонит",
    "aragonit",
    "aragonite",
    "文石",
    "文石",
  },
  {
    "археологическа находка",
    "archeologické nálezy",
    "archäologischer Fund",
    "αρχαιολογικό εύρημα",
    "archaeological material",
    NULL,
    NULL,
    "yacimiento (arq)",
    "matériel archéo",
    "materiale archeologico",
    "taonga o nehe",
    "znaleziska archeologiczne",
    "material arqueológico",
    NULL,
    NULL,
    "археологическая находка",
    "archeologické nálezy",
    "material arkeologjik",
    "考古遗物",
    "考古遗物",
  },
  {
    "основна скала",
    "pevná skála",
    "Deckgebirge",
    "πέτρωμα",
    "bedrock",
    NULL,
    NULL,
    "roca madre",
    "roche",
    "roccia",
    "koiwi a papa",
    "lita skała",
    "rocha encaixante",
    NULL,
    NULL,
    "коренная порода",
    "pevná skala",
    "shtrat shkembi",
    "基岩",
    "基岩",
  },
  {
    "камъни, блокаж",
    "kamenné bloky",
    "Blöcke",
    "ογκόλιθοι",
    "blocks, breakdown",
    NULL,
    NULL,
    "bloques",
    "blocs",
    "massi",
    "pakaru",
    "kamienne bloki",
    "blocos, desmoronamento",
    NULL,
    NULL,
    "глыбы, завал",
    "kamenné bloky",
    "blloqe, shembje",
    "崩塌块石",
    "崩塌块石",
  },
  {
    "затворено от срутище",
    "zavalený konec",
    "Fortsetzung verstürzt",
    "κλείσιμο στοάς λόγο χαλάσματος",
    "breakdown choke",
    NULL,
    NULL,
    "colmatado por derrumbe",
    "trémie",
    "chiude su frana",
    "nati pakaru",
    "koniec zawalony",
    "obstrução por desmoronamento",
    NULL,
    NULL,
    "блокировано обвалом",
    "zavalený koniec",
    "gurre rrjedhes-fund",
    "崩塌堵塞",
    "崩塌堵塞",
  },
  {
    "мост",
    "most",
    "Brücke",
    "γέφυρα",
    "bridge",
    NULL,
    NULL,
    "puente roca",
    "pont",
    "ponte di roccia",
    "piriti",
    "most",
    "ponte",
    NULL,
    NULL,
    "мост",
    "most",
    "ure",
    "桥",
    "桥",
  },
  {
    "лагер",
    "bivak",
    "Biwak",
    "κατασκήνωση",
    "camp",
    NULL,
    NULL,
    "campamento",
    "camp",
    "campo",
    "topuni",
    "biwak",
    "acampamento",
    NULL,
    NULL,
    "ПБЛ",
    "bivak",
    "vend-pushim",
    "营地",
    "营地",
  },
  {
    "пещерен бисер",
    "jeskynní perly",
    "Höhlenperle",
    "μαργαριτάρι των σπηλαίων",
    "cave pearl",
    NULL,
    NULL,
    "perla de caverna",
    "perle des cavernes",
    "pisolite",
    "ana kahurangi",
    "perły jaskiniowe",
    "pérolas",
    "pérolas",
    "pérolas de Gruta",
    "пещерный жемчуг",
    "jaskynné perly",
    "margaritar te shpelles",
    "穴珠",
    "穴珠",
  },
  {
    "глина",
    "bahno",
    "Lehm",
    "άργιλος",
    "clay",
    NULL,
    NULL,
    "arcilla",
    "argile",
    "argilla",
    "oneuku",
    "glina",
    "lama",
    NULL,
    NULL,
    "глина",
    "íl",
    "argjil",
    "粘土",
    "粘土",
  },
  {
    NULL,
    NULL,
    "Fortsetzung verlehmt",
    NULL,
    "clay choke",
    NULL,
    NULL,
    NULL,
    NULL,
    "chiude su riempimento",
    "uku pari",
    "koniec zamknięty gliną",
    NULL,
    NULL,
    NULL,
    NULL,
    "koniec uzavretý ílom",
    NULL,
    "粘土堵赛",
    "粘土堵赛",
  },
  {
    NULL,
    NULL,
    "Lehmbäumchen",
    NULL,
    "clay tree",
    NULL,
    NULL,
    NULL,
    NULL,
    "pini d'argilla",
    "rakau oneuku",
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    "粘土层",
    "粘土层",
  },
  {
    "възможно продължение",
    "možné pokračování",
    "Fortsetzung",
    "πιθανή συνέχεια",
    "possible continuation",
    NULL,
    NULL,
    "continuación",
    "suite possible",
    "possibile prosecuzione",
    "roanga taea",
    "możliwa kontynuacja",
    "possível continuação",
    NULL,
    NULL,
    "возможное продолжение",
    "možné pokračovanie",
    "vazhdim I mundshem",
    "可能延伸洞道",
    "可能延伸洞道",
  },
  {
    "кристал",
    "krystal",
    "Kristall",
    "κρύσταλλο",
    "crystal",
    NULL,
    NULL,
    "cristal",
    "cristaux",
    "cristallo",
    "kohatu piata",
    "kryształ",
    "cristal",
    NULL,
    NULL,
    "кристаллы",
    "kryštál",
    "kristale",
    "晶花",
    "晶花",
  },
  {
    "драперия",
    "sintrové záclony",
    "Sinterfahne",
    "κουρτίνα",
    "curtain",
    NULL,
    NULL,
    "cortina",
    "rideau",
    "cortina",
    "araia",
    "draperie naciekowe",
    "cortina",
    NULL,
    NULL,
    "натечный занавес",
    "sintrové záclony",
    "perde",
    "石幕",
    "石幕",
  },
  {
    "дата на наблюдението",
    "datum pozorování",
    "Datum",
    "ημερομηνία",
    "date of observation",
    NULL,
    NULL,
    "fecha",
    "date",
    "data d'osservazione",
    "rā o te titiro",
    "data obserwacji",
    "data de observação",
    NULL,
    NULL,
    "дата наблюдения",
    "dátum pozorovania",
    "data e vrojtimit",
    "观测日期",
    "观测日期",
  },
  {
    "чакъл",
    "štěrk",
    "Schutt",
    "χαλάσματα",
    "debris",
    NULL,
    NULL,
    "derrubios",
    "débris",
    "detriti",
    "otaota",
    "żwir",
    "escombros",
    NULL,
    NULL,
    "щебень",
    "sutina",
    "mbetje-mbeturina",
    "碎屑堆积",
    "碎屑堆积",
  },
  {
    "изкоп",
    "sonda",
    "Grabung",
    "διάνοιξη",
    "dig",
    NULL,
    NULL,
    NULL,
    "désobstruction",
    "disostruzione",
    "kari",
    "wykop",
    NULL,
    NULL,
    NULL,
    NULL,
    "sonda",
    "mihje",
    NULL,
    NULL,
  },
  {
    "размери на галерията",
    "rozměry",
    "Ausdehnung",
    "διαστάσεις",
    "dimensions",
    NULL,
    NULL,
    "dimensiones",
    "proportions",
    "dimensione",
    "rahinga, meiha",
    "rozmiary",
    "dimensões",
    NULL,
    NULL,
    "размеры хода",
    "rozmery",
    "dimenzionet",
    "规模",
    "规模",
  },
  {
    "диск",
    "disk",
    "Diskus",
    "δίσκος",
    "disk",
    NULL,
    NULL,
    "disco",
    "disque",
    "disco",
    "kiwhi",
    "dysk",
    "disco",
    NULL,
    NULL,
    "диск",
    "disk",
    "pllake",
    "石盘",
    "石盘",
  },
  {
    "вход",
    "vchod",
    "Eingang",
    "είσοδος",
    "entrance",
    NULL,
    NULL,
    "boca",
    "entrée",
    "ingresso",
    "ana ngutu",
    "wejście",
    "entrada",
    NULL,
    NULL,
    "вход",
    "vchod",
    "hyrja",
    "洞口",
    "洞口",
  },
  {
    "стационарна стълба",
    "pevný žebřík",
    "feste Leiter",
    "μόνιμη σκάλα",
    "fixed ladder",
    NULL,
    NULL,
    "escala fija",
    "échelle fixe",
    "scala fissa",
    "arawhata",
    "sztywna drabinka",
    "escada fixa",
    NULL,
    NULL,
    "жесткая лестница",
    "fixný rebrík",
    "shkalle fikse",
    "固定梯子",
    "固定梯子",
  },
  {
    "въздушно течение",
    "průvan",
    "Luftzug",
    "ροή αέρα",
    "air draught",
    NULL,
    NULL,
    "corriente aire",
    "courant d’air",
    "corrente d'aria",
    "tawhiri",
    "przewiew",
    "presença de vento",
    NULL,
    NULL,
    "ток воздуха",
    "prievan",
    "rrymim i ajrit",
    "气流",
    "气流",
  },
  {
    NULL,
    NULL,
    NULL,
    NULL,
    "arch",
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    "skalný oblúk",
    NULL,
    NULL,
    NULL,
  },
  {
    "възможно продължение",
    "možné pokračování",
    "Fortsetzung",
    "πιθανή συνέχεια",
    "possible continuation",
    NULL,
    NULL,
    "continuación",
    "suite possible",
    "possibile prosecuzione",
    "roanga taea",
    "możliwa kontynuacja",
    "possível continuação",
    NULL,
    NULL,
    "возможное продолжение",
    "možné pokračovanie",
    "vazhdim I mundshem",
    "可能延伸洞道",
    "可能延伸洞道",
  },
  {
    "изкоп",
    "sonda",
    "Grabung",
    "διάνοιξη",
    "dig",
    NULL,
    NULL,
    NULL,
    "désobstruction",
    "disostruzione",
    "kari",
    "wykop",
    NULL,
    NULL,
    NULL,
    NULL,
    "sonda",
    "mihje",
    NULL,
    NULL,
  },
  {
    NULL,
    "závrt",
    NULL,
    NULL,
    "doline",
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    "závrt",
    NULL,
    NULL,
    NULL,
  },
  {
    "вход",
    "vchod",
    "Eingang",
    "είσοδος",
    "entrance",
    NULL,
    NULL,
    "boca",
    "entrée",
    "ingresso",
    "ana ngutu",
    "wejście",
    "entrada",
    NULL,
    NULL,
    "вход",
    "vchod",
    "hyrja",
    "洞口",
    "洞口",
  },
  {
    "скална площадка",
    "převis",
    "Überhang",
    "προέκταση οροφής",
    "overhang",
    NULL,
    NULL,
    "extraplomo",
    "surplomb",
    "sporgenza",
    "tauwharenga",
    "przewieszka",
    "projeção",
    "projeção",
    "projecção",
    "нависание потолка",
    "previs",
    "varese",
    "倒倾斜",
    "倒倾斜",
  },
  {
    "понор",
    "ponor",
    "Schluckloch",
    "καταβόθρα",
    "sink",
    NULL,
    NULL,
    "sumidero",
    "perte",
    "perdita",
    "tapoko",
    "ponor",
    "sumidouro",
    NULL,
    NULL,
    "сток",
    "ponor",
    "pus",
    "渗水点",
    "渗水点",
  },
  {
    "извор",
    "vývěr",
    "Quelle",
    "πηγή",
    "spring",
    NULL,
    NULL,
    "surgencia",
    "source",
    "sorgente",
    "waipuna",
    "wywierzysko",
    "nascente",
    NULL,
    NULL,
    "исток",
    "výver",
    "burim",
    "泉点",
    "泉点",
  },
  {
    "натек",
    "sintr",
    "flächiger Sinter",
    "σταλαγμιτικό υλικό δαπέδου",
    "flowstone",
    NULL,
    NULL,
    "concreción",
    "concrétions",
    "concrezione",
    "pari kōhatu",
    "nacieki",
    "escorrimento",
    NULL,
    NULL,
    "натек",
    "sinter",
    "gurre-rrjedhes",
    "流石",
    "流石",
  },
  {
    "блокирано от натеци",
    "zasintrovaný konec",
    "Fortsetzung zugesintert",
    "κλείσιμο στοάς λόγο σταλαγμιτικού αποθέματος",
    "flowstone choke",
    NULL,
    NULL,
    "colmatado por concreción",
    "trémie calcifiée",
    "chiude su colata",
    "nati pari kōhatu",
    "koniec zamknięty naciekami",
    "obstrução por escorrimento",
    NULL,
    NULL,
    "блокировано натеками",
    "zasintrený koniec",
    "mbyllje me gurre-rrjedhes",
    "流石堵塞",
    "流石堵塞",
  },
  {
    "карни жлебове",
    "píšťaly",
    "Kolk",
    "αυλάκι διάβρωσης",
    "flute",
    NULL,
    NULL,
    "canaleta",
    "marmites",
    "scanalatura",
    "koauau",
    "marmity",
    "marcas de fluxo",
    NULL,
    NULL,
    "канавки",
    "píšťaly",
    "flauta",
    "溶槽",
    "溶槽",
  },
  {
    "наклон на галерията",
    "sklon chodby",
    "Gefälle",
    "κλίση στοάς",
    "passage gradient",
    NULL,
    NULL,
    "gradiente",
    "pente",
    "scivolo",
    "harapaki putanga",
    "nachylenie korytarza",
    "declividade da galeria",
    NULL,
    NULL,
    "уклон хода",
    "sklon chodby",
    "pjertesia e kalimit",
    "洞道坡度",
    "洞道坡度",
  },
  {
    "гуано",
    "guano",
    "Guano",
    "γκουανό (περιττώματα νυχτερίδων)",
    "guano",
    NULL,
    NULL,
    "guano",
    "guano",
    "guano",
    "tutae",
    "guano",
    "guano",
    NULL,
    NULL,
    "гуано",
    "guáno",
    "jashteqitje e lakuriqeve-guano",
    "粪类堆积",
    "粪类堆积",
  },
  {
    "гипс",
    "sádrovec",
    "Gips",
    "γύψος",
    "gypsum",
    NULL,
    NULL,
    "yeso",
    "gypse",
    "gesso",
    "tote",
    "gips",
    "gipsita",
    NULL,
    NULL,
    "гипс",
    "sádrovec",
    "gjips",
    "石膏",
    "石膏",
  },
  {
    "гипсово цвете",
    "sádrovcový květ",
    "Gipsblume",
    "άνθος γύψου",
    "gypsum flower",
    NULL,
    NULL,
    "flor yeso",
    "fleur de gypse",
    "fiore di gesso",
    "putiputi tote",
    "gipsowy kwiat",
    "flor de gipsita",
    NULL,
    NULL,
    "гипсовые цветы",
    "sádrovcový kvet",
    "lule gjipsi",
    "石膏花",
    "石膏花",
  },
  {
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
  },
  {
    "височина на праг/комин/кладенец",
    "výška stupně/komínu/hloubka propasti",
    "Höhe der Stufe oder des Schlotes oder Tiefe des Schachts",
    "ύψος σκαλοπατιού/καμινάδας ή βάθος πηγαδιού",
    "pit/chimney/step depth/height",
    NULL,
    NULL,
    "altura resalte/chimenea/profundidad pozo",
    "hauteur d’une marche/d’une cheminée/profondeur",
    "altezza",
    "papa tapuae/tumera/teitei rua/hōhonu",
    "wysokość progu/komina/głębokość studni",
    "altura do chão para degrau/chaminé/desnível",
    NULL,
    NULL,
    "высота уступа/трубы/колодца",
    "hĺbka/výška priepasti/stupňa/komína",
    "lartesia e shkalles ne dysheme/oxhaku/thellesia e leshimit",
    "洞底梯坎高/烟囱洞道高/竖洞深度",
    "洞底梯坎高/烟囱洞道高/竖洞深度",
  },
  {
    "Дълбочина на кладенец",
    "hloubka propasti",
    "Tiefe des Schachts",
    "βάθος πηγαδιού",
    "pit depth",
    NULL,
    NULL,
    "profundidad pozo",
    "profondeur",
    "prodondità pozzo",
    "rua hōhonu",
    "głębokosc studni",
    "profundidade do desnível",
    NULL,
    NULL,
    "высота колодца",
    "hĺbka priepasti",
    "thellesia e leshimit",
    "竖直洞道深度",
    "竖直洞道深度",
  },
  {
    "височина на комин",
    "výška komínu",
    "Höhe des Schlotes",
    "ύψος καμινάδας",
    "chimney height",
    NULL,
    NULL,
    "altura chimenea",
    "hauteur d’une cheminée",
    "altezza camino",
    "teitei tumera",
    "wysokość komina",
    "altura da chaminé",
    NULL,
    NULL,
    "высота трубы",
    "výška komína",
    "lartesia e oxhakut",
    "烟囱式洞道高",
    "烟囱式洞道高",
  },
  {
    "височина на ниша в тавана",
    "výška stupně",
    "Höhe der Bodenstufe",
    "ύψος σκαλοπατιού",
    "floor step height",
    NULL,
    NULL,
    "altura resalte",
    "hauteur d’une marche",
    "altezza camino",
    "teitei papa tapuae",
    "wysokość progu",
    "altura do degrau no chão",
    NULL,
    NULL,
    "высота уступа",
    "výška stupňa",
    "lartesia e shkalles se dyshemes",
    "洞底梯坎高",
    "洞底梯坎高",
  },
  {
    "хеликтити",
    "heliktit",
    "Excentrique",
    "ελικτίτης",
    "helictite",
    NULL,
    NULL,
    "excéntrica",
    "excentrique/hélictite",
    "eccentrica",
    "pākeho torotoro",
    "heliktyt",
    "helictite",
    "helictite",
    "excêntrica",
    "геликтиты",
    "heliktit",
    "heliktite",
    "卷曲石",
    "卷曲石",
  },
  {
    "лед",
    "led",
    "Eis",
    "πάγος",
    "ice",
    NULL,
    NULL,
    "hielo",
    "glace",
    "ghiaccio",
    "kōpaka",
    "lód",
    "gelo",
    NULL,
    NULL,
    "лёд",
    "ľad",
    "akull",
    "冰",
    "冰",
  },
  {
    NULL,
    NULL,
    "Eissäule",
    NULL,
    "ice pillar",
    NULL,
    NULL,
    NULL,
    NULL,
    "colonna di ghiaccio",
    "pou Kōpaka",
    "lodowy stalagnat",
    NULL,
    NULL,
    NULL,
    NULL,
    "ľadový stalagnát",
    NULL,
    "冰柱",
    "冰柱",
  },
  {
    NULL,
    NULL,
    "Eisstalaktit",
    NULL,
    "ice stalactite",
    NULL,
    NULL,
    NULL,
    NULL,
    "stalattite di ghiaccio",
    "kōpaka ki te haere ki runga",
    "lodowy stalaktyt",
    NULL,
    NULL,
    NULL,
    NULL,
    "ľadový stalaktit",
    NULL,
    "冰乳",
    "冰乳",
  },
  {
    NULL,
    NULL,
    "Eisstalagmit",
    NULL,
    "ice stalagmite",
    NULL,
    NULL,
    NULL,
    NULL,
    "stalagmite di ghiaccio",
    "kōpaka ki te haere ki raro",
    "lodowy stalagmit",
    NULL,
    NULL,
    NULL,
    NULL,
    "ľadový stalagmit",
    NULL,
    "冰笋",
    "冰笋",
  },
  {
    "кари",
    "škrapy",
    "Karren",
    "κάρρεν - γυμνός καρστικοποιημένος βράχος",
    "karren",
    NULL,
    NULL,
    "lapiaz",
    "lapiez",
    "karren",
    "awaawa",
    "żłobki krasowe",
    "lapiás",
    NULL,
    NULL,
    "карры",
    "škrapy",
    "karreni",
    "溶痕",
    "溶痕",
  },
  {
    "етикет",
    "pojmenování",
    "Beschriftung",
    "περιγραφή",
    "label",
    NULL,
    NULL,
    "etiqueta",
    "libellé",
    "etichetta",
    "ingoa",
    "nazwa",
    "indicação",
    NULL,
    NULL,
    "текстовая метка",
    "pomenovanie",
    "mbishkrim-etiket",
    "标记",
    "标记",
  },
  {
    "хоризонтално стеснение",
    "neprůlezné snížení",
    "Engstelle, zu flach",
    "κλείσιμο στοάς λόγω χαμηλής οροφής",
    "passage end, low",
    NULL,
    NULL,
    "final bajo",
    "passage bas",
    "chiude su laminatoio",
    "putanga pāpaku mutunga",
    "obniżenie nie do przejścia",
    "passagem com final baixo",
    NULL,
    NULL,
    "горизонтальная узость",
    "neprielezné zníženie",
    "kalim I poshtem-fund",
    "低矮洞道尽头",
    "低矮洞道尽头",
  },
  {
    "пещерно мляко",
    "nickamínek",
    "Bergmilch",
    "γάλα σπηλαίου",
    "moonmilk",
    NULL,
    NULL,
    "mondmilch",
    "mondmilch",
    "moonmilk",
    "mirika marama",
    "miękkie nacieki",
    "leite-de-lua",
    NULL,
    NULL,
    "лунное молоко",
    "mäkký sinter",
    "qumesht-hena",
    "月奶石",
    "月奶石",
  },
  {
    "непроходимо снижаване",
    "neprůlezné zúžení",
    "Engstelle, zu schmal",
    "κλείσιμο στοάς λόγω στενώματος",
    "passage end, narrow",
    NULL,
    NULL,
    "final estrecho",
    "passage impénétrable",
    "chiude su strettoia",
    "putanga kuiti mutunga",
    "zwężenie nie do przejścia",
    "passagem com final estreito",
    NULL,
    NULL,
    "вертикальная узость",
    "neprielezné zúženie",
    "kalim I ngushte-fund",
    "狭窄洞道尽头",
    "狭窄洞道尽头",
  },
  {
    "липсва екипировка!",
    "nevystrojené místo",
    "keine Ausrüstung",
    "χωρίς υλικά",
    "no equipment!",
    NULL,
    NULL,
    "sin equipar",
    "pas d’équipement",
    "senza armo",
    "wahi a taonga mahi kore",
    "miejsce bez punktu asekuracyjnego",
    "local sem equipamento",
    NULL,
    NULL,
    "снаряжение отутствует!",
    "nevystrojené miesto",
    "vend pa pajisje",
    "无需装备点",
    "无需装备点",
  },
  {
    "палеонтологична находка",
    "paleontologické nálezy",
    "paläontologischer Fund",
    "παλαιοντολογικό εύρημα",
    "paleo material",
    NULL,
    NULL,
    "yacimiento (pal)",
    "matériel paléo",
    "materiale paleologico",
    "taiao taonga o nehe",
    "znaleziska paleontologiczne",
    "material paleontológico",
    NULL,
    NULL,
    "палео-находка",
    "paleontologické nálezy",
    "paleo-material",
    "原始堆积",
    "原始堆积",
  },
  {
    "височина на галерията",
    "výška chodby",
    "Raumhöhe",
    "ύψος στοάς",
    "passage height",
    NULL,
    NULL,
    "altura galería",
    "hauteur du passage",
    "altezza galleria",
    "ara teitei",
    "wysokość korytarza",
    "altura da galeria",
    NULL,
    NULL,
    "высота хода",
    "výška chodby",
    "lartesia e kalimit",
    "洞道高度",
    "洞道高度",
  },
  {
    "височина над и дълбочина под водата",
    "výška nad i pod hladinou",
    "Raumhöhe gesamt",
    "ύψος και βάθος στοάς πάνω και κάτω από νερό",
    "height above, depth below water",
    NULL,
    NULL,
    "altura y profundidad respecto nivel del mar",
    "hauteur au dessous et au dessus de l’eau",
    "altezza sopra e sotto il livello dell'acqua",
    "karewa ki runga ki raro",
    "wysokość korytarza nad powierzchnią wody i głębokość poniżej poziomu wody",
    "altura acima e profundidade abaixo do nível da água",
    NULL,
    NULL,
    "высота над и глубина ниже уровня воды",
    "výška nad a hĺbka pod hladinou",
    "lartesia mbi dhe nen nivelin e ujit",
    "水面洞高和水体深度",
    "水面洞高和水体深度",
  },
  {
    "дълбочина на галерията под водата",
    "výška chodby pod hladinou",
    "Raumhöhe nach unten",
    "βάθος στοάς κάτω από νερό",
    "depth below water level",
    NULL,
    NULL,
    "profundidad bajo nivel del mar",
    "hauteur en dessous de l’eau",
    "profondità sotto il livello dell'acqua",
    "te hōhunu a karewa ki raro",
    "wysokość korytarza pod powierzchnią wody",
    "profundidade abaixo do nível da água",
    NULL,
    NULL,
    "глубина ниже уровня воды",
    "hĺbka pod hladinou",
    "thellesia nen nivelin e ujit",
    "水体深度",
    "水体深度",
  },
  {
    "височина на галерията над водата",
    "výška chodby nad hladinou",
    "Raumhöhe nach oben",
    "ύψος στοάς πάνω από νερό",
    "height above water level",
    NULL,
    NULL,
    "altura sobre nivel del mar",
    "hauteur au-dessus de l’eau",
    "altezza sopra il livello dell'acqua",
    "te teitei a karewa ki runga",
    "wysokość korytarza nad powierzchnią wody",
    "altura acima do nível da água",
    NULL,
    NULL,
    "высота над уровнем воды",
    "výška nad hladinou",
    "lartesia mbi nivelin e ujit",
    "水面洞高",
    "水面洞高",
  },
  {
    "височина на галерията",
    "výška chodby",
    "Raumhöhe",
    "ύψος στοάς",
    "passage height",
    NULL,
    NULL,
    "altura galería",
    "hauteur du passage",
    "altezza galleria",
    "ara teitei",
    "wysokość korytarza",
    "altura da galeria",
    NULL,
    NULL,
    "высота хода",
    "výška chodby",
    "lartesia e kalimit-e pashenuar",
    "洞道高度:无标记的点",
    "洞道高度:无标记的点",
  },
  {
    "камъчета",
    "valouny",
    "Kies",
    "χαλίκια",
    "pebbles",
    NULL,
    NULL,
    "cantos rodados",
    "galets",
    "ciotoli",
    "nga kōhatu iti",
    "okręglaki",
    "seixos",
    NULL,
    NULL,
    "галька",
    "okruhliaky",
    "gurralece",
    "卵石",
    "卵石",
  },
  {
    "сталактон",
    "stalagnát",
    "Säule",
    "κολόνα",
    "pillar",
    NULL,
    NULL,
    "pilar",
    "pillier",
    "colonna",
    "pou",
    "stalagnat",
    "coluna",
    NULL,
    NULL,
    "колонна",
    "stalagnát",
    "shtylle",
    "石柱",
    "石柱",
  },
  {
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
  },
  {
    "коралити",
    "pizolity",
    "Blumenkohlsinter",
    "μανιτάρια από σταλαγμιτικό υλικό",
    "popcorn",
    NULL,
    NULL,
    "coliflor",
    "choux-fleur",
    "cavolfiore",
    "kanga pāhuuhuu",
    "pizolity",
    "couve-flor",
    NULL,
    NULL,
    "коралиты",
    "pizolity",
    "palagaqa-kokorroshka",
    "石珊瑚",
    "石珊瑚",
  },
  {
    "насип",
    "náplav",
    "schwimmendes Kalkhäutchen",
    "σταλαγμιτικό υλικό που επιπλέει",
    "calcite raft",
    NULL,
    NULL,
    "calcita flotante",
    "calcite flottante",
    "calcite flottante",
    "mōkihi o kōhatu hōhonu",
    "nanios",
    "jangada",
    NULL,
    NULL,
    "высыпка",
    "náplav",
    "trap-skele",
    "石筏",
    "石筏",
  },
  {
    "насипен конус",
    "náplavový kužel",
    "schwimmendes Kalkhäutchen",
    "σταλαγμιτικός κώνος που επιπλέει",
    "raft cone",
    NULL,
    NULL,
    "conos",
    "cone",
    "calcite flottante",
    "korere a mōkihi kōhatu hōhonu",
    "nanios",
    "cone de jangada",
    NULL,
    NULL,
    "высыпной конус",
    "náplavový kužeľ",
    "rrjedhe uji konike",
    "钙膜晶锥",
    "钙膜晶锥",
  },
  {
    "забележка",
    "poznámka",
    "Bemerkung",
    "σχόλιο",
    "remark",
    NULL,
    NULL,
    "nota",
    "remarque",
    "nota",
    "korero",
    "uwaga",
    "anotação",
    NULL,
    NULL,
    "заметка",
    "poznámka",
    "shenim",
    "备注",
    "备注",
  },
  {
    "сухо синтрово езеро",
    "sintrová hrázka",
    "Sinterbarriere",
    "γκουρ (λιθωματικό φράγμα)",
    "rimstone dam",
    NULL,
    NULL,
    "gour-presa",
    "gours",
    "gour",
    "kōhatu matatara",
    "naciekowa przegroda",
    "travertino",
    NULL,
    NULL,
    "гуры без воды",
    "sintrová hrádza",
    "penda guri",
    "边石坝",
    "边石坝",
  },
  {
    "синтрово езеро",
    "sintrové jezírko",
    "Sinterbecken",
    "γκουρ (λιθωματική λεκάνη)",
    "rimstone pool",
    NULL,
    NULL,
    "gour-poza",
    "gour",
    "vasca",
    "kōhatu kopua wai",
    "jeziorko naciekowe",
    "lago travertino",
    NULL,
    NULL,
    "гуры с водой",
    "sintrové jazierko",
    "vaska uji",
    "边石潭",
    "边石潭",
  },
  {
    "корени",
    "kořeny",
    "Holzreste",
    "ρίζες",
    "root",
    NULL,
    NULL,
    "raíz",
    "racine",
    "radice",
    "pakiaka",
    "korzenie",
    "raiz",
    NULL,
    NULL,
    "корни растений",
    "korene",
    "rrenje",
    "树根",
    "树根",
  },
  {
    "въже",
    "lano",
    "Seil",
    "σχοινί",
    "rope",
    NULL,
    NULL,
    "cuerda",
    "corde",
    "corda",
    "taura",
    "lina",
    "corda",
    NULL,
    NULL,
    "линейная опора",
    "lano",
    "litar",
    "绳子",
    "绳子",
  },
  {
    "пещерна стълба",
    "lanový žebřík",
    "Drahtseilleiter",
    "ανεμόσκαλα",
    "rope ladder",
    NULL,
    NULL,
    "escala",
    "échelle de corde",
    "scala di corda",
    "arawhata taura",
    "drabinka linowa",
    "escada de corda",
    NULL,
    NULL,
    "гибкая лестница",
    "lanový rebrík",
    "shkalle litari",
    "绳梯",
    "绳梯",
  },
  {
    "пясък",
    "písek",
    "Sand",
    "άμμος",
    "sand",
    NULL,
    NULL,
    "arena",
    "sable",
    "sabbia",
    "onepū",
    "piasek",
    "areia",
    NULL,
    NULL,
    "песок",
    "piesok",
    "rane",
    "砂",
    "砂",
  },
  {
    "фасетки",
    "erozní útvary",
    "Fließfacette",
    "σκάλοπ (κενά διάβρωσης)",
    "scallop",
    NULL,
    NULL,
    "cavitaciones",
    "vagues d’érosion (coups de gouge)",
    "scallop",
    "anatipa",
    "formy erozyjne",
    "marcas de fluxo",
    NULL,
    NULL,
    "фасетки",
    "lastúrovité jamky",
    "guacat",
    "贝窝",
    "贝窝",
  },
  {
    "място на сечение",
    "příčný řez",
    "Schnitt",
    "τομή",
    "section",
    NULL,
    NULL,
    "sección",
    "section",
    "sezione",
    "roherohenga",
    "przkrój",
    "seção",
    "seção",
    "secção",
    "сечение",
    "priečny rez",
    "pike-ndarje",
    "断面",
    "断面",
  },
  {
    "понор",
    "ponor",
    "Schluckloch",
    "καταβόθρα",
    "sink",
    NULL,
    NULL,
    "sumidero",
    "perte",
    "perdita",
    "tapoko",
    "ponor",
    "sumidouro",
    NULL,
    NULL,
    "сток",
    "ponor",
    "pus",
    "渗水点",
    "渗水点",
  },
  {
    "сняг",
    "sníh",
    "Schnee",
    "χιώνι",
    "snow",
    NULL,
    NULL,
    "nieve",
    "neige",
    "neve",
    "huka",
    "śnieg",
    "neve",
    NULL,
    NULL,
    "снег",
    "sneh",
    "bore",
    "雪",
    "雪",
  },
  {
    "цевичен сталактит",
    "brčka",
    "Makkaroni",
    "μακαρόνια",
    "soda straw",
    NULL,
    NULL,
    "fistulosa",
    "fistuleuse",
    "tubolare",
    "pū ngote",
    "nacieki",
    "canudos",
    NULL,
    "tubulares",
    "сталактиты-соломины",
    "brčká",
    "shkopinje sode",
    "鹅管",
    "鹅管",
  },
  {
    "извор",
    "vývěr",
    "Quelle",
    "πηγή",
    "spring",
    NULL,
    NULL,
    "surgencia",
    "source",
    "sorgente",
    "waipuna",
    "wywierzysko",
    "nascente",
    NULL,
    NULL,
    "исток",
    "výver",
    "burim",
    "泉点",
    "泉点",
  },
  {
    "сталактит",
    "stalaktit",
    "Stalaktit",
    "σταλακτίτης",
    "stalactite",
    NULL,
    NULL,
    "estalactita",
    "stalactite",
    "stalattite",
    "kōhatu ki te haere ki runga",
    "stalaktyt",
    "estalactite",
    NULL,
    NULL,
    "сталактит",
    "stalaktit",
    "stalaktit",
    "石钟乳",
    "石钟乳",
  },
  {
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
  },
  {
    "сталагмит",
    "stalagmit",
    "Stalagmit",
    "σταλαγμίτης",
    "stalagmite",
    NULL,
    NULL,
    "estalagmita",
    "stalagmite",
    "stalagmite",
    "kōhatu ki te haere ki raro",
    "stalagmit",
    "estalagmite",
    NULL,
    NULL,
    "сталагмит",
    "stalagmit",
    "stalagmit",
    "石笋",
    "石笋",
  },
  {
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
  },
  {
    "реперна точка",
    "měřičský bod",
    "Messpunkt",
    "σημείο χαρτογράφησης",
    "survey station",
    NULL,
    NULL,
    "estación",
    "station topo",
    "caposaldo",
    "kaimataara",
    "punkt pomiarowy",
    "base",
    NULL,
    NULL,
    "пикет",
    "meračský bod",
    "stacioni I matjes",
    "测点",
    "测点",
  },
  {
    "име на реперна точка",
    "číslo měřičského bodu",
    "Messpunktname",
    "όνομα σημείου χαρτογράφησης",
    "survey station name",
    NULL,
    NULL,
    "nombre estacion",
    "station topo, nom",
    "node del caposaldo",
    "kaimatara ingoa",
    "numer punktu pomiarowego",
    "nome de base",
    NULL,
    NULL,
    "номер пикета",
    "číslo meračského bodu",
    "emri I stacionit-mates",
    "测点名称",
    "测点名称",
  },
  {
    "реперна точка (стабилизирана)",
    "měřičský bod (stabilizovaný)",
    "dauerhafter Messpunkt",
    "μόνιμο σημείο χαρτογράφησης",
    "fixed survey station",
    NULL,
    NULL,
    "estación (fija)",
    "station topo, fixe",
    "caposaldo fisso",
    "kaimataara whakakōhatu",
    "punkt pomiarowy (zastabilizowany)",
    "base fixa",
    NULL,
    NULL,
    "репер",
    "meračský bod (stabilizovaný)",
    "stacion mates I palevizshem",
    "固定测点",
    "固定测点",
  },
  {
    "реперна точка (естествена)",
    "měřičský bod (přírodní)",
    "natürlicher Messpunkt",
    "σημείο χαρτογράφησης (φυσικό)",
    "natural survey station",
    NULL,
    NULL,
    "estación (natural)",
    "station topo, naturelle",
    "caposaldo naturale",
    "kaimataara a papa",
    "punkt pomiarowy naturalny",
    "base natural",
    NULL,
    NULL,
    "естественная точка привязки",
    "meračský bod (prírodný)",
    "stacion mates natyral",
    "天然测点",
    "天然测点",
  },
  {
    "реперна точка (боядисана)",
    "měřičský bod (zabarvený)",
    "farbig markierter Messpunkt",
    "σημείο χαρτογράφησης (βαμμένο)",
    "painted survey station",
    NULL,
    NULL,
    "estación (pintada)",
    "station topo, peinte",
    "caposaldo verniciato",
    "kaimataara tohi",
    "punkt pomiarowy (oznaczony farbą)",
    "base pintada",
    NULL,
    NULL,
    "нарисованный пикет",
    "meračský bod (zafarbený)",
    "stacion mates I ngjyrosur",
    "人工测点",
    "人工测点",
  },
  {
    "временна реперна точка",
    "měřičský bod (nestabilizovaný)",
    "unmarkierter Messpunkt",
    "προσωρινό σημείο χαρτογράφησης",
    "temporary survey station",
    NULL,
    NULL,
    "estación topográfica",
    "station topo temporaire",
    "caposaldo termporaneo",
    "kaimataara mo te wā",
    "punkt pomiarowy (niezastabilizowany)",
    "base temporária",
    NULL,
    NULL,
    "временный пикет",
    "meračský bod (nestabilizovaný)",
    "stacion mates I perkohshem",
    "临时测点",
    "临时测点",
  },
  {
    "стъпала",
    "schody",
    "Stufen",
    "σκαλοπάτια",
    "steps",
    NULL,
    NULL,
    "escalones",
    "marches",
    "scalini",
    "nga tapuae",
    "schody",
    "degraus",
    NULL,
    NULL,
    "ступени",
    "schody",
    "shkalle",
    "梯坎",
    "梯坎",
  },
  {
    "траверс",
    "traverz",
    "Querung",
    "τραβέρσα",
    "traverse",
    NULL,
    NULL,
    "pasamanos",
    "traversée",
    "traverso",
    "hikoi a tupari",
    "trawers",
    "travessia",
    NULL,
    NULL,
    "троллей",
    "traverz",
    "kalim anesore",
    "横越",
    "横越",
  },
  {
    "останки от растителност",
    "zbytky rostlin",
    "Pflanzenreste",
    "φυτικά κατάλοιπα",
    "vegetable debris",
    NULL,
    NULL,
    "detritus vegetales",
    "débris végétaux",
    "detriti vegetali",
    "otaota a hua whenua",
    "szczątki roślinne",
    "restos vegetais",
    NULL,
    NULL,
    "останки растительности",
    "zvyšky rastlín",
    "mbetje perimesh",
    "生物碎屑堆积",
    "生物碎屑堆积",
  },
  {
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
  },
  {
    "височинна отметка на стената",
    "nadmořská výška bodu na stěně",
    "Höhe über Koordinatenursprung",
    "ύψος τοίχου",
    "altitude",
    NULL,
    NULL,
    "altura pared",
    "altitude",
    "altezza",
    "teitei, tiketike",
    "wysokość punktu pomiarowego npm",
    "altura",
    NULL,
    NULL,
    "высотная отметка стены",
    "nadmorská výška bodu na stene",
    "lartesia mbidetare e murit",
    "海拔",
    "海拔",
  },
  {
    "повлек",
    "vápencový povlak",
    "Wandsinter",
    "ασβεστίτης τοιχώματος",
    "wall calcite",
    NULL,
    NULL,
    "calcita",
    "mur, calcite",
    "calcite",
    "tāra a nga roimata a pakeho",
    "wapienna powłoka",
    "parede de calcita",
    "parede de calcita",
    "parede de calcite",
    "настенный кальцит",
    "vápencový povlak",
    "kalcit-muri",
    "洞壁石花",
    "洞壁石花",
  },
  {
    "вода",
    "voda",
    "Wasser",
    "νερό",
    "water",
    NULL,
    NULL,
    "agua",
    "eau",
    "acqua",
    "wai",
    "woda",
    "água",
    NULL,
    NULL,
    "вода",
    "voda",
    "uje",
    "水",
    "水",
  },
  {
    "водно течение",
    "vodní tok",
    "Gerinne",
    "υδρορροή",
    "water flow",
    NULL,
    NULL,
    "curso agua",
    "rivière",
    "corso d'acqua",
    "wairere",
    "ciek wodny",
    "fluxo de água",
    NULL,
    NULL,
    "водоток",
    "vodný tok",
    "rrjedhe uji",
    "流水点",
    "流水点",
  },
  {
    "непостоянно водно течение",
    "občasný vodní tok",
    "zeitweises Gerinne",
    "διακοπτόμενη υδρορροή",
    "intermittent water flow",
    NULL,
    NULL,
    "curso agua intermitente",
    "rivière, intermittente",
    "corso d'acqua temporaneo",
    "wairere taumutumutu",
    "okresowy ciek wodny",
    "fluxo de água intermitente",
    NULL,
    NULL,
    "непостоянный водоток",
    "občasný vodný tok",
    "rrjedhe uji me force",
    "季节性流水",
    "季节性流水",
  },
  {
    "палео речно легло",
    "paleořečiště",
    "ehemaliges Gerinne",
    "παλαιουδρορροή",
    "paleo water flow (scallops)",
    NULL,
    NULL,
    "paleocurso agua",
    "rivière fossile",
    "paleocorso d'acqua",
    "wairere nehera",
    "stary ciek wodny",
    "paleo-fluxo de água",
    NULL,
    NULL,
    "палео-поток",
    "paleoriečisko",
    "rrjedhe uji e vjeter",
    "古水流",
    "古水流",
  },
  {
    "постоянно водно течение",
    "vodní tok",
    "ständiges Gerinne",
    "μόνιμη υδρορροή",
    "water flow",
    NULL,
    NULL,
    "curso agua",
    "rivière, permanente",
    "corso d'acqua permanente",
    "wairere",
    "ciek wodny",
    "fluxo de água permanente",
    NULL,
    NULL,
    "постоянный водоток",
    "vodný tok",
    "rrjedhe uji e perhershme",
    "常流水",
    "常流水",
  },
  {
    "Гл. картировач",
    "Kreslil",
    "Zeichnung",
    "Σκαρίφημα",
    "Drawn by",
    NULL,
    NULL,
    "Cartografía",
    "Dessinateur",
    "Cartografia",
    "Kaituhi",
    "rysował",
    "Desenhada por",
    NULL,
    NULL,
    "Камеральная обработка",
    "Kreslil",
    "vizatuar nga",
    "绘图",
    "绘图",
  },
  {
    "Гл. картировачи",
    "Kreslili",
    "Zeichnung",
    "Σκαρίφημα",
    "Drawn by",
    NULL,
    NULL,
    "Cartografía",
    "Dessinateurs",
    "Cartografia",
    "Kaituhi",
    "rysowali",
    "Desenhadas por",
    NULL,
    NULL,
    "Камеральная обработка",
    "Kreslili",
    "vizatuar nga",
    "绘图",
    "绘图",
  },
  {
    "Денивелация",
    "Převýšení",
    "Niveaudifferenz",
    "Βάθος",
    "Depth",
    NULL,
    NULL,
    "Desnivel",
    "Profondeur",
    "Profondità",
    "Hōhonu a ana, Rētōtanga",
    "przewyższenie",
    "Desnível",
    NULL,
    NULL,
    "Глубина",
    "Prevýšenie",
    "thellesia",
    "洞道深度",
    "洞道深度",
  },
  {
    "Дължина",
    "Délka",
    "Gesamtlänge",
    "Μήκος",
    "Length",
    NULL,
    NULL,
    "Desarrollo",
    "Longueur",
    "Sviluppo",
    "Roa a ana",
    "długość",
    "Extensão",
    NULL,
    NULL,
    "Длина",
    "Dĺžka",
    "gjatesia",
    "洞道长度",
    "洞道长度",
  },
  {
    "Височинна скала",
    "Nadmořské výšky",
    "Höhe des Titelfeldes",
    "Υψομετρικά",
    "Altitudes",
    NULL,
    NULL,
    "color (altitud)",
    "Altitudes",
    "Profondità",
    "Teitei, Tiketike",
    "wysokości npm",
    "Altitudes",
    NULL,
    NULL,
    "Высотная шкала",
    "Nadmorské výšky",
    "titulli ngjyra-permbajtja-lartesia mbidetare",
    "海拔",
    "海拔",
  },
  {
    "Карти",
    "Mapy",
    "Karten",
    "Χάρτες",
    "Maps",
    NULL,
    NULL,
    "color (mapa)",
    "Cartes",
    "Mappa",
    "Mahere whenua",
    "mapy",
    "Mapas",
    NULL,
    NULL,
    "Карты",
    "Mapy",
    "hartat",
    "地图",
    "地图",
  },
  {
    "Изследване",
    "Objevil",
    "Entdeckung",
    "Εξερευνητής",
    "Explored by",
    NULL,
    NULL,
    "Exploración",
    "Explorateur",
    "Esplorazione",
    "Kaipokai whenua",
    "odkrył",
    "Explorada por",
    NULL,
    NULL,
    "Исследование",
    "Objavil",
    "hulumtuar nga",
    "探测",
    "探测",
  },
  {
    "Изследване",
    "Objevili",
    "Entdeckung",
    "Εξερευνητές",
    "Explored by",
    NULL,
    NULL,
    "Exploración",
    "Explorateurs",
    "Esplorazione",
    "Kaipokai whenua",
    "odkryli",
    "Exploradas por",
    NULL,
    NULL,
    "Исследование",
    "Objavili",
    "hulumtuar nga",
    "探测",
    "探测",
  },
  {
    "Легенда",
    "Legenda",
    "Legende",
    "Τίτλος",
    "Legend",
    NULL,
    NULL,
    "Leyenda",
    "Légende",
    "Legenda",
    "Kaiwhakaatu",
    "legenda",
    "Legenda",
    NULL,
    NULL,
    "Условные обозначения",
    "Legenda",
    "permbajtja",
    "图例",
    "图例",
  },
  {
    "Карта",
    NULL,
    NULL,
    NULL,
    "Map",
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
  },
  {
    "Модел",
    NULL,
    NULL,
    NULL,
    "Model",
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
  },
  {
    "Изглед от горе",
    "[Náhled horních vrstev]",
    "Vorschau oben",
    "[προεπισκόπηση πάνω]",
    "[Preview above]",
    NULL,
    NULL,
    "Vista previa superior",
    "[Prévisualisation au-dessus]",
    "Anteprima sopra",
    "Tuhi a ana ki runga",
    "widok z góry",
    "[Visualização acima]",
    NULL,
    NULL,
    "[Вид выше]",
    "[Náhľad horných vrstiev]",
    "parashiqimi lart",
    "往上预览",
    "往上预览",
  },
  {
    "Изглед от долу",
    "[Náhled dolních vrstev]",
    "Vorschau unten",
    "[προεπισκόπηση κάτω]",
    "[Preview below]",
    NULL,
    NULL,
    "Vista previa inferior",
    "[Prévisualisation au-dessous]",
    "Anteprima sotto",
    "Tuhi a ana ki raro",
    "widok z dołu",
    "[Visualização abaixo]",
    NULL,
    NULL,
    "[Вид ниже]",
    "[Náhľad spodných vrstiev]",
    "parashiqimi perfundi",
    "往下预览",
    "往下预览",
  },
  {
    "Карта на повърхността",
    "[Povrchová mapa]",
    "Erdoberfläche",
    "[χάρτης επιφάνειας]",
    "[Surface Image]",
    NULL,
    NULL,
    "Mapa superficie",
    "[Carte extérieure]",
    "Mappa superficie",
    "Konohi o te whenua",
    "mapa powierzchni",
    "[Mapa de superfície]",
    NULL,
    NULL,
    "[Карта поверхности]",
    "[Povrchová mapa]",
    "harta e siperfaqes",
    "外观图",
    "外观图",
  },
  {
    "Картирал",
    "Měřil",
    "Vermessung",
    "Χαρτογραφήθηκε από τον",
    "Surveyed by",
    NULL,
    NULL,
    "Topografía",
    "Topographe",
    "Topografia",
    "Kairūri",
    "mierzył",
    "Topografada por",
    NULL,
    NULL,
    "Съемка",
    "Zameral",
    "matur nga",
    "测量",
    "测量",
  },
  {
    "Картирали",
    "Měřili",
    "Vermessung",
    "Χαρτογραφήθηκε από τους",
    "Surveyed by",
    NULL,
    NULL,
    "Espeleometría",
    "Topographes",
    "Topografia",
    "Kairūri",
    "pomierzyli",
    "Topografadas por",
    NULL,
    NULL,
    "Съемка",
    "Zamerali",
    "matur nga",
    "测量",
    "测量",
  },
  {
    "футове",
    "ft",
    "ft",
    "πόδια",
    "ft",
    NULL,
    NULL,
    "ft",
    "ft",
    "ft",
    "whīti",
    "ft (stopy)",
    "pés",
    NULL,
    NULL,
    "футов",
    "ft",
    "njesia matese-kembe",
    "英尺",
    "英尺",
  },
  {
    "м",
    "m",
    "m",
    "μ",
    "m",
    NULL,
    NULL,
    "m",
    "m",
    "m",
    "mehua",
    "m (metry)",
    "m",
    NULL,
    NULL,
    "м",
    "m",
    "njesia matese-metri",
    "米",
    "米",
  },
};

 
 
