/**
 * @file thlangdata.cxx
 * Therion language translations module.
 *
 * THIS FILE IS GENERATED AUTOMATICALLY, DO NOT MODIFY IT !!!
 */

 
typedef char * thlang_pchar;


static const thstok thtt_lang [] = {
  {"cz", THLANG_CZ},
  {"en", THLANG_EN},
  {"en_UK", THLANG_EN_UK},
  {"en_US", THLANG_EN_US},
  {"sk", THLANG_SK},
  {NULL, THLANG_UNKNOWN},
};



static const thlang_pchar thlang__cxxids []  = {
  "THLANG_CZ",
  "THLANG_EN",
  "THLANG_EN_UK",
  "THLANG_EN_US",
  "THLANG_SK",
};



static const int thlang__alternatives [] = {
  THLANG_UNKNOWN,
  THLANG_UNKNOWN,
  THLANG_EN,
  THLANG_EN,
  THLANG_UNKNOWN,
};



static const thstok thtt__texts [120] = {
  {"area debris",0},
  {"area sand",1},
  {"area sump",2},
  {"area water",3},
  {"line arrow",4},
  {"line border:temporary",5},
  {"line border:visible",6},
  {"line ceiling-step",7},
  {"line chimney",8},
  {"line contour",9},
  {"line floor-step",10},
  {"line flowstone",11},
  {"line gradient",12},
  {"line overhang",13},
  {"line pit",14},
  {"line rock-border",15},
  {"line rock-edge",16},
  {"line section",17},
  {"line slope",18},
  {"line survey",19},
  {"line wall:bedrock",20},
  {"line wall:blocks",21},
  {"line wall:clay",22},
  {"line wall:debris",23},
  {"line wall:ice",24},
  {"line wall:pebbles",25},
  {"line wall:presumed",26},
  {"line wall:sand",27},
  {"line wall:underlying",28},
  {"line wall:unsurveyed",29},
  {"line waterflow:conjectural",30},
  {"line waterflow:intermittent",31},
  {"line waterflow:permanent",32},
  {"point air-draught",33},
  {"point altitude",34},
  {"point anastomosis",35},
  {"point anchor",36},
  {"point aragonite",37},
  {"point archeo-material",38},
  {"point bedrock",39},
  {"point blocks",40},
  {"point breakdown-choke",41},
  {"point bridge",42},
  {"point camp",43},
  {"point cave-pearl",44},
  {"point clay",45},
  {"point continuation",46},
  {"point crystal",47},
  {"point curtain",48},
  {"point date",49},
  {"point debris",50},
  {"point disk",51},
  {"point entrance",52},
  {"point fixed-ladder",53},
  {"point flowstone",54},
  {"point flowstone-choke",55},
  {"point flute",56},
  {"point gradient",57},
  {"point guano",58},
  {"point gypsum",59},
  {"point gypsum-flower",60},
  {"point height:negative",61},
  {"point height:positive",62},
  {"point height:unsigned",63},
  {"point helictite",64},
  {"point ice",65},
  {"point karren",66},
  {"point low-end",67},
  {"point moonmilk",68},
  {"point narrow-end",69},
  {"point no-equipment",70},
  {"point paleo-material",71},
  {"point passage-height:both",72},
  {"point passage-height:negative",73},
  {"point passage-height:positive",74},
  {"point passage-height:unsigned",75},
  {"point pebbles",76},
  {"point pillar",77},
  {"point popcorn",78},
  {"point raft",79},
  {"point raft-cone",80},
  {"point rimstone-dam",81},
  {"point rimstone-pool",82},
  {"point root",83},
  {"point rope",84},
  {"point rope-ladder",85},
  {"point sand",86},
  {"point scallop",87},
  {"point sink",88},
  {"point soda-straw",89},
  {"point spring",90},
  {"point stalactite",91},
  {"point stalagmite",92},
  {"point station-name",93},
  {"point station:fixed",94},
  {"point station:natural",95},
  {"point station:painted",96},
  {"point station:temporary",97},
  {"point steps",98},
  {"point traverse",99},
  {"point vegetable-debris",100},
  {"point wall-altitude",101},
  {"point wall-calcite",102},
  {"point water",103},
  {"point waterflow:intermittent",104},
  {"point waterflow:paleo",105},
  {"point waterflow:permanent",106},
  {"title carto",107},
  {"title carto (plural)",108},
  {"title cave depth",109},
  {"title cave length",110},
  {"title explo",111},
  {"title explo (plural)",112},
  {"title legend",113},
  {"title preview above",114},
  {"title preview below",115},
  {"title topo",116},
  {"title topo (plural)",117},
  {"units m",118},
  {NULL, -1},
};



static const thlang_pchar thlang__translations [119][5] = {
  {
    "štěrk",
    "debris",
    NULL,
    NULL,
    "štrk",
  },
  {
    "písek",
    "sand",
    NULL,
    NULL,
    "piesok",
  },
  {
    "sifon",
    "sump",
    NULL,
    NULL,
    "zatopená plocha (sifón)",
  },
  {
    "vodní plocha",
    "water",
    NULL,
    NULL,
    "vodná plocha",
  },
  {
    "pomocná šipka",
    "arrow",
    NULL,
    NULL,
    "pomocná šípka",
  },
  {
    "nestálé ohraničení",
    "temporary border",
    NULL,
    NULL,
    "nestále ohraničenie",
  },
  {
    "ohraničení",
    "border",
    NULL,
    NULL,
    "ohraničenie",
  },
  {
    "změna výšky stropu",
    "step on the ceiling",
    NULL,
    NULL,
    "zmena výšky stropu",
  },
  {
    "komín",
    "chimney",
    NULL,
    NULL,
    "komín",
  },
  {
    "vrstevnice",
    "contour",
    NULL,
    NULL,
    "vrstevnica",
  },
  {
    "stupeň",
    "floor step",
    NULL,
    NULL,
    "stupeň",
  },
  {
    "sintrové náteky",
    "flowstone",
    NULL,
    NULL,
    "sintrové náteky",
  },
  {
    "sklon chodby",
    "passage gradient",
    NULL,
    NULL,
    "sklon chodby",
  },
  {
    "převis",
    "overhang",
    NULL,
    NULL,
    "previs",
  },
  {
    "propast",
    "pitch",
    "pitch",
    "pit",
    "priepasť",
  },
  {
    "kameny",
    "rock border",
    NULL,
    NULL,
    "ohraničenie kameňov",
  },
  {
    "hrany kamenů",
    "rock edges",
    NULL,
    NULL,
    "hrany kameňov",
  },
  {
    "příčný řez",
    "cross-section",
    NULL,
    NULL,
    "priečny rez",
  },
  {
    "svah",
    "slope",
    NULL,
    NULL,
    "šikmá plocha",
  },
  {
    "polygonový tah",
    "survey lines",
    NULL,
    NULL,
    "polygónový ťah",
  },
  {
    "stěna",
    "wall",
    NULL,
    NULL,
    "stena",
  },
  {
    "zával",
    "breakdown",
    NULL,
    NULL,
    "stena tvorená závalom",
  },
  {
    "jíl",
    "clay",
    NULL,
    NULL,
    "stena tvorená bahnom",
  },
  {
    "štěrk",
    "debris",
    NULL,
    NULL,
    "stena tvorená štrkom",
  },
  {
    "led",
    "ice",
    NULL,
    NULL,
    "stena tvorená ľadom",
  },
  {
    "valouny",
    "pebbles",
    NULL,
    NULL,
    "stena tvorená okruhliakmi",
  },
  {
    "předpokládaná stěna",
    "presumed wall",
    NULL,
    NULL,
    "predpokladaná stena",
  },
  {
    "písek",
    "sand",
    NULL,
    NULL,
    "stena tvorená pieskom",
  },
  {
    "stěna nižší úrovně",
    "underlying wall",
    NULL,
    NULL,
    "stena nižšej úrovne",
  },
  {
    "nezaměřená stěna",
    "unsurveyed wall",
    NULL,
    NULL,
    "nezameraná stena",
  },
  {
    "předpokládaný vodní tok",
    "conjectural waterflow",
    NULL,
    NULL,
    "predpokladaný vodný tok",
  },
  {
    "občasný vodní tok",
    "intermittent waterflow",
    NULL,
    NULL,
    "občasný vodný tok",
  },
  {
    "vodní tok",
    "waterflow",
    NULL,
    NULL,
    "vodný tok",
  },
  {
    "průvan",
    "air draught",
    NULL,
    NULL,
    "prievan",
  },
  {
    "nadmořská výška bodu v chodbě",
    "altitude",
    NULL,
    NULL,
    "nadmorská výška bodu v chodbe",
  },
  {
    "anastomóza",
    "anastomosis",
    NULL,
    NULL,
    "anastomóza",
  },
  {
    "kotvení",
    "anchor",
    NULL,
    NULL,
    "kotvenie",
  },
  {
    "aragonit",
    "aragonite",
    NULL,
    NULL,
    "aragonit",
  },
  {
    "archeologické nálezy",
    "archeo material",
    NULL,
    NULL,
    "archeologické nálezy",
  },
  {
    "pevná skála",
    "bedrock",
    NULL,
    NULL,
    "pevná skala",
  },
  {
    "kamenné bloky",
    "blocks, breakdown",
    NULL,
    NULL,
    "kamenné bloky",
  },
  {
    "zavalený konec",
    "breakdown choke",
    NULL,
    NULL,
    "zavalený koniec",
  },
  {
    "most",
    "bridge",
    NULL,
    NULL,
    "most",
  },
  {
    "bivak",
    "camp",
    NULL,
    NULL,
    "bivak",
  },
  {
    "jeskynní perly",
    "cave pearl",
    NULL,
    NULL,
    "jaskynné perly",
  },
  {
    "jíl",
    "clay",
    NULL,
    NULL,
    "blato",
  },
  {
    "možné pokračování",
    "possible continuation",
    NULL,
    NULL,
    "možné pokračovanie",
  },
  {
    "krystal",
    "crystal",
    NULL,
    NULL,
    "kryštál",
  },
  {
    "sintrové záclony",
    "curtain",
    NULL,
    NULL,
    "sintrové záclony",
  },
  {
    "datum pozorování",
    "date of observation",
    NULL,
    NULL,
    "dátum pozorovania",
  },
  {
    "štěrk",
    "debris",
    NULL,
    NULL,
    "štrk",
  },
  {
    "disk",
    "disk",
    NULL,
    NULL,
    "disk",
  },
  {
    "vchod",
    "entrance",
    NULL,
    NULL,
    "vchod",
  },
  {
    "pevný žebřík",
    "fixed ladder",
    NULL,
    NULL,
    "fixný rebrík",
  },
  {
    "sintr",
    "flowstone",
    NULL,
    NULL,
    "sinter",
  },
  {
    "zasintrovaný konec",
    "flowstone choke",
    NULL,
    NULL,
    "zasintrený koniec",
  },
  {
    "píšťaly",
    "flute",
    NULL,
    NULL,
    "píšťaly",
  },
  {
    "sklon chodby",
    "passage gradient",
    NULL,
    NULL,
    "sklon chodby",
  },
  {
    "guano",
    "guano",
    NULL,
    NULL,
    "guáno",
  },
  {
    "sádrovec",
    "gypsum",
    NULL,
    NULL,
    "sádrovec",
  },
  {
    "sádrovcový květ",
    "gypsum flower",
    NULL,
    NULL,
    "sádrovcový kvet",
  },
  {
    "hloubka propasti",
    "pit depth",
    NULL,
    NULL,
    "hĺbka priepasti",
  },
  {
    "výška komínu",
    "chimney height",
    NULL,
    NULL,
    "výška komínu",
  },
  {
    "výška stupně",
    "the height of floor step",
    NULL,
    NULL,
    "výška stupňa",
  },
  {
    "heliktit",
    "helictite",
    NULL,
    NULL,
    "helektit",
  },
  {
    "led",
    "ice",
    NULL,
    NULL,
    "ľad",
  },
  {
    "škrapy",
    "karren",
    NULL,
    NULL,
    "škrapy",
  },
  {
    "neprůlezné snížení",
    "passage low end",
    NULL,
    NULL,
    "neprielezné zníženie",
  },
  {
    "nickamínek",
    "moonmilk",
    NULL,
    NULL,
    "mäkký sinter",
  },
  {
    "neprůlezné zúžení",
    "passage narrow end",
    NULL,
    NULL,
    "neprielezné zúženie",
  },
  {
    "nevystrojené místo",
    "place without equipement",
    NULL,
    NULL,
    "nevystrojené miesto",
  },
  {
    "paleontologické nálezy",
    "paleo material",
    NULL,
    NULL,
    "paleontologické nálezy",
  },
  {
    "výška nad i pod hladinou",
    "height above and depth below water level",
    NULL,
    NULL,
    "výška nad a hĺbka pod hladinou",
  },
  {
    "výška chodby pod hladinou",
    "depth below water level",
    NULL,
    NULL,
    "hĺbka pod hladinou",
  },
  {
    "výška chodby nad hladinou",
    "height above water level",
    NULL,
    NULL,
    "výška nad hladinou",
  },
  {
    "výška chodby",
    "passage height",
    NULL,
    NULL,
    "výška chodby",
  },
  {
    "valouny",
    "pebbles",
    NULL,
    NULL,
    "okruhliaky",
  },
  {
    "stalagnát",
    "pillar",
    NULL,
    NULL,
    "stalagnát",
  },
  {
    "pizolity",
    "popcorn",
    NULL,
    NULL,
    "pizolity",
  },
  {
    "náplav",
    "raft",
    NULL,
    NULL,
    "náplav",
  },
  {
    "náplavový kužel",
    "raft cone",
    NULL,
    NULL,
    "náplavový kužeľ",
  },
  {
    "sintrová hrázka",
    "rimstone dam",
    NULL,
    NULL,
    "sintrová hrádza",
  },
  {
    "sintrové jezírko",
    "rimstone pool",
    NULL,
    NULL,
    "sintrové jazierko",
  },
  {
    "kořeny",
    "root",
    NULL,
    NULL,
    "korene",
  },
  {
    "lano",
    "rope",
    NULL,
    NULL,
    "lano",
  },
  {
    "lanový žebřík",
    "rope ladder",
    NULL,
    NULL,
    "lanový rebrík",
  },
  {
    "písek",
    "sand",
    NULL,
    NULL,
    "piesok",
  },
  {
    "erozní útvary",
    "scallop",
    NULL,
    NULL,
    "erózne útvary",
  },
  {
    "ponor",
    "sink",
    NULL,
    NULL,
    "ponor",
  },
  {
    "brčka",
    "soda straw",
    NULL,
    NULL,
    "brčká",
  },
  {
    "vývěr",
    "spring",
    NULL,
    NULL,
    "výver",
  },
  {
    "stalaktit",
    "stalactite",
    NULL,
    NULL,
    "stalaktit",
  },
  {
    "stalagmit",
    "stalagmite",
    NULL,
    NULL,
    "stalagmit",
  },
  {
    "číslo měřičského bodu",
    "survey station name",
    NULL,
    NULL,
    "číslo meračského bodu",
  },
  {
    "měřičský bod (stabilizovaný)",
    "fixed survey station",
    NULL,
    NULL,
    "meračský bod (stabilizovaný)",
  },
  {
    "měřičský bod (přírodní)",
    "natural survey station",
    NULL,
    NULL,
    "meračský bod (prírodný)",
  },
  {
    "měřičský bod (zabarvený)",
    "painted survey station",
    NULL,
    NULL,
    "meračský bod (zafarbený)",
  },
  {
    "měřičský bod (nestabilizovaný)",
    "temporary survey station",
    NULL,
    NULL,
    "meračský bod (nestabilizovaný)",
  },
  {
    "schody",
    "steps",
    NULL,
    NULL,
    "schody",
  },
  {
    "traverz",
    "traverse",
    NULL,
    NULL,
    "traverz",
  },
  {
    "zbytky rostlin",
    "vegetable debris",
    NULL,
    NULL,
    "zvyšky rastlín",
  },
  {
    "nadmořská výška bodu na stěně",
    "altitude",
    NULL,
    NULL,
    "nadmorská výška bodu na stene",
  },
  {
    "vápencový povlak",
    "wall calcite",
    NULL,
    NULL,
    "vápencový povlak",
  },
  {
    "voda",
    "water",
    NULL,
    NULL,
    "voda",
  },
  {
    "občasný vodní tok",
    "intermittent waterflow",
    NULL,
    NULL,
    "občasný vodný tok",
  },
  {
    "paleořečiště",
    "paleo waterflow",
    NULL,
    NULL,
    "paleoriečisko",
  },
  {
    "vodní tok",
    "waterflow",
    NULL,
    NULL,
    "vodný tok",
  },
  {
    "Kreslil",
    "Drawn by",
    NULL,
    NULL,
    "Kreslil",
  },
  {
    "Kreslili",
    "Drawn by",
    NULL,
    NULL,
    "Kreslili",
  },
  {
    "Převýšení",
    "Depth",
    NULL,
    NULL,
    "Prevýšenie",
  },
  {
    "Délka",
    "Length",
    NULL,
    NULL,
    "Dĺžka",
  },
  {
    "Objevil",
    "Explored by",
    NULL,
    NULL,
    "Objavil",
  },
  {
    "Objevili",
    "Explored by",
    NULL,
    NULL,
    "Objavili",
  },
  {
    "Legenda",
    "Legend",
    NULL,
    NULL,
    "Legenda",
  },
  {
    "[Náhled horních vrstev]",
    "[Preview above]",
    NULL,
    NULL,
    "[Náhľad horných vrstiev]",
  },
  {
    "[Náhled dolních vrstev]",
    "[Preview below]",
    NULL,
    NULL,
    "[Náhľad spodných vrstiev]",
  },
  {
    "Měřil",
    "Surveyed by",
    NULL,
    NULL,
    "Zameral",
  },
  {
    "Měřili",
    "Surveyed by",
    NULL,
    NULL,
    "Zamerali",
  },
  {
    "m",
    "m",
    NULL,
    NULL,
    "m",
  },
};

 
 
