/**
 *  thsymbolsetlist.h
 *
 * THIS FILE IS GENERATED AUTOMATICALLY, DO NOT MODIFY IT !!!
 */  

#ifndef thsymbolsetlist_h
#define thsymbolsetlist_h

#define thsymbolset_size 206

enum {
  SYMA_ = 0,
  SYMA_BEDROCK = 1,
  SYMA_BLOCKS = 2,
  SYMA_CLAY = 3,
  SYMA_DEBRIS = 4,
  SYMA_DIMENSIONS = 5,
  SYMA_FLOWSTONE = 6,
  SYMA_ICE = 7,
  SYMA_MOONMILK = 8,
  SYMA_PEBBLES = 9,
  SYMA_SAND = 10,
  SYMA_SNOW = 11,
  SYMA_SUMP = 12,
  SYMA_U = 13,
  SYMA_WATER = 14,
  SYMA_ZZZ = 15,
  SYML_ = 16,
  SYML_ARROW = 17,
  SYML_BORDER_INVISIBLE = 18,
  SYML_BORDER_PRESUMED = 19,
  SYML_BORDER_TEMPORARY = 20,
  SYML_BORDER_VISIBLE = 21,
  SYML_CEILINGMEANDER = 22,
  SYML_CEILINGSTEP = 23,
  SYML_CHIMNEY = 24,
  SYML_CONTOUR = 25,
  SYML_FIXEDLADDER = 26,
  SYML_FLOORMEANDER = 27,
  SYML_FLOORSTEP = 28,
  SYML_FLOWSTONE = 29,
  SYML_GRADIENT = 30,
  SYML_HANDRAIL = 31,
  SYML_LABEL = 32,
  SYML_MAPCONNECTION = 33,
  SYML_MOONMILK = 34,
  SYML_OVERHANG = 35,
  SYML_PIT = 36,
  SYML_ROCKBORDER = 37,
  SYML_ROCKEDGE = 38,
  SYML_ROPE = 39,
  SYML_ROPELADDER = 40,
  SYML_SECTION = 41,
  SYML_SLOPE = 42,
  SYML_STEPS = 43,
  SYML_SURVEY_CAVE = 44,
  SYML_SURVEY_SURFACE = 45,
  SYML_U = 46,
  SYML_UNDEFINED = 47,
  SYML_VIAFERRATA = 48,
  SYML_WALL_BEDROCK = 49,
  SYML_WALL_BLOCKS = 50,
  SYML_WALL_CLAY = 51,
  SYML_WALL_DEBRIS = 52,
  SYML_WALL_FLOWSTONE = 53,
  SYML_WALL_ICE = 54,
  SYML_WALL_INVISIBLE = 55,
  SYML_WALL_MOONMILK = 56,
  SYML_WALL_OVERLYING = 57,
  SYML_WALL_PEBBLES = 58,
  SYML_WALL_PIT = 59,
  SYML_WALL_PRESUMED = 60,
  SYML_WALL_SAND = 61,
  SYML_WALL_UNDERLYING = 62,
  SYML_WALL_UNSURVEYED = 63,
  SYML_WATERFLOW_CONJECTURAL = 64,
  SYML_WATERFLOW_INTERMITTENT = 65,
  SYML_WATERFLOW_PERMANENT = 66,
  SYML_ZZZ = 67,
  SYMP_ = 68,
  SYMP_AIRDRAUGHT = 69,
  SYMP_AIRDRAUGHT_SUMMER = 70,
  SYMP_AIRDRAUGHT_WINTER = 71,
  SYMP_ALTITUDE = 72,
  SYMP_ANASTOMOSIS = 73,
  SYMP_ANCHOR = 74,
  SYMP_ARAGONITE = 75,
  SYMP_ARCHEOMATERIAL = 76,
  SYMP_BEDROCK = 77,
  SYMP_BLOCKS = 78,
  SYMP_BREAKDOWNCHOKE = 79,
  SYMP_BRIDGE = 80,
  SYMP_CAMP = 81,
  SYMP_CAVEPEARL = 82,
  SYMP_CAVESTATION = 83,
  SYMP_CLAY = 84,
  SYMP_CLAYCHOKE = 85,
  SYMP_CLAYTREE = 86,
  SYMP_CONTINUATION = 87,
  SYMP_CRYSTAL = 88,
  SYMP_CURTAIN = 89,
  SYMP_DATE = 90,
  SYMP_DEBRIS = 91,
  SYMP_DIG = 92,
  SYMP_DISK = 93,
  SYMP_ENTRANCE = 94,
  SYMP_FIXEDLADDER = 95,
  SYMP_FLAG_AIRDRAUGHT = 96,
  SYMP_FLAG_ARCH = 97,
  SYMP_FLAG_CONTINUATION = 98,
  SYMP_FLAG_DIG = 99,
  SYMP_FLAG_DOLINE = 100,
  SYMP_FLAG_ENTRANCE = 101,
  SYMP_FLAG_OVERHANG = 102,
  SYMP_FLAG_SINK = 103,
  SYMP_FLAG_SPRING = 104,
  SYMP_FLOWSTONE = 105,
  SYMP_FLOWSTONECHOKE = 106,
  SYMP_FLUTE = 107,
  SYMP_GRADIENT = 108,
  SYMP_GUANO = 109,
  SYMP_GYPSUM = 110,
  SYMP_GYPSUMFLOWER = 111,
  SYMP_HANDRAIL = 112,
  SYMP_HEIGHT_NEGATIVE = 113,
  SYMP_HEIGHT_POSITIVE = 114,
  SYMP_HEIGHT_UNSIGNED = 115,
  SYMP_HELICTITE = 116,
  SYMP_ICE = 117,
  SYMP_ICEPILLAR = 118,
  SYMP_ICESTALACTITE = 119,
  SYMP_ICESTALAGMITE = 120,
  SYMP_KARREN = 121,
  SYMP_LABEL = 122,
  SYMP_LOWEND = 123,
  SYMP_MAPCONNECTION = 124,
  SYMP_MOONMILK = 125,
  SYMP_NARROWEND = 126,
  SYMP_NOEQUIPMENT = 127,
  SYMP_PALEOMATERIAL = 128,
  SYMP_PASSAGEHEIGHT_BOTH = 129,
  SYMP_PASSAGEHEIGHT_NEGATIVE = 130,
  SYMP_PASSAGEHEIGHT_POSITIVE = 131,
  SYMP_PASSAGEHEIGHT_UNSIGNED = 132,
  SYMP_PEBBLES = 133,
  SYMP_PILLAR = 134,
  SYMP_PILLARS = 135,
  SYMP_POPCORN = 136,
  SYMP_RAFT = 137,
  SYMP_RAFTCONE = 138,
  SYMP_REMARK = 139,
  SYMP_RIMSTONEDAM = 140,
  SYMP_RIMSTONEPOOL = 141,
  SYMP_ROOT = 142,
  SYMP_ROPE = 143,
  SYMP_ROPELADDER = 144,
  SYMP_SAND = 145,
  SYMP_SCALLOP = 146,
  SYMP_SECTION = 147,
  SYMP_SECTIONARROW = 148,
  SYMP_SINK = 149,
  SYMP_SNOW = 150,
  SYMP_SODASTRAW = 151,
  SYMP_SPRING = 152,
  SYMP_STALACTITE = 153,
  SYMP_STALACTITES = 154,
  SYMP_STALAGMITE = 155,
  SYMP_STALAGMITES = 156,
  SYMP_STATION = 157,
  SYMP_STATION_FIXED = 158,
  SYMP_STATION_NATURAL = 159,
  SYMP_STATION_PAINTED = 160,
  SYMP_STATION_TEMPORARY = 161,
  SYMP_STATIONNAME = 162,
  SYMP_STEPS = 163,
  SYMP_SURFACESTATION = 164,
  SYMP_TRAVERSE = 165,
  SYMP_U = 166,
  SYMP_UNDEFINED = 167,
  SYMP_VEGETABLEDEBRIS = 168,
  SYMP_VIAFERRATA = 169,
  SYMP_WALLALTITUDE = 170,
  SYMP_WALLCALCITE = 171,
  SYMP_WATER = 172,
  SYMP_WATERFLOW_INTERMITTENT = 173,
  SYMP_WATERFLOW_PALEO = 174,
  SYMP_WATERFLOW_PERMANENT = 175,
  SYMP_ZZZ = 176,
  SYMS_ = 177,
  SYMS_HGRID = 178,
  SYMS_NORTHARROW = 179,
  SYMS_SCALEBAR = 180,
  SYMS_VGRID = 181,
  SYMS_ZZZ = 182,
  SYMX_ = 183,
  SYMX_ALL = 184,
  SYMX_CAVECENTERLINE = 185,
  SYMX_CENTERLINE = 186,
  SYMX_EQUIPMENT = 187,
  SYMX_ICE = 188,
  SYMX_LINE_BORDER = 189,
  SYMX_LINE_SURVEY = 190,
  SYMX_LINE_WALL = 191,
  SYMX_LINE_WATERFLOW = 192,
  SYMX_PASSAGEFILLS = 193,
  SYMX_POINT_AIRDRAUGHT = 194,
  SYMX_POINT_FLAG = 195,
  SYMX_POINT_HEIGHT = 196,
  SYMX_POINT_PASSAGEHEIGHT = 197,
  SYMX_POINT_STATION = 198,
  SYMX_POINT_WATERFLOW = 199,
  SYMX_SECTIONS = 200,
  SYMX_SEDIMENTS = 201,
  SYMX_SPELEOTHEMS = 202,
  SYMX_SURFACECENTERLINE = 203,
  SYMX_TEXT = 204,
  SYMX_WATER = 205,
};

typedef const char * thsymbolset__char_ptr;

static const thsymbolset__char_ptr thsymbolset__mp [] = {
  "a_",
  "a_bedrock",
  "a_blocks",
  "a_clay",
  "a_debris",
  "a_dimensions",
  "a_flowstone",
  "a_ice",
  "a_moonmilk",
  "a_pebbles",
  "a_sand",
  "a_snow",
  "a_sump",
  "a_u",
  "a_water",
  "a_zzz",
  "l_",
  "l_arrow",
  "l_border_invisible",
  "l_border_presumed",
  "l_border_temporary",
  "l_border_visible",
  "l_ceilingmeander",
  "l_ceilingstep",
  "l_chimney",
  "l_contour",
  "l_fixedladder",
  "l_floormeander",
  "l_floorstep",
  "l_flowstone",
  "l_gradient",
  "l_handrail",
  "l_label",
  "l_mapconnection",
  "l_moonmilk",
  "l_overhang",
  "l_pit",
  "l_rockborder",
  "l_rockedge",
  "l_rope",
  "l_ropeladder",
  "l_section",
  "l_slope",
  "l_steps",
  "l_survey_cave",
  "l_survey_surface",
  "l_u",
  "l_undefined",
  "l_viaferrata",
  "l_wall_bedrock",
  "l_wall_blocks",
  "l_wall_clay",
  "l_wall_debris",
  "l_wall_flowstone",
  "l_wall_ice",
  "l_wall_invisible",
  "l_wall_moonmilk",
  "l_wall_overlying",
  "l_wall_pebbles",
  "l_wall_pit",
  "l_wall_presumed",
  "l_wall_sand",
  "l_wall_underlying",
  "l_wall_unsurveyed",
  "l_waterflow_conjectural",
  "l_waterflow_intermittent",
  "l_waterflow_permanent",
  "l_zzz",
  "p_",
  "p_airdraught",
  "p_airdraught_summer",
  "p_airdraught_winter",
  "p_altitude",
  "p_anastomosis",
  "p_anchor",
  "p_aragonite",
  "p_archeomaterial",
  "p_bedrock",
  "p_blocks",
  "p_breakdownchoke",
  "p_bridge",
  "p_camp",
  "p_cavepearl",
  "p_cavestation",
  "p_clay",
  "p_claychoke",
  "p_claytree",
  "p_continuation",
  "p_crystal",
  "p_curtain",
  "p_date",
  "p_debris",
  "p_dig",
  "p_disk",
  "p_entrance",
  "p_fixedladder",
  "p_flag_airdraught",
  "p_flag_arch",
  "p_flag_continuation",
  "p_flag_dig",
  "p_flag_doline",
  "p_flag_entrance",
  "p_flag_overhang",
  "p_flag_sink",
  "p_flag_spring",
  "p_flowstone",
  "p_flowstonechoke",
  "p_flute",
  "p_gradient",
  "p_guano",
  "p_gypsum",
  "p_gypsumflower",
  "p_handrail",
  "p_height_negative",
  "p_height_positive",
  "p_height_unsigned",
  "p_helictite",
  "p_ice",
  "p_icepillar",
  "p_icestalactite",
  "p_icestalagmite",
  "p_karren",
  "p_label",
  "p_lowend",
  "p_mapconnection",
  "p_moonmilk",
  "p_narrowend",
  "p_noequipment",
  "p_paleomaterial",
  "p_passageheight_both",
  "p_passageheight_negative",
  "p_passageheight_positive",
  "p_passageheight_unsigned",
  "p_pebbles",
  "p_pillar",
  "p_pillars",
  "p_popcorn",
  "p_raft",
  "p_raftcone",
  "p_remark",
  "p_rimstonedam",
  "p_rimstonepool",
  "p_root",
  "p_rope",
  "p_ropeladder",
  "p_sand",
  "p_scallop",
  "p_section",
  "p_sectionarrow",
  "p_sink",
  "p_snow",
  "p_sodastraw",
  "p_spring",
  "p_stalactite",
  "p_stalactites",
  "p_stalagmite",
  "p_stalagmites",
  "p_station",
  "p_station_fixed",
  "p_station_natural",
  "p_station_painted",
  "p_station_temporary",
  "p_stationname",
  "p_steps",
  "p_surfacestation",
  "p_traverse",
  "p_u",
  "p_undefined",
  "p_vegetabledebris",
  "p_viaferrata",
  "p_wallaltitude",
  "p_wallcalcite",
  "p_water",
  "p_waterflow_intermittent",
  "p_waterflow_paleo",
  "p_waterflow_permanent",
  "p_zzz",
  "s_",
  "s_hgrid",
  "s_northarrow",
  "s_scalebar",
  "s_vgrid",
  "s_zzz",
  "x_",
  "x_all",
  "x_cavecenterline",
  "x_centerline",
  "x_equipment",
  "x_ice",
  "x_line_border",
  "x_line_survey",
  "x_line_wall",
  "x_line_waterflow",
  "x_passagefills",
  "x_point_airdraught",
  "x_point_flag",
  "x_point_height",
  "x_point_passageheight",
  "x_point_station",
  "x_point_waterflow",
  "x_sections",
  "x_sediments",
  "x_speleothems",
  "x_surfacecenterline",
  "x_text",
  "x_water",
};

static const bool thsymbolset__assign [] = {
  false,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  false,
  false,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  false,
  true,
  true,
  true,
  true,
  true,
  true,
  false,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  false,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  false,
  false,
  true,
  true,
  true,
  false,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  false,
  true,
  true,
  true,
  true,
  true,
  true,
  false,
  true,
  true,
  true,
  true,
  true,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  false,
  false,
  false,
  true,
  true,
  true,
  true,
  true,
  true,
  false,
  true,
  false,
  true,
  true,
  true,
  true,
  false,
  false,
  false,
  false,
  true,
  true,
  true,
  true,
  true,
  true,
  false,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  false,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  false,
  true,
  false,
  true,
  true,
  false,
  true,
  true,
  false,
  true,
  true,
  true,
  true,
  true,
  false,
  false,
  true,
  true,
  true,
  true,
  false,
  false,
  true,
  false,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  false,
  true,
  true,
};

static const bool thsymbolset__hidden [] = {
  true,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  true,
  true,
  false,
  true,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  true,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  true,
  true,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  true,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  true,
  true,
  false,
  false,
  false,
  false,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
};

static const thsymbolset__char_ptr thsymbolset__src [] = {
  "SYMA_",
  "SYMA_BEDROCK",
  "SYMA_BLOCKS",
  "SYMA_CLAY",
  "SYMA_DEBRIS",
  "SYMA_DIMENSIONS",
  "SYMA_FLOWSTONE",
  "SYMA_ICE",
  "SYMA_MOONMILK",
  "SYMA_PEBBLES",
  "SYMA_SAND",
  "SYMA_SNOW",
  "SYMA_SUMP",
  "SYMA_U",
  "SYMA_WATER",
  "SYMA_ZZZ",
  "SYML_",
  "SYML_ARROW",
  "SYML_BORDER_INVISIBLE",
  "SYML_BORDER_PRESUMED",
  "SYML_BORDER_TEMPORARY",
  "SYML_BORDER_VISIBLE",
  "SYML_CEILINGMEANDER",
  "SYML_CEILINGSTEP",
  "SYML_CHIMNEY",
  "SYML_CONTOUR",
  "SYML_FIXEDLADDER",
  "SYML_FLOORMEANDER",
  "SYML_FLOORSTEP",
  "SYML_FLOWSTONE",
  "SYML_GRADIENT",
  "SYML_HANDRAIL",
  "SYML_LABEL",
  "SYML_MAPCONNECTION",
  "SYML_MOONMILK",
  "SYML_OVERHANG",
  "SYML_PIT",
  "SYML_ROCKBORDER",
  "SYML_ROCKEDGE",
  "SYML_ROPE",
  "SYML_ROPELADDER",
  "SYML_SECTION",
  "SYML_SLOPE",
  "SYML_STEPS",
  "SYML_SURVEY_CAVE",
  "SYML_SURVEY_SURFACE",
  "SYML_U",
  "SYML_UNDEFINED",
  "SYML_VIAFERRATA",
  "SYML_WALL_BEDROCK",
  "SYML_WALL_BLOCKS",
  "SYML_WALL_CLAY",
  "SYML_WALL_DEBRIS",
  "SYML_WALL_FLOWSTONE",
  "SYML_WALL_ICE",
  "SYML_WALL_INVISIBLE",
  "SYML_WALL_MOONMILK",
  "SYML_WALL_OVERLYING",
  "SYML_WALL_PEBBLES",
  "SYML_WALL_PIT",
  "SYML_WALL_PRESUMED",
  "SYML_WALL_SAND",
  "SYML_WALL_UNDERLYING",
  "SYML_WALL_UNSURVEYED",
  "SYML_WATERFLOW_CONJECTURAL",
  "SYML_WATERFLOW_INTERMITTENT",
  "SYML_WATERFLOW_PERMANENT",
  "SYML_ZZZ",
  "SYMP_",
  "SYMP_AIRDRAUGHT",
  "SYMP_AIRDRAUGHT_SUMMER",
  "SYMP_AIRDRAUGHT_WINTER",
  "SYMP_ALTITUDE",
  "SYMP_ANASTOMOSIS",
  "SYMP_ANCHOR",
  "SYMP_ARAGONITE",
  "SYMP_ARCHEOMATERIAL",
  "SYMP_BEDROCK",
  "SYMP_BLOCKS",
  "SYMP_BREAKDOWNCHOKE",
  "SYMP_BRIDGE",
  "SYMP_CAMP",
  "SYMP_CAVEPEARL",
  "SYMP_CAVESTATION",
  "SYMP_CLAY",
  "SYMP_CLAYCHOKE",
  "SYMP_CLAYTREE",
  "SYMP_CONTINUATION",
  "SYMP_CRYSTAL",
  "SYMP_CURTAIN",
  "SYMP_DATE",
  "SYMP_DEBRIS",
  "SYMP_DIG",
  "SYMP_DISK",
  "SYMP_ENTRANCE",
  "SYMP_FIXEDLADDER",
  "SYMP_FLAG_AIRDRAUGHT",
  "SYMP_FLAG_ARCH",
  "SYMP_FLAG_CONTINUATION",
  "SYMP_FLAG_DIG",
  "SYMP_FLAG_DOLINE",
  "SYMP_FLAG_ENTRANCE",
  "SYMP_FLAG_OVERHANG",
  "SYMP_FLAG_SINK",
  "SYMP_FLAG_SPRING",
  "SYMP_FLOWSTONE",
  "SYMP_FLOWSTONECHOKE",
  "SYMP_FLUTE",
  "SYMP_GRADIENT",
  "SYMP_GUANO",
  "SYMP_GYPSUM",
  "SYMP_GYPSUMFLOWER",
  "SYMP_HANDRAIL",
  "SYMP_HEIGHT_NEGATIVE",
  "SYMP_HEIGHT_POSITIVE",
  "SYMP_HEIGHT_UNSIGNED",
  "SYMP_HELICTITE",
  "SYMP_ICE",
  "SYMP_ICEPILLAR",
  "SYMP_ICESTALACTITE",
  "SYMP_ICESTALAGMITE",
  "SYMP_KARREN",
  "SYMP_LABEL",
  "SYMP_LOWEND",
  "SYMP_MAPCONNECTION",
  "SYMP_MOONMILK",
  "SYMP_NARROWEND",
  "SYMP_NOEQUIPMENT",
  "SYMP_PALEOMATERIAL",
  "SYMP_PASSAGEHEIGHT_BOTH",
  "SYMP_PASSAGEHEIGHT_NEGATIVE",
  "SYMP_PASSAGEHEIGHT_POSITIVE",
  "SYMP_PASSAGEHEIGHT_UNSIGNED",
  "SYMP_PEBBLES",
  "SYMP_PILLAR",
  "SYMP_PILLARS",
  "SYMP_POPCORN",
  "SYMP_RAFT",
  "SYMP_RAFTCONE",
  "SYMP_REMARK",
  "SYMP_RIMSTONEDAM",
  "SYMP_RIMSTONEPOOL",
  "SYMP_ROOT",
  "SYMP_ROPE",
  "SYMP_ROPELADDER",
  "SYMP_SAND",
  "SYMP_SCALLOP",
  "SYMP_SECTION",
  "SYMP_SECTIONARROW",
  "SYMP_SINK",
  "SYMP_SNOW",
  "SYMP_SODASTRAW",
  "SYMP_SPRING",
  "SYMP_STALACTITE",
  "SYMP_STALACTITES",
  "SYMP_STALAGMITE",
  "SYMP_STALAGMITES",
  "SYMP_STATION",
  "SYMP_STATION_FIXED",
  "SYMP_STATION_NATURAL",
  "SYMP_STATION_PAINTED",
  "SYMP_STATION_TEMPORARY",
  "SYMP_STATIONNAME",
  "SYMP_STEPS",
  "SYMP_SURFACESTATION",
  "SYMP_TRAVERSE",
  "SYMP_U",
  "SYMP_UNDEFINED",
  "SYMP_VEGETABLEDEBRIS",
  "SYMP_VIAFERRATA",
  "SYMP_WALLALTITUDE",
  "SYMP_WALLCALCITE",
  "SYMP_WATER",
  "SYMP_WATERFLOW_INTERMITTENT",
  "SYMP_WATERFLOW_PALEO",
  "SYMP_WATERFLOW_PERMANENT",
  "SYMP_ZZZ",
  "SYMS_",
  "SYMS_HGRID",
  "SYMS_NORTHARROW",
  "SYMS_SCALEBAR",
  "SYMS_VGRID",
  "SYMS_ZZZ",
  "SYMX_",
  "SYMX_ALL",
  "SYMX_CAVECENTERLINE",
  "SYMX_CENTERLINE",
  "SYMX_EQUIPMENT",
  "SYMX_ICE",
  "SYMX_LINE_BORDER",
  "SYMX_LINE_SURVEY",
  "SYMX_LINE_WALL",
  "SYMX_LINE_WATERFLOW",
  "SYMX_PASSAGEFILLS",
  "SYMX_POINT_AIRDRAUGHT",
  "SYMX_POINT_FLAG",
  "SYMX_POINT_HEIGHT",
  "SYMX_POINT_PASSAGEHEIGHT",
  "SYMX_POINT_STATION",
  "SYMX_POINT_WATERFLOW",
  "SYMX_SECTIONS",
  "SYMX_SEDIMENTS",
  "SYMX_SPELEOTHEMS",
  "SYMX_SURFACECENTERLINE",
  "SYMX_TEXT",
  "SYMX_WATER",
};

static const char thsymbolset__fontchar [] = {
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  33,
  34,
  35,
  0,
  36,
  37,
  38,
  39,
  40,
  41,
  42,
  43,
  44,
  45,
  0,
  46,
  47,
  48,
  49,
  50,
  51,
  0,
  52,
  53,
  54,
  55,
  56,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  57,
  58,
  59,
  60,
  61,
  62,
  63,
  0,
  0,
  0,
  0,
  64,
  65,
  66,
  67,
  68,
  69,
  0,
  70,
  0,
  71,
  72,
  73,
  74,
  0,
  0,
  0,
  0,
  75,
  76,
  0,
  77,
  78,
  79,
  0,
  80,
  81,
  82,
  83,
  84,
  85,
  86,
  0,
  0,
  87,
  88,
  89,
  90,
  91,
  0,
  92,
  0,
  93,
  94,
  95,
  96,
  97,
  0,
  98,
  0,
  99,
  0,
  0,
  100,
  0,
  0,
  101,
  102,
  103,
  104,
  105,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
};

#endif

