/**
 *  thsymbolsetlist.h
 *
 * THIS FILE IS GENERATED AUTOMATICALLY, DO NOT MODIFY IT !!!
 */  

#define thsymbolset_size 154

enum {
  SYMA_ = 0,
  SYMA_BLOCKS = 1,
  SYMA_CLAY = 2,
  SYMA_DEBRIS = 3,
  SYMA_ICE = 4,
  SYMA_PEBBLES = 5,
  SYMA_SAND = 6,
  SYMA_SNOW = 7,
  SYMA_SUMP = 8,
  SYMA_WATER = 9,
  SYMA_ZZZ = 10,
  SYML_ = 11,
  SYML_ARROW = 12,
  SYML_BORDER_INVISIBLE = 13,
  SYML_BORDER_PRESUMED = 14,
  SYML_BORDER_TEMPORARY = 15,
  SYML_BORDER_VISIBLE = 16,
  SYML_CEILINGMEANDER = 17,
  SYML_CEILINGSTEP = 18,
  SYML_CHIMNEY = 19,
  SYML_CONTOUR = 20,
  SYML_FLOORMEANDER = 21,
  SYML_FLOORSTEP = 22,
  SYML_FLOWSTONE = 23,
  SYML_GRADIENT = 24,
  SYML_LABEL = 25,
  SYML_OVERHANG = 26,
  SYML_PIT = 27,
  SYML_ROCKBORDER = 28,
  SYML_ROCKEDGE = 29,
  SYML_SECTION = 30,
  SYML_SLOPE = 31,
  SYML_SURVEY_CAVE = 32,
  SYML_SURVEY_SURFACE = 33,
  SYML_UNDEFINED = 34,
  SYML_WALL_BEDROCK = 35,
  SYML_WALL_BLOCKS = 36,
  SYML_WALL_CLAY = 37,
  SYML_WALL_DEBRIS = 38,
  SYML_WALL_ICE = 39,
  SYML_WALL_INVISIBLE = 40,
  SYML_WALL_PEBBLES = 41,
  SYML_WALL_PRESUMED = 42,
  SYML_WALL_SAND = 43,
  SYML_WALL_UNDERLYING = 44,
  SYML_WALL_UNSURVEYED = 45,
  SYML_WATERFLOW_CONJECTURAL = 46,
  SYML_WATERFLOW_INTERMITTENT = 47,
  SYML_WATERFLOW_PERMANENT = 48,
  SYML_ZZZ = 49,
  SYMP_ = 50,
  SYMP_AIRDRAUGHT = 51,
  SYMP_ALTITUDE = 52,
  SYMP_ANASTOMOSIS = 53,
  SYMP_ANCHOR = 54,
  SYMP_ARAGONITE = 55,
  SYMP_ARCHEOMATERIAL = 56,
  SYMP_BEDROCK = 57,
  SYMP_BLOCKS = 58,
  SYMP_BREAKDOWNCHOKE = 59,
  SYMP_BRIDGE = 60,
  SYMP_CAMP = 61,
  SYMP_CAVEPEARL = 62,
  SYMP_CAVESTATION = 63,
  SYMP_CLAY = 64,
  SYMP_CONTINUATION = 65,
  SYMP_CRYSTAL = 66,
  SYMP_CURTAIN = 67,
  SYMP_DATE = 68,
  SYMP_DEBRIS = 69,
  SYMP_DISK = 70,
  SYMP_ENTRANCE = 71,
  SYMP_FIXEDLADDER = 72,
  SYMP_FLOWSTONE = 73,
  SYMP_FLOWSTONECHOKE = 74,
  SYMP_FLUTE = 75,
  SYMP_GRADIENT = 76,
  SYMP_GUANO = 77,
  SYMP_GYPSUM = 78,
  SYMP_GYPSUMFLOWER = 79,
  SYMP_HEIGHT_NEGATIVE = 80,
  SYMP_HEIGHT_POSITIVE = 81,
  SYMP_HEIGHT_UNSIGNED = 82,
  SYMP_HELICTITE = 83,
  SYMP_ICE = 84,
  SYMP_KARREN = 85,
  SYMP_LABEL = 86,
  SYMP_LOWEND = 87,
  SYMP_MOONMILK = 88,
  SYMP_NARROWEND = 89,
  SYMP_NOEQUIPMENT = 90,
  SYMP_PALEOMATERIAL = 91,
  SYMP_PASSAGEHEIGHT_BOTH = 92,
  SYMP_PASSAGEHEIGHT_NEGATIVE = 93,
  SYMP_PASSAGEHEIGHT_POSITIVE = 94,
  SYMP_PASSAGEHEIGHT_UNSIGNED = 95,
  SYMP_PEBBLES = 96,
  SYMP_PILLAR = 97,
  SYMP_POPCORN = 98,
  SYMP_RAFT = 99,
  SYMP_RAFTCONE = 100,
  SYMP_REMARK = 101,
  SYMP_RIMSTONEDAM = 102,
  SYMP_RIMSTONEPOOL = 103,
  SYMP_ROOT = 104,
  SYMP_ROPE = 105,
  SYMP_ROPELADDER = 106,
  SYMP_SAND = 107,
  SYMP_SCALLOP = 108,
  SYMP_SECTION = 109,
  SYMP_SECTIONARROW = 110,
  SYMP_SINK = 111,
  SYMP_SNOW = 112,
  SYMP_SODASTRAW = 113,
  SYMP_SPRING = 114,
  SYMP_STALACTITE = 115,
  SYMP_STALAGMITE = 116,
  SYMP_STATION_FIXED = 117,
  SYMP_STATION_NATURAL = 118,
  SYMP_STATION_PAINTED = 119,
  SYMP_STATION_TEMPORARY = 120,
  SYMP_STATIONNAME = 121,
  SYMP_STEPS = 122,
  SYMP_SURFACESTATION = 123,
  SYMP_TRAVERSE = 124,
  SYMP_UNDEFINED = 125,
  SYMP_VEGETABLEDEBRIS = 126,
  SYMP_WALLALTITUDE = 127,
  SYMP_WALLCALCITE = 128,
  SYMP_WATER = 129,
  SYMP_WATERFLOW_INTERMITTENT = 130,
  SYMP_WATERFLOW_PALEO = 131,
  SYMP_WATERFLOW_PERMANENT = 132,
  SYMP_ZZZ = 133,
  SYMS_ = 134,
  SYMS_HGRID = 135,
  SYMS_NORTHARROW = 136,
  SYMS_SCALEBAR = 137,
  SYMS_VGRID = 138,
  SYMS_ZZZ = 139,
  SYMX_ = 140,
  SYMX_ALL = 141,
  SYMX_CAVECENTERLINE = 142,
  SYMX_CENTERLINE = 143,
  SYMX_LINE_BORDER = 144,
  SYMX_LINE_SURVEY = 145,
  SYMX_LINE_WALL = 146,
  SYMX_LINE_WATERFLOW = 147,
  SYMX_POINT_HEIGHT = 148,
  SYMX_POINT_PASSAGEHEIGHT = 149,
  SYMX_POINT_STATION = 150,
  SYMX_POINT_WATERFLOW = 151,
  SYMX_SECTIONS = 152,
  SYMX_SURFACECENTERLINE = 153,
};

typedef char * thsymbolset__char_ptr;

static const thsymbolset__char_ptr thsymbolset__mp [] = {
  "a_",
  "a_blocks",
  "a_clay",
  "a_debris",
  "a_ice",
  "a_pebbles",
  "a_sand",
  "a_snow",
  "a_sump",
  "a_water",
  "a_zzz",
  "l_",
  "l_arrow",
  "l_border_invisible",
  "l_border_presumed",
  "l_border_temporary",
  "l_border_visible",
  "l_ceilingmeander",
  "l_ceilingstep",
  "l_chimney",
  "l_contour",
  "l_floormeander",
  "l_floorstep",
  "l_flowstone",
  "l_gradient",
  "l_label",
  "l_overhang",
  "l_pit",
  "l_rockborder",
  "l_rockedge",
  "l_section",
  "l_slope",
  "l_survey_cave",
  "l_survey_surface",
  "l_undefined",
  "l_wall_bedrock",
  "l_wall_blocks",
  "l_wall_clay",
  "l_wall_debris",
  "l_wall_ice",
  "l_wall_invisible",
  "l_wall_pebbles",
  "l_wall_presumed",
  "l_wall_sand",
  "l_wall_underlying",
  "l_wall_unsurveyed",
  "l_waterflow_conjectural",
  "l_waterflow_intermittent",
  "l_waterflow_permanent",
  "l_zzz",
  "p_",
  "p_airdraught",
  "p_altitude",
  "p_anastomosis",
  "p_anchor",
  "p_aragonite",
  "p_archeomaterial",
  "p_bedrock",
  "p_blocks",
  "p_breakdownchoke",
  "p_bridge",
  "p_camp",
  "p_cavepearl",
  "p_cavestation",
  "p_clay",
  "p_continuation",
  "p_crystal",
  "p_curtain",
  "p_date",
  "p_debris",
  "p_disk",
  "p_entrance",
  "p_fixedladder",
  "p_flowstone",
  "p_flowstonechoke",
  "p_flute",
  "p_gradient",
  "p_guano",
  "p_gypsum",
  "p_gypsumflower",
  "p_height_negative",
  "p_height_positive",
  "p_height_unsigned",
  "p_helictite",
  "p_ice",
  "p_karren",
  "p_label",
  "p_lowend",
  "p_moonmilk",
  "p_narrowend",
  "p_noequipment",
  "p_paleomaterial",
  "p_passageheight_both",
  "p_passageheight_negative",
  "p_passageheight_positive",
  "p_passageheight_unsigned",
  "p_pebbles",
  "p_pillar",
  "p_popcorn",
  "p_raft",
  "p_raftcone",
  "p_remark",
  "p_rimstonedam",
  "p_rimstonepool",
  "p_root",
  "p_rope",
  "p_ropeladder",
  "p_sand",
  "p_scallop",
  "p_section",
  "p_sectionarrow",
  "p_sink",
  "p_snow",
  "p_sodastraw",
  "p_spring",
  "p_stalactite",
  "p_stalagmite",
  "p_station_fixed",
  "p_station_natural",
  "p_station_painted",
  "p_station_temporary",
  "p_stationname",
  "p_steps",
  "p_surfacestation",
  "p_traverse",
  "p_undefined",
  "p_vegetabledebris",
  "p_wallaltitude",
  "p_wallcalcite",
  "p_water",
  "p_waterflow_intermittent",
  "p_waterflow_paleo",
  "p_waterflow_permanent",
  "p_zzz",
  "s_",
  "s_hgrid",
  "s_northarrow",
  "s_scalebar",
  "s_vgrid",
  "s_zzz",
  "x_",
  "x_all",
  "x_cavecenterline",
  "x_centerline",
  "x_line_border",
  "x_line_survey",
  "x_line_wall",
  "x_line_waterflow",
  "x_point_height",
  "x_point_passageheight",
  "x_point_station",
  "x_point_waterflow",
  "x_sections",
  "x_surfacecenterline",
};

static const bool thsymbolset__assign [] = {
  false,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  false,
  false,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  false,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  false,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  false,
  false,
  true,
  false,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  false,
  true,
  true,
  true,
  true,
  false,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  false,
  false,
  false,
  true,
  true,
  true,
  false,
  true,
  true,
  true,
  true,
  true,
  false,
  false,
  false,
  false,
  true,
  true,
  true,
  true,
  true,
  false,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  false,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  false,
  true,
  false,
  true,
  false,
  true,
  false,
  true,
  true,
  true,
  true,
  true,
  false,
  false,
  true,
  true,
  true,
  true,
  false,
  false,
  true,
  false,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  false,
};

static const bool thsymbolset__hidden [] = {
  true,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  true,
  true,
  false,
  true,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  true,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  true,
  true,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  true,
  true,
  false,
  false,
  false,
  false,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
};

static const thsymbolset__char_ptr thsymbolset__src [] = {
  "SYMA_",
  "SYMA_BLOCKS",
  "SYMA_CLAY",
  "SYMA_DEBRIS",
  "SYMA_ICE",
  "SYMA_PEBBLES",
  "SYMA_SAND",
  "SYMA_SNOW",
  "SYMA_SUMP",
  "SYMA_WATER",
  "SYMA_ZZZ",
  "SYML_",
  "SYML_ARROW",
  "SYML_BORDER_INVISIBLE",
  "SYML_BORDER_PRESUMED",
  "SYML_BORDER_TEMPORARY",
  "SYML_BORDER_VISIBLE",
  "SYML_CEILINGMEANDER",
  "SYML_CEILINGSTEP",
  "SYML_CHIMNEY",
  "SYML_CONTOUR",
  "SYML_FLOORMEANDER",
  "SYML_FLOORSTEP",
  "SYML_FLOWSTONE",
  "SYML_GRADIENT",
  "SYML_LABEL",
  "SYML_OVERHANG",
  "SYML_PIT",
  "SYML_ROCKBORDER",
  "SYML_ROCKEDGE",
  "SYML_SECTION",
  "SYML_SLOPE",
  "SYML_SURVEY_CAVE",
  "SYML_SURVEY_SURFACE",
  "SYML_UNDEFINED",
  "SYML_WALL_BEDROCK",
  "SYML_WALL_BLOCKS",
  "SYML_WALL_CLAY",
  "SYML_WALL_DEBRIS",
  "SYML_WALL_ICE",
  "SYML_WALL_INVISIBLE",
  "SYML_WALL_PEBBLES",
  "SYML_WALL_PRESUMED",
  "SYML_WALL_SAND",
  "SYML_WALL_UNDERLYING",
  "SYML_WALL_UNSURVEYED",
  "SYML_WATERFLOW_CONJECTURAL",
  "SYML_WATERFLOW_INTERMITTENT",
  "SYML_WATERFLOW_PERMANENT",
  "SYML_ZZZ",
  "SYMP_",
  "SYMP_AIRDRAUGHT",
  "SYMP_ALTITUDE",
  "SYMP_ANASTOMOSIS",
  "SYMP_ANCHOR",
  "SYMP_ARAGONITE",
  "SYMP_ARCHEOMATERIAL",
  "SYMP_BEDROCK",
  "SYMP_BLOCKS",
  "SYMP_BREAKDOWNCHOKE",
  "SYMP_BRIDGE",
  "SYMP_CAMP",
  "SYMP_CAVEPEARL",
  "SYMP_CAVESTATION",
  "SYMP_CLAY",
  "SYMP_CONTINUATION",
  "SYMP_CRYSTAL",
  "SYMP_CURTAIN",
  "SYMP_DATE",
  "SYMP_DEBRIS",
  "SYMP_DISK",
  "SYMP_ENTRANCE",
  "SYMP_FIXEDLADDER",
  "SYMP_FLOWSTONE",
  "SYMP_FLOWSTONECHOKE",
  "SYMP_FLUTE",
  "SYMP_GRADIENT",
  "SYMP_GUANO",
  "SYMP_GYPSUM",
  "SYMP_GYPSUMFLOWER",
  "SYMP_HEIGHT_NEGATIVE",
  "SYMP_HEIGHT_POSITIVE",
  "SYMP_HEIGHT_UNSIGNED",
  "SYMP_HELICTITE",
  "SYMP_ICE",
  "SYMP_KARREN",
  "SYMP_LABEL",
  "SYMP_LOWEND",
  "SYMP_MOONMILK",
  "SYMP_NARROWEND",
  "SYMP_NOEQUIPMENT",
  "SYMP_PALEOMATERIAL",
  "SYMP_PASSAGEHEIGHT_BOTH",
  "SYMP_PASSAGEHEIGHT_NEGATIVE",
  "SYMP_PASSAGEHEIGHT_POSITIVE",
  "SYMP_PASSAGEHEIGHT_UNSIGNED",
  "SYMP_PEBBLES",
  "SYMP_PILLAR",
  "SYMP_POPCORN",
  "SYMP_RAFT",
  "SYMP_RAFTCONE",
  "SYMP_REMARK",
  "SYMP_RIMSTONEDAM",
  "SYMP_RIMSTONEPOOL",
  "SYMP_ROOT",
  "SYMP_ROPE",
  "SYMP_ROPELADDER",
  "SYMP_SAND",
  "SYMP_SCALLOP",
  "SYMP_SECTION",
  "SYMP_SECTIONARROW",
  "SYMP_SINK",
  "SYMP_SNOW",
  "SYMP_SODASTRAW",
  "SYMP_SPRING",
  "SYMP_STALACTITE",
  "SYMP_STALAGMITE",
  "SYMP_STATION_FIXED",
  "SYMP_STATION_NATURAL",
  "SYMP_STATION_PAINTED",
  "SYMP_STATION_TEMPORARY",
  "SYMP_STATIONNAME",
  "SYMP_STEPS",
  "SYMP_SURFACESTATION",
  "SYMP_TRAVERSE",
  "SYMP_UNDEFINED",
  "SYMP_VEGETABLEDEBRIS",
  "SYMP_WALLALTITUDE",
  "SYMP_WALLCALCITE",
  "SYMP_WATER",
  "SYMP_WATERFLOW_INTERMITTENT",
  "SYMP_WATERFLOW_PALEO",
  "SYMP_WATERFLOW_PERMANENT",
  "SYMP_ZZZ",
  "SYMS_",
  "SYMS_HGRID",
  "SYMS_NORTHARROW",
  "SYMS_SCALEBAR",
  "SYMS_VGRID",
  "SYMS_ZZZ",
  "SYMX_",
  "SYMX_ALL",
  "SYMX_CAVECENTERLINE",
  "SYMX_CENTERLINE",
  "SYMX_LINE_BORDER",
  "SYMX_LINE_SURVEY",
  "SYMX_LINE_WALL",
  "SYMX_LINE_WATERFLOW",
  "SYMX_POINT_HEIGHT",
  "SYMX_POINT_PASSAGEHEIGHT",
  "SYMX_POINT_STATION",
  "SYMX_POINT_WATERFLOW",
  "SYMX_SECTIONS",
  "SYMX_SURFACECENTERLINE",
};

