/**
 * @file thtex.h
 *
 * THIS FILE IS GENERATED AUTOMATICALLY, DO NOT MODIFY IT !!!
 */  
 
#ifndef thtex_h
#define thtex_h

/**
 * Metapost source file.
 */
 
const char * thtex_library = 
"%% \n"
"%% therion.tex\n"
"%%\n"
"%% Copyright (C) 2001-2002 Martin Budaj\n"
"%%\n"
"%% -------------------------------------------------------------------- \n"
"%% This program is free software; you can redistribute it and/or modify\n"
"%% it under the terms of the GNU General Public License as published by\n"
"%% the Free Software Foundation; either version 2 of the License, or\n"
"%% any later version.\n"
"%%\n"
"%% This program is distributed in the hope that it will be useful,\n"
"%% but WITHOUT ANY WARRANTY; without even the implied warranty of\n"
"%% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\n"
"%% GNU General Public License for more details.\n"
"%% \n"
"%% You should have received a copy of the GNU General Public License\n"
"%% along with this program; if not, write to the Free Software\n"
"%% Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA\n"
"%% -------------------------------------------------------------------- \n"
"\n"
"% Summary of macros to be used in therion layout files:\n"
"%\n"
"% \\author{}, \\title{}, \\subject{}, \\keywords{} \n"
"%    -- sets the corresponding attributes of PDF file\n"
"%\n"
"% \\opacity{}\n"
"%    -- in transparency mode sets the opacity value\n"
"%\n"
"% \\dopage{}, \\showpointer, \\showpointerlist, \\processpointeritem\n"
"%    -- enables custom layouts of atlas pages (see The TherionBook for details)\n"
"%\n"
"% \\pagesetup{paper-width}{paper-height}\n"
"%           {page-width}{page-height}\n"
"%           {left-margin}{top-margin}\n"
"%    -- used only in atlas mode\n"
"%\n"
"% \\placemaps\n"
"%    -- draws map(s)\n"
"%\n"
"% \\placelegend\n"
"%    -- not supported yet\n"
"%\n"
"% \\TITLE{}\n"
"%    -- creates an empty page with a large title\n"
"\n"
"\\def\\scale{200} % !!! to be defined by therion\n"
"\n"
"\\ifx\\pdfoutput\\undefined\n"
"     \\newlinechar`\\^^J\n"
"     \\immediate\\write16{^^J^^JProcess me with pdfTeX, please!^^J^^J}\n"
"     \\expandafter\\end\n"
"\\fi\n"
"\n"
"\\def\\requiredformat{plain}\n"
"\\ifx\\requiredformat\\fmtname\\else\n"
"     \\newlinechar`\\^^J\n"
"     \\immediate\\write16{^^J^^JTherion works only with plain TeX format!^^J}\n"
"     \\immediate\\write16{Your format is: \\fmtname^^J^^J}\n"
"     \\expandafter\\end\n"
"\\fi\n"
"\n"
"\\parindent=0pt\n"
"\\raggedbottom\n"
"\\nopagenumbers\n"
"\\tracingstats=1\n"
"\n"
"%\\pdfinfo{/Creator <feff%\n"
"%  03b803b703c103af03bf03bd0020%\n"
"%  002800740068006500720069006f006e0029002c0020%\n"
"%  004d0065007400610050006f00730074002c0020%\n"
"%  005400650058>}%\n"
"\\pdfinfo{/Creator (Therion, MetaPost, TeX)}%\n"
"\\pdfcatalog{ /ViewerPreferences << /DisplayDocTitle true >> }\n"
"\n"
"\\def\\wlog#1{}\n"
"\n"
"\\newbox\\xxx\n"
"\\newbox\\mapbox\n"
"\\newbox\\navbox\n"
"%\\newbox\\updownbox\n"
"\\newcount\\pointerE\n"
"\\newcount\\pointerW\n"
"\\newcount\\pointerN\n"
"\\newcount\\pointerS\n"
"\\newtoks\\pointerU\n"
"\\newtoks\\pointerD\n"
"\\newcount\\pagenum\n"
"\\newtoks\\pagename\n"
"\\newtoks\\pagelabel\n"
"\\newtoks\\opacity \\opacity{0.7}\n"
"\\newif\\ifpagenumbering \\pagenumberingfalse\n"
"\n"
"\\let\\ne\\noexpand\n"
"\\def\\notdef{notdef}\n"
"\n"
"% hyperlinks\n"
"\n"
"%\\def\\link#1#2#3#4{%\n"
"%  \\rlap{\\kern#1bp\\raise#2bp\\hbox{%\n"
"%  \\vbox to0bp{\\vss\\hbox to 0bp{\\hss\n"
"%  \\pdfstartlink attr {/Border [0 0 0]} goto name {#4}%\n"
"%  \\pdfrefxform#3\\pdfendlink\\hss}%\n"
"%  \\vss}}}}\n"
"\n"
"\\def\\flatlink#1#2#3#4#5{%\n"
"  \\setbox\\xxx=\\hbox{}\\wd\\xxx=#3bp\\ht\\xxx=#4bp%\n"
"  \\rlap{\\kern#1bp\\raise#2bp\\hbox{%\n"
"  \\vbox to0bp{\\vss\\hbox to 0bp{%\n"
"  \\pdfstartlink attr {/Border [0 0 0]} goto name {#5}%\n"
"  \\box\\xxx\\pdfendlink\\hss}}}}}%\n"
"\n"
"\\def\\textlink#1#2{%\n"
"  \\pdfstartlink attr {/Border [0 0 0]} goto name {#2}#1\\pdfendlink}%\n"
"\n"
"\n"
"\\def\\includechars#1:#2\\endinclude{\\pdfincludechars#1{#2}}\n"
"\n"
"    \n"
"% there should be more general font selection in the future\n"
"\n"
"\\font\\big=csss10 at 20 pt\n"
"\\font\\middle=csss10 at 16 pt\n"
"\\font\\norm=csss10\n"
"\n"
"\\norm\n"
"\n"
"\\def\\legendbox#1#2{\\hbox{\\raise12pt\\vtop{\\pdfrefxform#1}\\quad#2}\\medskip}\n"
"\n"
"\\let\\PL\\pdfliteral\n"
"\n"
"\\def\\PB#1#2#3{\\rlap{\\kern#1bp\\raise#2bp\\hbox{\\pdfrefxform#3}}} %placebox\n"
"\n"
"\\def\\TITLE#1{\\eject\\hbox{}\\vskip5cm\\centerline{\\big#1}\\vfil\\eject}\n"
"\n"
"% processing of the E-W-N-S references\n"
"\n"
"\\def\\showpointer#1{\\ifnum\\the#1=0\\else\\the#1\\fi}\n"
"\n"
"% processing of the up and down references\n"
"\n"
"\\def\\showpointerlist#1{\\edef\\test{\\the#1}\\ifx\\test\\notdef\\else\n"
"                   \\expandafter\\process\\the#1\\endarg\\fi}\n"
"\n"
"\\def\\process#1||#2\\endarg{\n"
"  \\expandafter\\processpointeritem#1\\endarg%\n"
"  \\if@#2@\\def\\next##1\\endarg{}\n"
"  \\else\\let\\next=\\process\\fi\n"
"  \\next#2\\endarg}\n"
"\n"
"\\def\\processpointeritem#1|#2|#3\\endarg{\\hbox{\\textlink{\\arr\\ #2 (#1)}{#3}}}\n"
"\n"
"\\def\\arr{}        % to be redefined in the \\dopage macro\n"
"\n"
"\\newdimen\\scw\n"
"\n"
"\\def\\scalebar#1#2{%  % the number must be less than 500\n"
"    \\scw=#1cm\n"
"    \\divide\\scw by \\scale\n"
"    \\multiply\\scw by \\ifx#2m100\\else31\\fi \n"
"    \\advance\\scw by 0.4pt\n"
"    \\vbox{\\hsize=\\scw\\baselineskip=0pt\n"
"      \\centerline{#1\\thinspace#2}\n"
"      \\line{\\vrule height3pt\\hfil\\vrule}\n"
"      \\hrule\n"
"    }%\n"
"  }\n"
"\n"
"\n"
"% \n"
"\n"
"\\def\\author#1{\\pdfinfo{ /Author <feff#1>}}\n"
"\\def\\title#1{\\pdfinfo{ /Title <feff#1>}}\n"
"\\def\\subject#1{\\pdfinfo{ /Subject <feff#1>}}\n"
"\\def\\keywords#1{\\pdfinfo{ /Keywords <feff#1>}}\n"
"\n"
"\\def\\pagesetup#1#2#3#4#5#6{\n"
"  \\pdfpagewidth#1\n"
"  \\pdfpageheight#2\n"
"  \\hsize#3\n"
"  \\vsize#4\n"
"  \\pdfhorigin#5\n"
"  \\pdfvorigin#6\n"
"  \\hoffset0pt\n"
"  \\voffset0pt\\relax\n"
"}\n"
"\n"
"% actual placing of the page elements\n"
"\n"
"\\def\\dopage{%\n"
"  \\vbox{\\line{\\hfil\\box\\mapbox\\hfil}\n"
"    \\bigskip\n"
"    \\line{%\n"
"     \\vbox to \\ht\\navbox{\n"
"      \\hbox{\\big\\the\\pagelabel\n"
"        \\ifpagenumbering\\space(\\the\\pagenum)\\fi\n"
"        \\space\\middle\\the\\pagename}\n"
"      \\ifpagenumbering\n"
"        \\medskip\n"
"        \\hbox{\\qquad\\qquad\n"
"          \\vtop{%\n"
"  \t    \\hbox to 0pt{\\hss\\showpointer\\pointerN\\hss}\n"
"            \\hbox to 0pt{\\llap{\\showpointer\\pointerW\\hskip0.7em}%\n"
"\t           \\raise1pt\\hbox to 0pt{\\hss$\\updownarrow$\\hss}%\n"
"\t           \\raise1pt\\hbox to 0pt{\\hss$\\leftrightarrow$\\hss}%\n"
"\t\t   \\rlap{\\hskip0.7em\\showpointer\\pointerE}}\n"
"  \t    \\hbox to 0pt{\\hss\\showpointer\\pointerS\\hss}\n"
"\t  }\\qquad\\qquad\n"
"          \\vtop{\n"
"\t    \\def\\arr{$\\uparrow$}\n"
"\t    \\showpointerlist\\pointerU\n"
"\t    \\def\\arr{$\\downarrow$}\n"
"\t    \\showpointerlist\\pointerD\n"
"\t  }\n"
"        }\n"
"      \\fi\n"
"      \\vss\n"
"      \\scalebar{10}m\n"
"      }\\hss\n"
"      \\box\\navbox\n"
"    }\n"
"  }\n"
"}\n"
"\n"
"\\def\\maplegend{}\n"
"\n"
"\\def\\insertmaps{%\n"
"  \\input th_resources\n"
"  \\input th_fontdef\n"
"  \\input th_formdef\n"
"  \\input th_pagedef\n"
"  \\input th_pages\n"
"}\n"
"    \n"
"\\def\\insertlegend{%\n"
"  \\input legend\n"
"}\n"
"\n"
"\\def\\placemaps{\n"
"  \\message{ [Warning: \\string\\placemaps\\space is deprecated; \n"
"            use \\string\\insertmaps] }\n"
"  \\insertmaps\n"
"}\n"
"\n"
"\\errorstopmode\n"
"\n";
 

#endif
