FROM mcr.microsoft.com/devcontainers/base:jammy

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update -qq && apt-get upgrade -y && apt-get install -y \
    bash-completion \
    bwidget \
    catch2 \
    clang \
    clang-tidy \
    cmake \
    g++ \
    ghostscript \
    git \
    imagemagick \
    lcdf-typetools \
    libfmt-dev \
    libfreetype6-dev \
    libjpeg-dev \
    libpng-dev \
    libproj-dev \
    libtk-img-dev \
    libvtk9-dev \
    libwxgtk3.0-gtk3-dev \
    ninja-build \
    python3 \
    survex \
    tcl-dev \
    texlive-binaries \
    texlive-lang-cyrillic \
    texlive-lang-czechslovak \
    texlive-metapost \
    zlib1g-dev
