all:
	pdftex thbook.tex
	pdftex thbook.tex
	pdftex thbook.tex
	perl ../makefile.pl rm ./thbook.log
  
win32:
	"C:/Program files/Therion/bin/win32/pdfetex.exe" thbook.tex
	"C:/Program files/Therion/bin/win32/pdfetex.exe" thbook.tex
	"C:/Program files/Therion/bin/win32/pdfetex.exe" thbook.tex
	perl ../makefile.pl rm ./thbook.log

