# Prevent building with CMake when there are files in the source dir generated by the legacy Therion Makefile.
if (EXISTS ${CMAKE_SOURCE_DIR}/thversion.h)
    message(FATAL_ERROR "Using old Therion Makefile together with new CMake build is not supported, please run \"make clean\" in the source directory and try again.")
endif()
