set(LOCH_HEADERS
    lxAboutDlg.h
    lxFNT10x20_bdf.h
    lxGLC.h
    lxImgIO.h
    lxOptDlg.h
    lxRender.h
    lxSScene.h
    lxSView.h
    lxWX.h
    lxData.h
    lxFNTFreeSans_ttf.h
    lxFNT6x13_bdf.h
    lxGUI.h
    lxLRUD.h
    lxOGLFT.h
    lxPres.h
    lxSetup.h
    lxSTree.h
    lxSStats.h
    lxTriGeom.h
)

set(LOCH_SOURCES
    lxAboutDlg.cxx
    lxGUI.cxx
    lxLRUD.cxx
    lxOGLFT.cxx
    lxPres.cxx
    lxSetup.cxx
    lxSTree.cxx
    lxWX.cxx
    lxData.cxx
    lxGLC.cxx
    lxImgIO.cxx
    lxOptDlg.cxx
    lxRender.cxx
    lxSScene.cxx
    lxSView.cxx
    lxSStats.cxx
    lxTriGeom.cxx
)
