# TODO rename these files to .h
set_source_files_properties(
    ${CMAKE_BINARY_DIR}/thchencdata.cxx
    ${CMAKE_SOURCE_DIR}/thlibrarydata.cxx
    PROPERTIES HEADER_FILE_ONLY TRUE)

set(THERION_SOURCES
    ${CMAKE_BINARY_DIR}/thcsdata.cxx
    ${CMAKE_BINARY_DIR}/thchencdata.cxx
    ${CMAKE_BINARY_DIR}/thmpost.cxx
    ${CMAKE_BINARY_DIR}/thsymbolsets.cxx
    ${CMAKE_BINARY_DIR}/thtex.cxx
    ${CMAKE_SOURCE_DIR}/src/therion-core/th2ddataobject.cxx
    ${CMAKE_SOURCE_DIR}/src/therion-core/tharea.cxx
    ${CMAKE_SOURCE_DIR}/src/therion-core/thattr.cxx
    ${CMAKE_SOURCE_DIR}/src/therion-core/thbezier.cxx
    ${CMAKE_SOURCE_DIR}/src/therion-core/thbuffer.cxx
    ${CMAKE_SOURCE_DIR}/src/therion-core/thcmdline.cxx
    ${CMAKE_SOURCE_DIR}/src/therion-core/thcomment.cxx
    ${CMAKE_SOURCE_DIR}/src/therion-core/thconfig.cxx
    ${CMAKE_SOURCE_DIR}/src/therion-core/thcs.cxx
    ${CMAKE_SOURCE_DIR}/src/therion-core/thdata.cxx
    ${CMAKE_SOURCE_DIR}/src/therion-core/thdatabase.cxx
    ${CMAKE_SOURCE_DIR}/src/therion-core/thdataleg.cxx
    ${CMAKE_SOURCE_DIR}/src/therion-core/thdataobject.cxx
    ${CMAKE_SOURCE_DIR}/src/therion-core/thdatareader.cxx
    ${CMAKE_SOURCE_DIR}/src/therion-core/thdatastation.cxx
    ${CMAKE_SOURCE_DIR}/src/therion-core/thdate.cxx
    ${CMAKE_SOURCE_DIR}/src/therion-core/thdb1d.cxx
    ${CMAKE_SOURCE_DIR}/src/therion-core/thdb2d.cxx
    ${CMAKE_SOURCE_DIR}/src/therion-core/thdb2d00.cxx
    ${CMAKE_SOURCE_DIR}/src/therion-core/thdb2dab.cxx
    ${CMAKE_SOURCE_DIR}/src/therion-core/thdb2dcp.cxx
    ${CMAKE_SOURCE_DIR}/src/therion-core/thdb2dji.cxx
    ${CMAKE_SOURCE_DIR}/src/therion-core/thdb2dlp.cxx
    ${CMAKE_SOURCE_DIR}/src/therion-core/thdb2dmi.cxx
    ${CMAKE_SOURCE_DIR}/src/therion-core/thdb2dprj.cxx
    ${CMAKE_SOURCE_DIR}/src/therion-core/thdb2dpt.cxx
    ${CMAKE_SOURCE_DIR}/src/therion-core/thdb2dxm.cxx
    ${CMAKE_SOURCE_DIR}/src/therion-core/thdb2dxs.cxx
    ${CMAKE_SOURCE_DIR}/src/therion-core/thdb3d.cxx
    ${CMAKE_SOURCE_DIR}/src/therion-core/thendscrap.cxx
    ${CMAKE_SOURCE_DIR}/src/therion-core/thendsurvey.cxx
    ${CMAKE_SOURCE_DIR}/src/therion-core/thepsparse.cxx
    ${CMAKE_SOURCE_DIR}/src/therion-core/therion.cxx
    ${CMAKE_SOURCE_DIR}/src/therion-core/thexception.cxx
    ${CMAKE_SOURCE_DIR}/src/therion-core/thexpdb.cxx
    ${CMAKE_SOURCE_DIR}/src/therion-core/thexpmap.cxx
    ${CMAKE_SOURCE_DIR}/src/therion-core/thexpmodel.cxx
    ${CMAKE_SOURCE_DIR}/src/therion-core/thexport.cxx
    ${CMAKE_SOURCE_DIR}/src/therion-core/thexporter.cxx
    ${CMAKE_SOURCE_DIR}/src/therion-core/thexpshp.cxx
    ${CMAKE_SOURCE_DIR}/src/therion-core/thexpsys.cxx
    ${CMAKE_SOURCE_DIR}/src/therion-core/thexptable.cxx
    ${CMAKE_SOURCE_DIR}/src/therion-core/thexpuni.cxx
    ${CMAKE_SOURCE_DIR}/src/therion-core/thgeomag.cxx
    ${CMAKE_SOURCE_DIR}/src/therion-core/thgrade.cxx
    ${CMAKE_SOURCE_DIR}/src/therion-core/thchenc.cxx
    ${CMAKE_SOURCE_DIR}/src/therion-core/thimport.cxx
    ${CMAKE_SOURCE_DIR}/src/therion-core/thinfnan.cxx
    ${CMAKE_SOURCE_DIR}/src/therion-core/thinit.cxx
    ${CMAKE_SOURCE_DIR}/src/therion-core/thinput.cxx
    ${CMAKE_SOURCE_DIR}/src/therion-core/thjoin.cxx
    ${CMAKE_SOURCE_DIR}/src/therion-core/thlang.cxx
    ${CMAKE_SOURCE_DIR}/src/therion-core/thlayout.cxx
    ${CMAKE_SOURCE_DIR}/src/therion-core/thlayoutclr.cxx
    ${CMAKE_SOURCE_DIR}/src/therion-core/thlayoutln.cxx
    ${CMAKE_SOURCE_DIR}/src/therion-core/thlegenddata.cxx
    ${CMAKE_SOURCE_DIR}/src/therion-core/thlibrary.cxx
    ${CMAKE_SOURCE_DIR}/src/therion-core/thlibrarydata.cxx
    ${CMAKE_SOURCE_DIR}/src/therion-core/thline.cxx
    ${CMAKE_SOURCE_DIR}/src/therion-core/thlocale.cxx
    ${CMAKE_SOURCE_DIR}/src/therion-core/thlog.cxx
    ${CMAKE_SOURCE_DIR}/src/therion-core/thlogfile.cxx
    ${CMAKE_SOURCE_DIR}/src/therion-core/thlookup.cxx
    ${CMAKE_SOURCE_DIR}/src/therion-core/thmap.cxx
    ${CMAKE_SOURCE_DIR}/src/therion-core/thmapstat.cxx
    ${CMAKE_SOURCE_DIR}/src/therion-core/thmbuffer.cxx
    ${CMAKE_SOURCE_DIR}/src/therion-core/thobjectid.cxx
    ${CMAKE_SOURCE_DIR}/src/therion-core/thobjectname.cxx
    ${CMAKE_SOURCE_DIR}/src/therion-core/thobjectsrc.cxx
    ${CMAKE_SOURCE_DIR}/src/therion-core/thparse.cxx
    ${CMAKE_SOURCE_DIR}/src/therion-core/thpdf.cxx
    ${CMAKE_SOURCE_DIR}/src/therion-core/thpdfdata.cxx
    ${CMAKE_SOURCE_DIR}/src/therion-core/thpdfdbg.cxx
    ${CMAKE_SOURCE_DIR}/src/therion-core/thperson.cxx
    ${CMAKE_SOURCE_DIR}/src/therion-core/thpic.cxx
    ${CMAKE_SOURCE_DIR}/src/therion-core/thpoint.cxx
    ${CMAKE_SOURCE_DIR}/src/therion-core/thproj.cxx
    ${CMAKE_SOURCE_DIR}/src/therion-core/thscan.cxx
    ${CMAKE_SOURCE_DIR}/src/therion-core/thscrap.cxx
    ${CMAKE_SOURCE_DIR}/src/therion-core/thscrapen.cxx
    ${CMAKE_SOURCE_DIR}/src/therion-core/thscrapis.cxx
    ${CMAKE_SOURCE_DIR}/src/therion-core/thscraplo.cxx
    ${CMAKE_SOURCE_DIR}/src/therion-core/thscraplp.cxx
    ${CMAKE_SOURCE_DIR}/src/therion-core/thselector.cxx
    ${CMAKE_SOURCE_DIR}/src/therion-core/thsketch.cxx
    ${CMAKE_SOURCE_DIR}/src/therion-core/thsurface.cxx
    ${CMAKE_SOURCE_DIR}/src/therion-core/thsurvey.cxx
    ${CMAKE_SOURCE_DIR}/src/therion-core/thsvg.cxx
    ${CMAKE_SOURCE_DIR}/src/therion-core/thsvxctrl.cxx
    ${CMAKE_SOURCE_DIR}/src/therion-core/thsymbolset.cxx
    ${CMAKE_SOURCE_DIR}/src/therion-core/thtexfonts.cxx
    ${CMAKE_SOURCE_DIR}/src/therion-core/thtf.cxx
    ${CMAKE_SOURCE_DIR}/src/therion-core/thtfangle.cxx
    ${CMAKE_SOURCE_DIR}/src/therion-core/thtflength.cxx
    ${CMAKE_SOURCE_DIR}/src/therion-core/thtfpwf.cxx
    ${CMAKE_SOURCE_DIR}/src/therion-core/thtmpdir.cxx
    ${CMAKE_SOURCE_DIR}/src/therion-core/thtrans.cxx
    ${CMAKE_SOURCE_DIR}/src/therion-core/thwarp.cxx
    ${CMAKE_SOURCE_DIR}/src/therion-core/thwarpp.cxx
    ${CMAKE_SOURCE_DIR}/src/therion-core/thwarppme.cxx
    ${CMAKE_SOURCE_DIR}/src/therion-core/thwarppt.cxx
)
